#pragma once

// Umbrella header - includes all component headers
#include "component_enums.h"

// Already split components
#include "battery.h"
#include "switch.h"
#include "relay.h"

// Per-component headers
#include "hold_button.h"
#include "resistor.h"
#include "load.h"
#include "ref_node.h"
#include "bus.h"
#include "blueprint_input.h"
#include "blueprint_output.h"
#include "generator.h"
#include "gs24.h"
#include "transformer.h"
#include "inverter.h"
#include "lerp_node.h"
#include "pid.h"
#include "pd.h"
#include "pi.h"
#include "p.h"
#include "splitter.h"
#include "merger.h"
#include "current_sense.h"
#include "indicator_light.h"
#include "high_power_load.h"
#include "voltmeter.h"
#include "voltage_sense.h"
#include "controlled_voltage_source.h"
#include "controlled_current_source.h"
#include "variable_conductance.h"
#include "gyroscope.h"
#include "agk47.h"
#include "electric_pump.h"
#include "solenoid_valve.h"
#include "gidro_accumulator.h"
#include "fuel_tank.h"
#include "inertia_node.h"
#include "spring.h"
#include "temp_sensor.h"
#include "electric_heater.h"
#include "rug82.h"
#include "dmr400.h"
#include "ru19a.h"
#include "radiator.h"
#include "azs.h"
#include "comparator.h"
#include "subtract.h"
#include "multiply.h"
#include "divide.h"
#include "add.h"
#include "and_gate.h"
#include "or_gate.h"
#include "xor_gate.h"
#include "not_gate.h"
#include "nand_gate.h"
#include "any_v_to_bool.h"
#include "positive_v_to_bool.h"
#include "lut.h"
#include "fast_tmo.h"
#include "asym_tmo.h"
#include "slew_rate.h"
#include "asym_slew_rate.h"
#include "time_delay.h"
#include "monostable.h"
#include "sample_hold.h"
#include "accumulator.h"
#include "integrator.h"
#include "clamp.h"
#include "normalize.h"
#include "min.h"
#include "max.h"
#include "greater.h"
#include "lesser.h"
#include "greater_eq.h"
#include "lesser_eq.h"
#include "slider.h"
#include "electrical_conductance.h"
#include "electrical_source.h"
#include "value.h"

// No class declarations here - all are in their respective headers
