// Auto-generated by codegen from library/*.blueprint
// DO NOT EDIT - changes will be overwritten
//
// Lightweight header containing only the PortNames enum.
// Split from port_registry.h to avoid circular includes:
//   component.h → port_registry.h → all.h → component.h
// This file has NO dependency on component headers.

#pragma once

#include <cstdint>

// Port names enum (for constexpr Provider pattern)
// Used by AOT components to get compile-time port indices
enum class PortNames : uint32_t {
    A,
    B,
    Va,
    Vb,
    Vin,
    ac_out,
    brightness,
    charge_out,
    cmd,
    control,
    ctrl,
    damping,
    dc_in,
    ext,
    feedback,
    flow_in,
    flow_out,
    force_out,
    heat_in,
    heat_out,
    i,
    i1,
    i2,
    i_out,
    in,
    input,
    inv_inertia,
    k_mod,
    lamp,
    level_out,
    mass,
    o,
    o1,
    o2,
    out,
    output,
    p_in,
    p_out,
    port,
    pos_a,
    pos_b,
    power,
    primary,
    reset,
    rpm_out,
    secondary,
    setpoint,
    soc_out,
    state,
    t4_out,
    temp,
    temp_in,
    temp_out,
    torque_in,
    trigger,
    tripped,
    v,
    v_bus,
    v_gen,
    v_gen_ref,
    v_in,
    v_neg,
    v_out,
    v_pos,
    v_ref,
    v_start
};
