// Auto-generated by codegen from components/*.json
// DO NOT EDIT - changes will be overwritten
// 
// This file contains port definitions for all components.
// Port offsets are calculated to ensure C++ fields match JSON registry.

#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>
#include <variant>

namespace an24 {
enum class PortNames : uint32_t;
} // namespace an24

#include "provider.h"
#include "all.h"

namespace an24 {

// Port names enum (for constexpr Provider pattern)
// Used by AOT components to get compile-time port indices
enum class PortNames : uint32_t {
    Va,
    Vb,
    ac_out,
    brightness,
    control,
    ctrl,
    dc_in,
    flow_in,
    flow_out,
    heat_in,
    heat_out,
    i,
    input,
    k_mod,
    lamp,
    o,
    o1,
    o2,
    output,
    p_out,
    power,
    primary,
    rpm_out,
    secondary,
    state,
    t4_out,
    temp_in,
    temp_out,
    v,
    v_bus,
    v_gen,
    v_gen_ref,
    v_in,
    v_out,
    v_start
};

// Component type enumeration
enum class ComponentType {
    AGK47,
    Battery,
    Bus,
    Comparator,
    DMR400,
    ElectricHeater,
    ElectricPump,
    GS24,
    Generator,
    Gyroscope,
    HighPowerLoad,
    HoldButton,
    IndicatorLight,
    InertiaNode,
    Inverter,
    LerpNode,
    Load,
    RU19A,
    RUG82,
    Radiator,
    RefNode,
    Relay,
    Resistor,
    SolenoidValve,
    Splitter,
    Switch,
    TempSensor,
    Transformer,
    Voltmeter
};

// Port count for each component
constexpr size_t AGK47_PORT_COUNT = 1;
constexpr size_t Battery_PORT_COUNT = 2;
constexpr size_t Bus_PORT_COUNT = 1;
constexpr size_t Comparator_PORT_COUNT = 3;
constexpr size_t DMR400_PORT_COUNT = 4;
constexpr size_t ElectricHeater_PORT_COUNT = 2;
constexpr size_t ElectricPump_PORT_COUNT = 2;
constexpr size_t GS24_PORT_COUNT = 3;
constexpr size_t Generator_PORT_COUNT = 2;
constexpr size_t Gyroscope_PORT_COUNT = 1;
constexpr size_t HighPowerLoad_PORT_COUNT = 2;
constexpr size_t HoldButton_PORT_COUNT = 4;
constexpr size_t IndicatorLight_PORT_COUNT = 3;
constexpr size_t InertiaNode_PORT_COUNT = 2;
constexpr size_t Inverter_PORT_COUNT = 2;
constexpr size_t LerpNode_PORT_COUNT = 2;
constexpr size_t Load_PORT_COUNT = 1;
constexpr size_t RU19A_PORT_COUNT = 5;
constexpr size_t RUG82_PORT_COUNT = 2;
constexpr size_t Radiator_PORT_COUNT = 2;
constexpr size_t RefNode_PORT_COUNT = 1;
constexpr size_t Relay_PORT_COUNT = 3;
constexpr size_t Resistor_PORT_COUNT = 2;
constexpr size_t SolenoidValve_PORT_COUNT = 3;
constexpr size_t Splitter_PORT_COUNT = 3;
constexpr size_t Switch_PORT_COUNT = 4;
constexpr size_t TempSensor_PORT_COUNT = 2;
constexpr size_t Transformer_PORT_COUNT = 2;
constexpr size_t Voltmeter_PORT_COUNT = 1;

// Port names for each component (in field declaration order)
constexpr const char* AGK47_PORTS[] = {
    "input"
};
constexpr const char* Battery_PORTS[] = {
    "v_in",
    "v_out"
};
constexpr const char* Bus_PORTS[] = {
    "v"
};
constexpr const char* Comparator_PORTS[] = {
    "Va",
    "Vb",
    "o"
};
constexpr const char* DMR400_PORTS[] = {
    "lamp",
    "v_gen_ref",
    "v_in",
    "v_out"
};
constexpr const char* ElectricHeater_PORTS[] = {
    "heat_out",
    "power"
};
constexpr const char* ElectricPump_PORTS[] = {
    "p_out",
    "v_in"
};
constexpr const char* GS24_PORTS[] = {
    "k_mod",
    "v_in",
    "v_out"
};
constexpr const char* Generator_PORTS[] = {
    "v_in",
    "v_out"
};
constexpr const char* Gyroscope_PORTS[] = {
    "input"
};
constexpr const char* HighPowerLoad_PORTS[] = {
    "v_in",
    "v_out"
};
constexpr const char* HoldButton_PORTS[] = {
    "control",
    "state",
    "v_in",
    "v_out"
};
constexpr const char* IndicatorLight_PORTS[] = {
    "brightness",
    "v_in",
    "v_out"
};
constexpr const char* InertiaNode_PORTS[] = {
    "input",
    "output"
};
constexpr const char* Inverter_PORTS[] = {
    "ac_out",
    "dc_in"
};
constexpr const char* LerpNode_PORTS[] = {
    "input",
    "output"
};
constexpr const char* Load_PORTS[] = {
    "input"
};
constexpr const char* RU19A_PORTS[] = {
    "k_mod",
    "rpm_out",
    "t4_out",
    "v_bus",
    "v_start"
};
constexpr const char* RUG82_PORTS[] = {
    "k_mod",
    "v_gen"
};
constexpr const char* Radiator_PORTS[] = {
    "heat_in",
    "heat_out"
};
constexpr const char* RefNode_PORTS[] = {
    "v"
};
constexpr const char* Relay_PORTS[] = {
    "control",
    "v_in",
    "v_out"
};
constexpr const char* Resistor_PORTS[] = {
    "v_in",
    "v_out"
};
constexpr const char* SolenoidValve_PORTS[] = {
    "ctrl",
    "flow_in",
    "flow_out"
};
constexpr const char* Splitter_PORTS[] = {
    "i",
    "o1",
    "o2"
};
constexpr const char* Switch_PORTS[] = {
    "control",
    "state",
    "v_in",
    "v_out"
};
constexpr const char* TempSensor_PORTS[] = {
    "temp_in",
    "temp_out"
};
constexpr const char* Transformer_PORTS[] = {
    "primary",
    "secondary"
};
constexpr const char* Voltmeter_PORTS[] = {
    "v_in"
};

// Get port names for a component type
inline std::vector<std::string> get_component_ports(const std::string& classname) {
    static const std::unordered_map<std::string, std::vector<std::string>> registry = {
        {"AGK47", {"input"}},
        {"Battery", {"v_in", "v_out"}},
        {"Bus", {"v"}},
        {"Comparator", {"Va", "Vb", "o"}},
        {"DMR400", {"lamp", "v_gen_ref", "v_in", "v_out"}},
        {"ElectricHeater", {"heat_out", "power"}},
        {"ElectricPump", {"p_out", "v_in"}},
        {"GS24", {"k_mod", "v_in", "v_out"}},
        {"Generator", {"v_in", "v_out"}},
        {"Gyroscope", {"input"}},
        {"HighPowerLoad", {"v_in", "v_out"}},
        {"HoldButton", {"control", "state", "v_in", "v_out"}},
        {"IndicatorLight", {"brightness", "v_in", "v_out"}},
        {"InertiaNode", {"input", "output"}},
        {"Inverter", {"ac_out", "dc_in"}},
        {"LerpNode", {"input", "output"}},
        {"Load", {"input"}},
        {"RU19A", {"k_mod", "rpm_out", "t4_out", "v_bus", "v_start"}},
        {"RUG82", {"k_mod", "v_gen"}},
        {"Radiator", {"heat_in", "heat_out"}},
        {"RefNode", {"v"}},
        {"Relay", {"control", "v_in", "v_out"}},
        {"Resistor", {"v_in", "v_out"}},
        {"SolenoidValve", {"ctrl", "flow_in", "flow_out"}},
        {"Splitter", {"i", "o1", "o2"}},
        {"Switch", {"control", "state", "v_in", "v_out"}},
        {"TempSensor", {"temp_in", "temp_out"}},
        {"Transformer", {"primary", "secondary"}},
        {"Voltmeter", {"v_in"}},
    };

    auto it = registry.find(classname);
    if (it != registry.end()) {
        return it->second;
    }
    return {};
}

// Component variant for dynamic component storage (Editor JIT mode)
// Enables type-safe storage of any component type without virtual calls
using ComponentVariant = std::variant<
    AGK47<JitProvider>,
    Battery<JitProvider>,
    Bus<JitProvider>,
    Comparator<JitProvider>,
    DMR400<JitProvider>,
    ElectricHeater<JitProvider>,
    ElectricPump<JitProvider>,
    GS24<JitProvider>,
    Generator<JitProvider>,
    Gyroscope<JitProvider>,
    HighPowerLoad<JitProvider>,
    HoldButton<JitProvider>,
    IndicatorLight<JitProvider>,
    InertiaNode<JitProvider>,
    Inverter<JitProvider>,
    LerpNode<JitProvider>,
    Load<JitProvider>,
    RU19A<JitProvider>,
    RUG82<JitProvider>,
    Radiator<JitProvider>,
    RefNode<JitProvider>,
    Relay<JitProvider>,
    Resistor<JitProvider>,
    SolenoidValve<JitProvider>,
    Splitter<JitProvider>,
    Switch<JitProvider>,
    TempSensor<JitProvider>,
    Transformer<JitProvider>,
    Voltmeter<JitProvider>
>;

// Visitor helper for calling solve_electrical on component variant
template <typename... Visitors>
struct overloaded : Visitors... {
    using Visitors::operator()...;
};

// Helper visitor to call solve_electrical on any component
inline auto solve_electrical_visitor = [](auto& component, SimulationState& st, float dt) {
    component.solve_electrical(st, dt);
};

// Helper visitor to call post_step on any component (optional)
inline auto post_step_visitor = [](auto& component, SimulationState& st, float dt) {
    if constexpr (requires { component.post_step(st, dt); }) {
        component.post_step(st, dt);
    }
};

} // namespace an24
