// Auto-generated by codegen from library/*.json
// DO NOT EDIT - changes will be overwritten
// 
// This file contains port definitions for all components.
// Port offsets are calculated to ensure C++ fields match JSON registry.

#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>
#include <optional>
#include <vector>
#include <variant>

namespace an24 {
enum class PortNames : uint32_t;
} // namespace an24

#include "provider.h"
#include "all.h"

namespace an24 {

// Port names enum (for constexpr Provider pattern)
// Used by AOT components to get compile-time port indices
enum class PortNames : uint32_t {
    A,
    B,
    Va,
    Vb,
    Vin,
    ac_out,
    brightness,
    control,
    ctrl,
    dc_in,
    ext,
    feedback,
    flow_in,
    flow_out,
    heat_in,
    heat_out,
    i,
    i1,
    i2,
    in,
    input,
    k_mod,
    lamp,
    o,
    o1,
    o2,
    out,
    output,
    p_out,
    port,
    power,
    primary,
    rpm_out,
    secondary,
    setpoint,
    state,
    t4_out,
    temp,
    temp_in,
    temp_out,
    tripped,
    v,
    v_bus,
    v_gen,
    v_gen_ref,
    v_in,
    v_out,
    v_start
};

// Component type enumeration
enum class ComponentType {
    AGK47,
    AND,
    AZS,
    Add,
    Any_V_to_Bool,
    AsymTMO,
    Battery,
    BlueprintInput,
    BlueprintOutput,
    Bus,
    Comparator,
    DMR400,
    Divide,
    ElectricHeater,
    ElectricPump,
    FastTMO,
    GS24,
    Generator,
    Gyroscope,
    HighPowerLoad,
    HoldButton,
    IndicatorLight,
    InertiaNode,
    Inverter,
    LUT,
    LerpNode,
    Load,
    Merger,
    Multiply,
    NAND,
    NOT,
    OR,
    P,
    PD,
    PI,
    PID,
    Positive_V_to_Bool,
    RU19A,
    RUG82,
    Radiator,
    RefNode,
    Relay,
    Resistor,
    SlewRate,
    SolenoidValve,
    Splitter,
    Subtract,
    Switch,
    TempSensor,
    Transformer,
    Voltmeter,
    XOR
};

// Port count for each component
constexpr size_t AGK47_PORT_COUNT = 1;
constexpr size_t AND_PORT_COUNT = 3;
constexpr size_t AZS_PORT_COUNT = 6;
constexpr size_t Add_PORT_COUNT = 3;
constexpr size_t Any_V_to_Bool_PORT_COUNT = 2;
constexpr size_t AsymTMO_PORT_COUNT = 2;
constexpr size_t Battery_PORT_COUNT = 2;
constexpr size_t BlueprintInput_PORT_COUNT = 2;
constexpr size_t BlueprintOutput_PORT_COUNT = 2;
constexpr size_t Bus_PORT_COUNT = 1;
constexpr size_t Comparator_PORT_COUNT = 3;
constexpr size_t DMR400_PORT_COUNT = 4;
constexpr size_t Divide_PORT_COUNT = 3;
constexpr size_t ElectricHeater_PORT_COUNT = 2;
constexpr size_t ElectricPump_PORT_COUNT = 2;
constexpr size_t FastTMO_PORT_COUNT = 2;
constexpr size_t GS24_PORT_COUNT = 3;
constexpr size_t Generator_PORT_COUNT = 2;
constexpr size_t Gyroscope_PORT_COUNT = 1;
constexpr size_t HighPowerLoad_PORT_COUNT = 2;
constexpr size_t HoldButton_PORT_COUNT = 4;
constexpr size_t IndicatorLight_PORT_COUNT = 3;
constexpr size_t InertiaNode_PORT_COUNT = 2;
constexpr size_t Inverter_PORT_COUNT = 2;
constexpr size_t LUT_PORT_COUNT = 2;
constexpr size_t LerpNode_PORT_COUNT = 2;
constexpr size_t Load_PORT_COUNT = 1;
constexpr size_t Merger_PORT_COUNT = 3;
constexpr size_t Multiply_PORT_COUNT = 3;
constexpr size_t NAND_PORT_COUNT = 3;
constexpr size_t NOT_PORT_COUNT = 2;
constexpr size_t OR_PORT_COUNT = 3;
constexpr size_t P_PORT_COUNT = 3;
constexpr size_t PD_PORT_COUNT = 3;
constexpr size_t PI_PORT_COUNT = 3;
constexpr size_t PID_PORT_COUNT = 3;
constexpr size_t Positive_V_to_Bool_PORT_COUNT = 2;
constexpr size_t RU19A_PORT_COUNT = 5;
constexpr size_t RUG82_PORT_COUNT = 2;
constexpr size_t Radiator_PORT_COUNT = 2;
constexpr size_t RefNode_PORT_COUNT = 1;
constexpr size_t Relay_PORT_COUNT = 3;
constexpr size_t Resistor_PORT_COUNT = 2;
constexpr size_t SlewRate_PORT_COUNT = 2;
constexpr size_t SolenoidValve_PORT_COUNT = 3;
constexpr size_t Splitter_PORT_COUNT = 3;
constexpr size_t Subtract_PORT_COUNT = 3;
constexpr size_t Switch_PORT_COUNT = 4;
constexpr size_t TempSensor_PORT_COUNT = 2;
constexpr size_t Transformer_PORT_COUNT = 2;
constexpr size_t Voltmeter_PORT_COUNT = 1;
constexpr size_t XOR_PORT_COUNT = 3;

// Port names for each component (in field declaration order)
constexpr const char* AGK47_PORTS[] = {
    "input"
};
constexpr const char* AND_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* AZS_PORTS[] = {
    "control",
    "state",
    "temp",
    "tripped",
    "v_in",
    "v_out"
};
constexpr const char* Add_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* Any_V_to_Bool_PORTS[] = {
    "Vin",
    "o"
};
constexpr const char* AsymTMO_PORTS[] = {
    "in",
    "out"
};
constexpr const char* Battery_PORTS[] = {
    "v_in",
    "v_out"
};
constexpr const char* BlueprintInput_PORTS[] = {
    "ext",
    "port"
};
constexpr const char* BlueprintOutput_PORTS[] = {
    "ext",
    "port"
};
constexpr const char* Bus_PORTS[] = {
    "v"
};
constexpr const char* Comparator_PORTS[] = {
    "Va",
    "Vb",
    "o"
};
constexpr const char* DMR400_PORTS[] = {
    "lamp",
    "v_gen_ref",
    "v_in",
    "v_out"
};
constexpr const char* Divide_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* ElectricHeater_PORTS[] = {
    "heat_out",
    "power"
};
constexpr const char* ElectricPump_PORTS[] = {
    "p_out",
    "v_in"
};
constexpr const char* FastTMO_PORTS[] = {
    "in",
    "out"
};
constexpr const char* GS24_PORTS[] = {
    "k_mod",
    "v_in",
    "v_out"
};
constexpr const char* Generator_PORTS[] = {
    "v_in",
    "v_out"
};
constexpr const char* Gyroscope_PORTS[] = {
    "input"
};
constexpr const char* HighPowerLoad_PORTS[] = {
    "v_in",
    "v_out"
};
constexpr const char* HoldButton_PORTS[] = {
    "control",
    "state",
    "v_in",
    "v_out"
};
constexpr const char* IndicatorLight_PORTS[] = {
    "brightness",
    "v_in",
    "v_out"
};
constexpr const char* InertiaNode_PORTS[] = {
    "input",
    "output"
};
constexpr const char* Inverter_PORTS[] = {
    "ac_out",
    "dc_in"
};
constexpr const char* LUT_PORTS[] = {
    "input",
    "output"
};
constexpr const char* LerpNode_PORTS[] = {
    "input",
    "output"
};
constexpr const char* Load_PORTS[] = {
    "input"
};
constexpr const char* Merger_PORTS[] = {
    "i1",
    "i2",
    "o"
};
constexpr const char* Multiply_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* NAND_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* NOT_PORTS[] = {
    "A",
    "o"
};
constexpr const char* OR_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* P_PORTS[] = {
    "feedback",
    "output",
    "setpoint"
};
constexpr const char* PD_PORTS[] = {
    "feedback",
    "output",
    "setpoint"
};
constexpr const char* PI_PORTS[] = {
    "feedback",
    "output",
    "setpoint"
};
constexpr const char* PID_PORTS[] = {
    "feedback",
    "output",
    "setpoint"
};
constexpr const char* Positive_V_to_Bool_PORTS[] = {
    "Vin",
    "o"
};
constexpr const char* RU19A_PORTS[] = {
    "k_mod",
    "rpm_out",
    "t4_out",
    "v_bus",
    "v_start"
};
constexpr const char* RUG82_PORTS[] = {
    "k_mod",
    "v_gen"
};
constexpr const char* Radiator_PORTS[] = {
    "heat_in",
    "heat_out"
};
constexpr const char* RefNode_PORTS[] = {
    "v"
};
constexpr const char* Relay_PORTS[] = {
    "control",
    "v_in",
    "v_out"
};
constexpr const char* Resistor_PORTS[] = {
    "v_in",
    "v_out"
};
constexpr const char* SlewRate_PORTS[] = {
    "in",
    "out"
};
constexpr const char* SolenoidValve_PORTS[] = {
    "ctrl",
    "flow_in",
    "flow_out"
};
constexpr const char* Splitter_PORTS[] = {
    "i",
    "o1",
    "o2"
};
constexpr const char* Subtract_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* Switch_PORTS[] = {
    "control",
    "state",
    "v_in",
    "v_out"
};
constexpr const char* TempSensor_PORTS[] = {
    "temp_in",
    "temp_out"
};
constexpr const char* Transformer_PORTS[] = {
    "primary",
    "secondary"
};
constexpr const char* Voltmeter_PORTS[] = {
    "v_in"
};
constexpr const char* XOR_PORTS[] = {
    "A",
    "B",
    "o"
};

// Get port names for a component type
// Convert port name string to PortNames enum
// Auto-generated from components/*.json — never maintain by hand!
inline std::optional<PortNames> string_to_port_name(const std::string& name) {
    static const std::unordered_map<std::string, PortNames> map = {
        {"A", PortNames::A},
        {"B", PortNames::B},
        {"Va", PortNames::Va},
        {"Vb", PortNames::Vb},
        {"Vin", PortNames::Vin},
        {"ac_out", PortNames::ac_out},
        {"brightness", PortNames::brightness},
        {"control", PortNames::control},
        {"ctrl", PortNames::ctrl},
        {"dc_in", PortNames::dc_in},
        {"ext", PortNames::ext},
        {"feedback", PortNames::feedback},
        {"flow_in", PortNames::flow_in},
        {"flow_out", PortNames::flow_out},
        {"heat_in", PortNames::heat_in},
        {"heat_out", PortNames::heat_out},
        {"i", PortNames::i},
        {"i1", PortNames::i1},
        {"i2", PortNames::i2},
        {"in", PortNames::in},
        {"input", PortNames::input},
        {"k_mod", PortNames::k_mod},
        {"lamp", PortNames::lamp},
        {"o", PortNames::o},
        {"o1", PortNames::o1},
        {"o2", PortNames::o2},
        {"out", PortNames::out},
        {"output", PortNames::output},
        {"p_out", PortNames::p_out},
        {"port", PortNames::port},
        {"power", PortNames::power},
        {"primary", PortNames::primary},
        {"rpm_out", PortNames::rpm_out},
        {"secondary", PortNames::secondary},
        {"setpoint", PortNames::setpoint},
        {"state", PortNames::state},
        {"t4_out", PortNames::t4_out},
        {"temp", PortNames::temp},
        {"temp_in", PortNames::temp_in},
        {"temp_out", PortNames::temp_out},
        {"tripped", PortNames::tripped},
        {"v", PortNames::v},
        {"v_bus", PortNames::v_bus},
        {"v_gen", PortNames::v_gen},
        {"v_gen_ref", PortNames::v_gen_ref},
        {"v_in", PortNames::v_in},
        {"v_out", PortNames::v_out},
        {"v_start", PortNames::v_start},
    };
    auto it = map.find(name);
    if (it != map.end()) return it->second;
    return std::nullopt;
}

// Get port names for a component type
inline std::vector<std::string> get_component_ports(const std::string& classname) {
    static const std::unordered_map<std::string, std::vector<std::string>> registry = {
        {"AGK47", {"input"}},
        {"AND", {"A", "B", "o"}},
        {"AZS", {"control", "state", "temp", "tripped", "v_in", "v_out"}},
        {"Add", {"A", "B", "o"}},
        {"Any_V_to_Bool", {"Vin", "o"}},
        {"AsymTMO", {"in", "out"}},
        {"Battery", {"v_in", "v_out"}},
        {"BlueprintInput", {"ext", "port"}},
        {"BlueprintOutput", {"ext", "port"}},
        {"Bus", {"v"}},
        {"Comparator", {"Va", "Vb", "o"}},
        {"DMR400", {"lamp", "v_gen_ref", "v_in", "v_out"}},
        {"Divide", {"A", "B", "o"}},
        {"ElectricHeater", {"heat_out", "power"}},
        {"ElectricPump", {"p_out", "v_in"}},
        {"FastTMO", {"in", "out"}},
        {"GS24", {"k_mod", "v_in", "v_out"}},
        {"Generator", {"v_in", "v_out"}},
        {"Gyroscope", {"input"}},
        {"HighPowerLoad", {"v_in", "v_out"}},
        {"HoldButton", {"control", "state", "v_in", "v_out"}},
        {"IndicatorLight", {"brightness", "v_in", "v_out"}},
        {"InertiaNode", {"input", "output"}},
        {"Inverter", {"ac_out", "dc_in"}},
        {"LUT", {"input", "output"}},
        {"LerpNode", {"input", "output"}},
        {"Load", {"input"}},
        {"Merger", {"i1", "i2", "o"}},
        {"Multiply", {"A", "B", "o"}},
        {"NAND", {"A", "B", "o"}},
        {"NOT", {"A", "o"}},
        {"OR", {"A", "B", "o"}},
        {"P", {"feedback", "output", "setpoint"}},
        {"PD", {"feedback", "output", "setpoint"}},
        {"PI", {"feedback", "output", "setpoint"}},
        {"PID", {"feedback", "output", "setpoint"}},
        {"Positive_V_to_Bool", {"Vin", "o"}},
        {"RU19A", {"k_mod", "rpm_out", "t4_out", "v_bus", "v_start"}},
        {"RUG82", {"k_mod", "v_gen"}},
        {"Radiator", {"heat_in", "heat_out"}},
        {"RefNode", {"v"}},
        {"Relay", {"control", "v_in", "v_out"}},
        {"Resistor", {"v_in", "v_out"}},
        {"SlewRate", {"in", "out"}},
        {"SolenoidValve", {"ctrl", "flow_in", "flow_out"}},
        {"Splitter", {"i", "o1", "o2"}},
        {"Subtract", {"A", "B", "o"}},
        {"Switch", {"control", "state", "v_in", "v_out"}},
        {"TempSensor", {"temp_in", "temp_out"}},
        {"Transformer", {"primary", "secondary"}},
        {"Voltmeter", {"v_in"}},
        {"XOR", {"A", "B", "o"}},
    };

    auto it = registry.find(classname);
    if (it != registry.end()) {
        return it->second;
    }
    return {};
}

// Component variant for dynamic component storage (Editor JIT mode)
// Enables type-safe storage of any component type without virtual calls
using ComponentVariant = std::variant<
    AGK47<JitProvider>,
    AND<JitProvider>,
    AZS<JitProvider>,
    Add<JitProvider>,
    Any_V_to_Bool<JitProvider>,
    AsymTMO<JitProvider>,
    Battery<JitProvider>,
    BlueprintInput<JitProvider>,
    BlueprintOutput<JitProvider>,
    Bus<JitProvider>,
    Comparator<JitProvider>,
    DMR400<JitProvider>,
    Divide<JitProvider>,
    ElectricHeater<JitProvider>,
    ElectricPump<JitProvider>,
    FastTMO<JitProvider>,
    GS24<JitProvider>,
    Generator<JitProvider>,
    Gyroscope<JitProvider>,
    HighPowerLoad<JitProvider>,
    HoldButton<JitProvider>,
    IndicatorLight<JitProvider>,
    InertiaNode<JitProvider>,
    Inverter<JitProvider>,
    LUT<JitProvider>,
    LerpNode<JitProvider>,
    Load<JitProvider>,
    Merger<JitProvider>,
    Multiply<JitProvider>,
    NAND<JitProvider>,
    NOT<JitProvider>,
    OR<JitProvider>,
    P<JitProvider>,
    PD<JitProvider>,
    PI<JitProvider>,
    PID<JitProvider>,
    Positive_V_to_Bool<JitProvider>,
    RU19A<JitProvider>,
    RUG82<JitProvider>,
    Radiator<JitProvider>,
    RefNode<JitProvider>,
    Relay<JitProvider>,
    Resistor<JitProvider>,
    SlewRate<JitProvider>,
    SolenoidValve<JitProvider>,
    Splitter<JitProvider>,
    Subtract<JitProvider>,
    Switch<JitProvider>,
    TempSensor<JitProvider>,
    Transformer<JitProvider>,
    Voltmeter<JitProvider>,
    XOR<JitProvider>
>;

// Visitor helper for calling solve_electrical on component variant
template <typename... Visitors>
struct overloaded : Visitors... {
    using Visitors::operator()...;
};

// Helper visitor to call solve_electrical on any component
inline auto solve_electrical_visitor = [](auto& component, SimulationState& st, float dt) {
    component.solve_electrical(st, dt);
};

// Helper visitor to call post_step on any component (optional)
inline auto post_step_visitor = [](auto& component, SimulationState& st, float dt) {
    if constexpr (requires { component.post_step(st, dt); }) {
        component.post_step(st, dt);
    }
};

} // namespace an24
