if(EXISTS "/Users/vladimir/an24_cpp/tests/blueprint_v2_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/blueprint_v2_tests[1]_tests.cmake")
else()
  add_test(blueprint_v2_tests_NOT_BUILT blueprint_v2_tests_NOT_BUILT)
endif()
