if(EXISTS "/Users/vladimir/an24_cpp/tests/blueprint_loading_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/blueprint_loading_tests[1]_tests.cmake")
else()
  add_test(blueprint_loading_tests_NOT_BUILT blueprint_loading_tests_NOT_BUILT)
endif()
