if(EXISTS "/Users/vladimir/an24_cpp/tests/codegen_accumulator_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/codegen_accumulator_tests[1]_tests.cmake")
else()
  add_test(codegen_accumulator_tests_NOT_BUILT codegen_accumulator_tests_NOT_BUILT)
endif()
