if(EXISTS "/Users/vladimir/an24_cpp/tests/comparison_components_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/comparison_components_tests[1]_tests.cmake")
else()
  add_test(comparison_components_tests_NOT_BUILT comparison_components_tests_NOT_BUILT)
endif()
