if(EXISTS "/Users/vladimir/an24_cpp/tests/document_window_system_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/document_window_system_tests[1]_tests.cmake")
else()
  add_test(document_window_system_tests_NOT_BUILT document_window_system_tests_NOT_BUILT)
endif()
