if(EXISTS "/Users/vladimir/an24_cpp/tests/dt_regression_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/dt_regression_tests[1]_tests.cmake")
else()
  add_test(dt_regression_tests_NOT_BUILT dt_regression_tests_NOT_BUILT)
endif()
