if(EXISTS "/Users/vladimir/an24_cpp/tests/editor_widget_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/editor_widget_tests[1]_tests.cmake")
else()
  add_test(editor_widget_tests_NOT_BUILT editor_widget_tests_NOT_BUILT)
endif()
