if(EXISTS "/Users/vladimir/an24_cpp/tests/editor_componentvariant_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/editor_componentvariant_tests[1]_tests.cmake")
else()
  add_test(editor_componentvariant_tests_NOT_BUILT editor_componentvariant_tests_NOT_BUILT)
endif()
