if(EXISTS "/Users/vladimir/an24_cpp/tests/flat_blueprint_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/flat_blueprint_tests[1]_tests.cmake")
else()
  add_test(flat_blueprint_tests_NOT_BUILT flat_blueprint_tests_NOT_BUILT)
endif()
