if(EXISTS "/Users/vladimir/an24_cpp/tests/gidro_accumulator_regression_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/gidro_accumulator_regression_tests[1]_tests.cmake")
else()
  add_test(gidro_accumulator_regression_tests_NOT_BUILT gidro_accumulator_regression_tests_NOT_BUILT)
endif()
