if(EXISTS "/Users/vladimir/an24_cpp/tests/integrator_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/integrator_tests[1]_tests.cmake")
else()
  add_test(integrator_tests_NOT_BUILT integrator_tests_NOT_BUILT)
endif()
