if(EXISTS "/Users/vladimir/an24_cpp/tests/json_parser_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/json_parser_tests[1]_tests.cmake")
else()
  add_test(json_parser_tests_NOT_BUILT json_parser_tests_NOT_BUILT)
endif()
