if(EXISTS "/Users/vladimir/an24_cpp/tests/library_v2_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/library_v2_tests[1]_tests.cmake")
else()
  add_test(library_v2_tests_NOT_BUILT library_v2_tests_NOT_BUILT)
endif()
