if(EXISTS "/Users/vladimir/an24_cpp/tests/multi_domain_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/multi_domain_tests[1]_tests.cmake")
else()
  add_test(multi_domain_tests_NOT_BUILT multi_domain_tests_NOT_BUILT)
endif()
