if(EXISTS "/Users/vladimir/an24_cpp/tests/multi_window_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/multi_window_tests[1]_tests.cmake")
else()
  add_test(multi_window_tests_NOT_BUILT multi_window_tests_NOT_BUILT)
endif()
