if(EXISTS "/Users/vladimir/an24_cpp/tests/node_deletion_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/node_deletion_tests[1]_tests.cmake")
else()
  add_test(node_deletion_tests_NOT_BUILT node_deletion_tests_NOT_BUILT)
endif()
