if(EXISTS "/Users/vladimir/an24_cpp/tests/node_color_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/node_color_tests[1]_tests.cmake")
else()
  add_test(node_color_tests_NOT_BUILT node_color_tests_NOT_BUILT)
endif()
