if(EXISTS "/Users/vladimir/an24_cpp/tests/params_integrity_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/params_integrity_tests[1]_tests.cmake")
else()
  add_test(params_integrity_tests_NOT_BUILT params_integrity_tests_NOT_BUILT)
endif()
