#include <gtest/gtest.h>
#include <nlohmann/json.hpp>
#include <fstream>
#include <filesystem>

// Test that ensures component ports in JSON match C++ field names
// This should FAIL initially, then PASS after we implement codegen

TEST(PortRegistryTest, RU19A_Ports_Match_JsonRegistry) {
    // Load RU19A definition from registry
    std::ifstream registry_file(std::string(TEST_DATA_DIR) + "/components/RU19A.json");
    ASSERT_TRUE(registry_file.is_open());

    nlohmann::json registry;
    registry_file >> registry;

    // Expected ports from JSON registry
    std::vector<std::string> expected_ports = {
        "v_start", "v_bus", "k_mod", "v_gen_mon", "rpm_out", "t4_out"
    };

    // Get actual ports from registry
    std::vector<std::string> actual_ports;
    for (auto& [port_name, _] : registry["default_ports"].items()) {
        actual_ports.push_back(port_name);
    }

    // Sort for comparison
    std::sort(expected_ports.begin(), expected_ports.end());
    std::sort(actual_ports.begin(), actual_ports.end());

    EXPECT_EQ(expected_ports, actual_ports);
}

TEST(PortRegistryTest, DMR400_Ports_Match_JsonRegistry) {
    std::ifstream registry_file(std::string(TEST_DATA_DIR) + "/components/DMR400.json");
    ASSERT_TRUE(registry_file.is_open());

    nlohmann::json registry;
    registry_file >> registry;

    std::vector<std::string> expected_ports = {
        "v_gen_ref", "v_in", "v_out", "lamp"
    };

    std::vector<std::string> actual_ports;
    for (auto& [port_name, _] : registry["default_ports"].items()) {
        actual_ports.push_back(port_name);
    }

    std::sort(expected_ports.begin(), expected_ports.end());
    std::sort(actual_ports.begin(), actual_ports.end());

    EXPECT_EQ(expected_ports, actual_ports);
}

// Test that will verify generated port_registry.h exists and is valid
TEST(PortRegistryTest, GeneratedPortRegistryExists) {
    std::ifstream registry_file(std::string(TEST_DATA_DIR) + "/src/jit_solver/components/port_registry.h");
    ASSERT_TRUE(registry_file.is_open())
        << "port_registry.h should be generated by codegen from components/*.json";
}

// Test that port offsets are correct (after generation)
TEST(PortRegistryTest, RU19A_PortOffsets_AreCorrect) {
    // This will verify that offsetof(RU19A, v_start_idx) matches generated offset
    // After implementation, port_registry.h will have:
    // constexpr size_t RU19A_v_start_offset = 0;
    // constexpr size_t RU19A_v_bus_offset = 4;
    // etc.

    // For now, just expect the file to contain correct patterns
    std::ifstream registry_file(std::string(TEST_DATA_DIR) + "/src/jit_solver/components/port_registry.h");
    ASSERT_TRUE(registry_file.is_open());

    std::string content((std::istreambuf_iterator<char>(registry_file)),
                        std::istreambuf_iterator<char>());

    // Should contain RU19A port definitions
    EXPECT_NE(content.find("RU19A"), std::string::npos);
    EXPECT_NE(content.find("v_start"), std::string::npos);
    EXPECT_NE(content.find("v_bus"), std::string::npos);
}

// Test component count
TEST(PortRegistryTest, AllComponentsInRegistry) {
    // Count JSON files in components/
    int json_count = 0;
    std::string components_dir = std::string(TEST_DATA_DIR) + "/components";
    for (const auto& entry : std::filesystem::directory_iterator(components_dir)) {
        if (entry.path().extension() == ".json") {
            json_count++;
        }
    }

    // Expect at least 26 components
    EXPECT_GE(json_count, 26);
}
