#include <gtest/gtest.h>
#include <nlohmann/json.hpp>
#include <fstream>
#include <filesystem>

// Test that will verify generated port_registry.h exists and is valid
TEST(PortRegistryTest, GeneratedPortRegistryExists) {
    std::ifstream registry_file(std::string(TEST_DATA_DIR) + "/src/jit_solver/components/port_registry.h");
    ASSERT_TRUE(registry_file.is_open())
        << "port_registry.h should be generated by codegen from components/*.json";
}

// Test type count
TEST(PortRegistryTest, AllTypesInRegistry) {
    // Count .blueprint files in library/
    int blueprint_count = 0;
    std::string library_dir = std::string(TEST_DATA_DIR) + "/library";
    for (const auto& entry : std::filesystem::recursive_directory_iterator(library_dir)) {
        if (entry.is_regular_file() && entry.path().extension() == ".blueprint") {
            blueprint_count++;
        }
    }

    // Expect at least 40 component types (after removing RU19A, DMR400, RUG82, AGK47, GS24)
    EXPECT_GE(blueprint_count, 40);
}
