if(EXISTS "/Users/vladimir/an24_cpp/tests/port_map_regression_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/port_map_regression_tests[1]_tests.cmake")
else()
  add_test(port_map_regression_tests_NOT_BUILT port_map_regression_tests_NOT_BUILT)
endif()
