if(EXISTS "/Users/vladimir/an24_cpp/tests/port_registry_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/port_registry_tests[1]_tests.cmake")
else()
  add_test(port_registry_tests_NOT_BUILT port_registry_tests_NOT_BUILT)
endif()
