if(EXISTS "/Users/vladimir/an24_cpp/tests/properties_window_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/properties_window_tests[1]_tests.cmake")
else()
  add_test(properties_window_tests_NOT_BUILT properties_window_tests_NOT_BUILT)
endif()
