if(EXISTS "/Users/vladimir/an24_cpp/tests/radiator_regression_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/radiator_regression_tests[1]_tests.cmake")
else()
  add_test(radiator_regression_tests_NOT_BUILT radiator_regression_tests_NOT_BUILT)
endif()
