if(EXISTS "/Users/vladimir/an24_cpp/tests/refactoring_regression_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/refactoring_regression_tests[1]_tests.cmake")
else()
  add_test(refactoring_regression_tests_NOT_BUILT refactoring_regression_tests_NOT_BUILT)
endif()
