if(EXISTS "/Users/vladimir/an24_cpp/tests/subtract_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/subtract_tests[1]_tests.cmake")
else()
  add_test(subtract_tests_NOT_BUILT subtract_tests_NOT_BUILT)
endif()
