if(EXISTS "/Users/vladimir/an24_cpp/tests/switch_regression_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/switch_regression_tests[1]_tests.cmake")
else()
  add_test(switch_regression_tests_NOT_BUILT switch_regression_tests_NOT_BUILT)
endif()
