if(EXISTS "/Users/vladimir/an24_cpp/tests/time_delay_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/time_delay_tests[1]_tests.cmake")
else()
  add_test(time_delay_tests_NOT_BUILT time_delay_tests_NOT_BUILT)
endif()
