if(EXISTS "/Users/vladimir/an24_cpp/tests/transformer_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/transformer_tests[1]_tests.cmake")
else()
  add_test(transformer_tests_NOT_BUILT transformer_tests_NOT_BUILT)
endif()
