if(EXISTS "/Users/vladimir/an24_cpp/tests/v_to_bool_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/v_to_bool_tests[1]_tests.cmake")
else()
  add_test(v_to_bool_tests_NOT_BUILT v_to_bool_tests_NOT_BUILT)
endif()
