if(EXISTS "/Users/vladimir/an24_cpp/tests/visual_container_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/tests/visual_container_tests[1]_tests.cmake")
else()
  add_test(visual_container_tests_NOT_BUILT visual_container_tests_NOT_BUILT)
endif()
