if(EXISTS "/Users/vladimir/an24_cpp/build_test2/tests/push_runtime_regression_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_test2/tests/push_runtime_regression_tests[1]_tests.cmake")
else()
  add_test(push_runtime_regression_tests_NOT_BUILT push_runtime_regression_tests_NOT_BUILT)
endif()
