if(EXISTS "/Users/vladimir/an24_cpp/build_fulltests/tests/editor_viewport_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_fulltests/tests/editor_viewport_tests[1]_tests.cmake")
else()
  add_test(editor_viewport_tests_NOT_BUILT editor_viewport_tests_NOT_BUILT)
endif()
