if(EXISTS "/Users/vladimir/an24_cpp/build_fulltests/tests/electrical_handle_build_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_fulltests/tests/electrical_handle_build_tests[1]_tests.cmake")
else()
  add_test(electrical_handle_build_tests_NOT_BUILT electrical_handle_build_tests_NOT_BUILT)
endif()
