if(EXISTS "/Users/vladimir/an24_cpp/build_fulltests/tests/external_ref_signal_mapping_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_fulltests/tests/external_ref_signal_mapping_tests[1]_tests.cmake")
else()
  add_test(external_ref_signal_mapping_tests_NOT_BUILT external_ref_signal_mapping_tests_NOT_BUILT)
endif()
