if(EXISTS "/Users/vladimir/an24_cpp/build_fulltests/tests/oscilloscope_stats_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_fulltests/tests/oscilloscope_stats_tests[1]_tests.cmake")
else()
  add_test(oscilloscope_stats_tests_NOT_BUILT oscilloscope_stats_tests_NOT_BUILT)
endif()
