if(EXISTS "/Users/vladimir/an24_cpp/build_fulltests/tests/port_layout_resolver_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_fulltests/tests/port_layout_resolver_tests[1]_tests.cmake")
else()
  add_test(port_layout_resolver_tests_NOT_BUILT port_layout_resolver_tests_NOT_BUILT)
endif()
