if(EXISTS "/Users/vladimir/an24_cpp/build_fulltests/tests/sam28_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_fulltests/tests/sam28_tests[1]_tests.cmake")
else()
  add_test(sam28_tests_NOT_BUILT sam28_tests_NOT_BUILT)
endif()
