if(EXISTS "/Users/vladimir/an24_cpp/build_fulltests/tests/sor_regression_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_fulltests/tests/sor_regression_tests[1]_tests.cmake")
else()
  add_test(sor_regression_tests_NOT_BUILT sor_regression_tests_NOT_BUILT)
endif()
