if(EXISTS "/Users/vladimir/an24_cpp/build_fulltests/tests/splitter_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_fulltests/tests/splitter_tests[1]_tests.cmake")
else()
  add_test(splitter_tests_NOT_BUILT splitter_tests_NOT_BUILT)
endif()
