// Auto-generated by codegen from library/*.blueprint
// DO NOT EDIT - changes will be overwritten

#include "jit_solver_internal.h"
#include "build_components_common.h"
#include "components/all.h"

#include <algorithm>

namespace jit_solver_impl {

// Per-component param consumers — the "data" in data-driven.
// Each overload is selected by the generic template via overload resolution.

static void consume_params(AND<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(AZS<JitProvider>& comp, ParamReader& param_reader) {
    comp.closed = param_reader.consume_bool_optional("closed", false);
    comp.g_closed = param_reader.consume_float_optional("g_closed", 1000.0f);
    comp.g_open = param_reader.consume_float_optional("g_open", 1e-6f);
    comp.i_nominal = param_reader.consume_float_optional("i_nominal", 20.0f);
    comp.k_cool = param_reader.consume_float_optional("k_cool", 1.0f);
}

static void consume_params(Accumulator<JitProvider>& comp, ParamReader& param_reader) {
    comp.initial_val = param_reader.consume_float_optional("initial_val", 0.0f);
}

static void consume_params(Add<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(Any_V_to_Bool<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(AsymSlewRate<JitProvider>& comp, ParamReader& param_reader) {
    comp.deadzone = param_reader.consume_float_optional("deadzone", 0.0001f);
    comp.rate_down = param_reader.consume_float_optional("rate_down", 0.5f);
    comp.rate_up = param_reader.consume_float_optional("rate_up", 1.0f);
}

static void consume_params(AsymTMO<JitProvider>& comp, ParamReader& param_reader) {
    comp.deadzone = param_reader.consume_float_optional("deadzone", 0.001f);
    comp.tau_down = param_reader.consume_float_optional("tau_down", 0.5f);
    comp.tau_up = param_reader.consume_float_optional("tau_up", 0.1f);
}

static void consume_params(Bus<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(Clamp<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(Comparator<JitProvider>& comp, ParamReader& param_reader) {
    comp.Voff = param_reader.consume_float_optional("Voff", 2.0f);
    comp.Von = param_reader.consume_float_optional("Von", 5.0f);
}

static void consume_params(ControlledCurrentSource<JitProvider>& comp, ParamReader& param_reader) {
    comp.g_shunt = param_reader.consume_float_optional("g_shunt", 0.001f);
    comp.gain = param_reader.consume_float_optional("gain", 1.0f);
    comp.max_i = param_reader.consume_float_optional("max_i", 100.0f);
    comp.min_i = param_reader.consume_float_optional("min_i", 0.0f);
}

static void consume_params(ControlledVoltageSource<JitProvider>& comp, ParamReader& param_reader) {
    comp.r_internal = param_reader.consume_float_optional("r_internal", 0.1f);
}

static void consume_params(CurrentSense<JitProvider>& comp, ParamReader& param_reader) {
    comp.conductance = param_reader.consume_float_optional("conductance", 0.05f);
}

static void consume_params(Divide<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(ElectricHeater<JitProvider>& comp, ParamReader& param_reader) {
    comp.efficiency = param_reader.consume_float_optional("efficiency", 0.9f);
    comp.max_power = param_reader.consume_float_optional("max_power", 1000.0f);
}

static void consume_params(ElectricPump<JitProvider>& comp, ParamReader& param_reader) {
    comp.max_pressure = param_reader.consume_float_optional("max_pressure", 1000.0f);
}

static void consume_params(ElectricalConductance<JitProvider>& comp, ParamReader& param_reader) {
    comp.conductance = param_reader.consume_float_optional("conductance", 0.1f);
}

static void consume_params(ElectricalSource<JitProvider>& comp, ParamReader& param_reader) {
    comp.resistance = param_reader.consume_float_optional("resistance", 0.01f);
    comp.voltage = param_reader.consume_float_optional("voltage", 28.0f);
}

static void consume_params(FastTMO<JitProvider>& comp, ParamReader& param_reader) {
    comp.deadzone = param_reader.consume_float_optional("deadzone", 0.001f);
    comp.tau = param_reader.consume_float_optional("tau", 0.1f);
}

static void consume_params(FuelTank<JitProvider>& comp, ParamReader& param_reader) {
    comp.capacity = param_reader.consume_float_optional("capacity", 1000.0f);
    comp.consumption_rate = param_reader.consume_float_optional("consumption_rate", 0.0f);
    comp.density = param_reader.consume_float_optional("density", 0.78f);
    comp.internal_r = param_reader.consume_float_optional("internal_r", 0.1f);
    comp.level = param_reader.consume_float_optional("level", 1000.0f);
    comp.tank_height = param_reader.consume_float_optional("tank_height", 1.0f);
}

static void consume_params(Generator<JitProvider>& comp, ParamReader& param_reader) {
    comp.internal_r = param_reader.consume_float_optional("internal_r", 0.005f);
    comp.v_nominal = param_reader.consume_float_optional("v_nominal", 28.5f);
}

static void consume_params(Greater<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(GreaterEq<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(Gyroscope<JitProvider>& comp, ParamReader& param_reader) {
    comp.conductance = param_reader.consume_float_optional("conductance", 0.035f);
}

static void consume_params(HoldButton<JitProvider>& comp, ParamReader& param_reader) {
    comp.g_closed = param_reader.consume_float_optional("g_closed", 1000.0f);
    comp.g_open = param_reader.consume_float_optional("g_open", 1e-6f);
    comp.idle = param_reader.consume_float_optional("idle", 0.0f);
}

static void consume_params(HydraulicAccumulator<JitProvider>& comp, ParamReader& param_reader) {
    comp.precharge_pressure = param_reader.consume_float_optional("precharge_pressure", 50.0f);
    comp.volume = param_reader.consume_float_optional("volume", 10.0f);
}

static void consume_params(IndicatorLight<JitProvider>& comp, ParamReader& param_reader) {
    comp.conductance = param_reader.consume_float_optional("conductance", 0.002f);
    comp.rated_voltage = param_reader.consume_float_optional("rated_voltage", 28.0f);
}

static void consume_params(InertiaNode<JitProvider>& comp, ParamReader& param_reader) {
    comp.initial_rpm = param_reader.consume_float_optional("initial_rpm", 1.0f);
}

static void consume_params(Integrator<JitProvider>& comp, ParamReader& param_reader) {
    comp.initial_val = param_reader.consume_float_optional("initial_val", 0.0f);
}

static void consume_params(Inverter<JitProvider>& comp, ParamReader& param_reader) {
    comp.efficiency = param_reader.consume_float_optional("efficiency", 0.95f);
    comp.frequency = param_reader.consume_float_optional("frequency", 400.0f);
}

static void consume_params(KnobSwitch<JitProvider>& comp, ParamReader& param_reader) {
    comp.g_closed = param_reader.consume_float_optional("g_closed", 1000.0f);
    comp.g_open = param_reader.consume_float_optional("g_open", 1e-6f);
    comp.selected = static_cast<int>(param_reader.consume_float_optional("initial_position", 0.0f));
    comp.positions = static_cast<int>(param_reader.consume_float_optional("positions", 2.0f));
}

static void consume_params(LUT<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(LerpNode<JitProvider>& comp, ParamReader& param_reader) {
    comp.deadzone = param_reader.consume_float_optional("deadzone", 0.001f);
    comp.factor = param_reader.consume_float_optional("factor", 0.05f);
}

static void consume_params(Lesser<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(LesserEq<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(Max<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(Merger<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(Min<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(Monostable<JitProvider>& comp, ParamReader& param_reader) {
    comp.duration = param_reader.consume_float_optional("duration", 30.0f);
}

static void consume_params(Multiply<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(NAND<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(NOT<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(Normalize<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(OR<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(P<JitProvider>& comp, ParamReader& param_reader) {
    comp.Kp = param_reader.consume_float_optional("Kp", 1.0f);
    comp.output_max = param_reader.consume_float_optional("output_max", 1000.0f);
    comp.output_min = param_reader.consume_float_optional("output_min", -1000.0f);
}

static void consume_params(PD<JitProvider>& comp, ParamReader& param_reader) {
    comp.Kd = param_reader.consume_float_optional("Kd", 0.0f);
    comp.Kp = param_reader.consume_float_optional("Kp", 1.0f);
    comp.filter_alpha = param_reader.consume_float_optional("filter_alpha", 0.2f);
    comp.output_max = param_reader.consume_float_optional("output_max", 1000.0f);
    comp.output_min = param_reader.consume_float_optional("output_min", -1000.0f);
}

static void consume_params(PI<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(PID<JitProvider>& comp, ParamReader& param_reader) {
    comp.Kd = param_reader.consume_float_optional("Kd", 0.0f);
    comp.Ki = param_reader.consume_float_optional("Ki", 0.0f);
    comp.Kp = param_reader.consume_float_optional("Kp", 1.0f);
    comp.filter_alpha = param_reader.consume_float_optional("filter_alpha", 0.2f);
    comp.output_max = param_reader.consume_float_optional("output_max", 1000.0f);
    comp.output_min = param_reader.consume_float_optional("output_min", -1000.0f);
}

static void consume_params(PneumaticCompressor<JitProvider>& comp, ParamReader& param_reader) {
    comp.internal_r = param_reader.consume_float_optional("internal_r", 0.05f);
    comp.max_pressure = param_reader.consume_float_optional("max_pressure", 700.0f);
    comp.rated_rpm = param_reader.consume_float_optional("rated_rpm", 24000.0f);
}

static void consume_params(PneumaticRef<JitProvider>& comp, ParamReader& param_reader) {
    comp.pressure = param_reader.consume_float_optional("pressure", 0.0f);
}

static void consume_params(PneumaticValve<JitProvider>& comp, ParamReader& param_reader) {
    comp.g_closed = param_reader.consume_float_optional("g_closed", 0.0001f);
    comp.g_open = param_reader.consume_float_optional("g_open", 5.0f);
    comp.normally_closed = param_reader.consume_bool_optional("normally_closed", true);
}

static void consume_params(Positive_V_to_Bool<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(PressureRef<JitProvider>& comp, ParamReader& param_reader) {
    comp.pressure = param_reader.consume_float_optional("pressure", 0.0f);
}

static void consume_params(Radiator<JitProvider>& comp, ParamReader& param_reader) {
    comp.cooling_capacity = param_reader.consume_float_optional("cooling_capacity", 1000.0f);
}

static void consume_params(RefNode<JitProvider>& comp, ParamReader& param_reader) {
    comp.value = param_reader.consume_float_optional("value", 0.0f);
}

static void consume_params(Relay<JitProvider>& comp, ParamReader& param_reader) {
    comp.closed = param_reader.consume_bool_optional("closed", false);
    comp.g_closed = param_reader.consume_float_optional("g_closed", 1000.0f);
    comp.g_open = param_reader.consume_float_optional("g_open", 1e-6f);
}

static void consume_params(Resistor<JitProvider>& comp, ParamReader& param_reader) {
    comp.conductance = param_reader.consume_float_optional("conductance", 0.1f);
}

static void consume_params(RotarySwitch1ToN<JitProvider>& comp, ParamReader& param_reader) {
    comp.g_closed = param_reader.consume_float_optional("g_closed", 1000.0f);
    comp.g_open = param_reader.consume_float_optional("g_open", 1e-6f);
    comp.selected = static_cast<int>(param_reader.consume_float_optional("initial_position", 0.0f));
    comp.positions = static_cast<int>(param_reader.consume_float_optional("positions", 2.0f));
}

static void consume_params(RotarySwitchNTo1<JitProvider>& comp, ParamReader& param_reader) {
    comp.g_closed = param_reader.consume_float_optional("g_closed", 1000.0f);
    comp.g_open = param_reader.consume_float_optional("g_open", 1e-6f);
    comp.selected = static_cast<int>(param_reader.consume_float_optional("initial_position", 0.0f));
    comp.positions = static_cast<int>(param_reader.consume_float_optional("positions", 2.0f));
}

static void consume_params(SampleHold<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(SlewRate<JitProvider>& comp, ParamReader& param_reader) {
    comp.deadzone = param_reader.consume_float_optional("deadzone", 0.0001f);
    comp.max_rate = param_reader.consume_float_optional("max_rate", 1.0f);
}

static void consume_params(Slider<JitProvider>& comp, ParamReader& param_reader) {
    comp.max = param_reader.consume_float_optional("max", 1.0f);
    comp.min = param_reader.consume_float_optional("min", 0.0f);
}

static void consume_params(SolenoidValve<JitProvider>& comp, ParamReader& param_reader) {
    comp.g_closed = param_reader.consume_float_optional("g_closed", 0.0001f);
    comp.g_open = param_reader.consume_float_optional("g_open", 10.0f);
    comp.normally_closed = param_reader.consume_bool_optional("normally_closed", true);
}

static void consume_params(Splitter<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(Spring<JitProvider>& comp, ParamReader& param_reader) {
    comp.c = param_reader.consume_float_optional("c", 10.0f);
    comp.compression_only = param_reader.consume_bool_optional("compression_only", true);
    comp.k = param_reader.consume_float_optional("k", 1000.0f);
    comp.rest_length = param_reader.consume_float_optional("rest_length", 0.1f);
}

static void consume_params(Subtract<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(Switch<JitProvider>& comp, ParamReader& param_reader) {
    comp.closed = param_reader.consume_bool_optional("closed", false);
}

static void consume_params(TempSensor<JitProvider>& comp, ParamReader& param_reader) {
    comp.sensitivity = param_reader.consume_float_optional("sensitivity", 1.0f);
}

static void consume_params(TimeDelay<JitProvider>& comp, ParamReader& param_reader) {
    comp.delay_off = param_reader.consume_float_optional("delay_off", 0.1f);
    comp.delay_on = param_reader.consume_float_optional("delay_on", 0.5f);
}

static void consume_params(Transformer<JitProvider>& comp, ParamReader& param_reader) {
    comp.ratio = param_reader.consume_float_optional("ratio", 1.0f);
}

static void consume_params(Value<JitProvider>& comp, ParamReader& param_reader) {
    comp.value = param_reader.consume_float_optional("value", 0.0f);
}

static void consume_params(VariableConductance<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(VoltageSense<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

static void consume_params(Voltmeter<JitProvider>& comp, ParamReader& param_reader) {
    comp.max = param_reader.consume_float_optional("max", 28.0f);
    comp.min = param_reader.consume_float_optional("min", 0.0f);
}

static void consume_params(XOR<JitProvider>& comp, ParamReader& param_reader) {
    (void)comp; (void)param_reader;  // no params
}

/// Generic builder template: construct → consume_params → build_finish.
/// Handles 69/71 components — only LUT (arena) and RefNode (fixed signals) need custom builders.
template <typename CompType, SchedulerRoleKind Role>
static void build_generic(BuildResult& result, const SolverDevice& dev, ParamReader& param_reader) {
     CompType comp;
     consume_params(comp, param_reader);
     if constexpr (requires { comp.pre_load(); }) { comp.pre_load(); }
     setup_component_ports(result, dev, comp);
     param_reader.validate_all_consumed();
     result.devices[dev.name] = std::move(comp);
     if constexpr (Role == SchedulerRoleKind::Consumer)
         result.scheduler.add_consumer(&std::get<CompType>(result.devices[dev.name]));
     else if constexpr (Role == SchedulerRoleKind::Source)
         result.scheduler.add_source(&std::get<CompType>(result.devices[dev.name]));
 }

/// Special builder: LUT — table arena allocation before pre_load.
static void build_LUT(BuildResult& result, const SolverDevice& dev, ParamReader& param_reader) {
    LUT<JitProvider> comp;
    consume_params(comp, param_reader);
    if (auto it = dev.params.find("table"); it != dev.params.end()) {
        const std::string table_str = param_reader.consume_string_optional("table", "");
        std::vector<float> keys, vals;
        if (LUT<JitProvider>::parse_table(table_str, keys, vals)) {
            comp.table_offset = static_cast<uint32_t>(result.lut_keys.size());
            comp.table_size = static_cast<uint16_t>(keys.size());
            result.lut_keys.insert(result.lut_keys.end(), keys.begin(), keys.end());
            result.lut_values.insert(result.lut_values.end(), vals.begin(), vals.end());
        }
    }
    setup_component_ports(result, dev, comp);
    param_reader.validate_all_consumed();
    result.devices[dev.name] = std::move(comp);
    result.scheduler.add_consumer(&std::get<LUT<JitProvider>>(result.devices[dev.name]));
}

/// Special builder: RefNode — fixed signal registration after scheduler add.
static void build_RefNode(BuildResult& result, const SolverDevice& dev, ParamReader& param_reader) {
    RefNode<JitProvider> comp;
    consume_params(comp, param_reader);
    setup_component_ports(result, dev, comp);
    param_reader.validate_all_consumed();
    result.devices[dev.name] = std::move(comp);
    result.scheduler.add_source(&std::get<RefNode<JitProvider>>(result.devices[dev.name]));
    {
        const std::string key = dev.name + ".v";
        const core::InternedId iid = result.signal_key_interner.lookup(key);
        auto it_sig = result.port_to_signal.find(iid);
        if (it_sig != result.port_to_signal.end()) {
            result.fixed_signals.push_back(it_sig->second);
        }
    }
}

/// Dispatch table — one entry per ComponentKind, indexed by enum value.
using BuildFn = void(*)(BuildResult&, const SolverDevice&, ParamReader&);

/// Sentinel for unsupported ComponentKind values (Unknown).
/// Should never be called — guarded by has_component_metadata() check in the main loop.
[[noreturn]] static void build_unsupported(BuildResult&, const SolverDevice& dev, ParamReader&) {
    throw std::runtime_error("No factory handler for component '" + dev.classname + "'");
}

static const BuildFn BUILD_TABLE[] = {
    build_generic<AND<JitProvider>, SchedulerRoleKind::Consumer>,  // AND
    build_generic<AZS<JitProvider>, SchedulerRoleKind::None>,  // AZS
    build_generic<Accumulator<JitProvider>, SchedulerRoleKind::Consumer>,  // Accumulator
    build_generic<Add<JitProvider>, SchedulerRoleKind::Consumer>,  // Add
    build_generic<Any_V_to_Bool<JitProvider>, SchedulerRoleKind::Consumer>,  // Any_V_to_Bool
    build_generic<AsymSlewRate<JitProvider>, SchedulerRoleKind::Consumer>,  // AsymSlewRate
    build_generic<AsymTMO<JitProvider>, SchedulerRoleKind::Consumer>,  // AsymTMO
    build_generic<Bus<JitProvider>, SchedulerRoleKind::Consumer>,  // Bus
    build_generic<Clamp<JitProvider>, SchedulerRoleKind::Consumer>,  // Clamp
    build_generic<Comparator<JitProvider>, SchedulerRoleKind::Consumer>,  // Comparator
    build_generic<ControlledCurrentSource<JitProvider>, SchedulerRoleKind::Consumer>,  // ControlledCurrentSource
    build_generic<ControlledVoltageSource<JitProvider>, SchedulerRoleKind::None>,  // ControlledVoltageSource
    build_generic<CurrentSense<JitProvider>, SchedulerRoleKind::None>,  // CurrentSense
    build_generic<Divide<JitProvider>, SchedulerRoleKind::Consumer>,  // Divide
    build_generic<ElectricHeater<JitProvider>, SchedulerRoleKind::Consumer>,  // ElectricHeater
    build_generic<ElectricPump<JitProvider>, SchedulerRoleKind::Consumer>,  // ElectricPump
    build_generic<ElectricalConductance<JitProvider>, SchedulerRoleKind::None>,  // ElectricalConductance
    build_generic<ElectricalSource<JitProvider>, SchedulerRoleKind::None>,  // ElectricalSource
    build_generic<FastTMO<JitProvider>, SchedulerRoleKind::Consumer>,  // FastTMO
    build_generic<FuelTank<JitProvider>, SchedulerRoleKind::None>,  // FuelTank
    build_generic<Generator<JitProvider>, SchedulerRoleKind::None>,  // Generator
    build_generic<Greater<JitProvider>, SchedulerRoleKind::Consumer>,  // Greater
    build_generic<GreaterEq<JitProvider>, SchedulerRoleKind::Consumer>,  // GreaterEq
    build_generic<Gyroscope<JitProvider>, SchedulerRoleKind::Consumer>,  // Gyroscope
    build_generic<HoldButton<JitProvider>, SchedulerRoleKind::None>,  // HoldButton
    build_generic<HydraulicAccumulator<JitProvider>, SchedulerRoleKind::Consumer>,  // HydraulicAccumulator
    build_generic<IndicatorLight<JitProvider>, SchedulerRoleKind::None>,  // IndicatorLight
    build_generic<InertiaNode<JitProvider>, SchedulerRoleKind::Consumer>,  // InertiaNode
    build_generic<Integrator<JitProvider>, SchedulerRoleKind::Consumer>,  // Integrator
    build_generic<Inverter<JitProvider>, SchedulerRoleKind::Consumer>,  // Inverter
    build_generic<KnobSwitch<JitProvider>, SchedulerRoleKind::None>,  // KnobSwitch
    build_LUT,  // LUT (special: table arena)
    build_generic<LerpNode<JitProvider>, SchedulerRoleKind::Consumer>,  // LerpNode
    build_generic<Lesser<JitProvider>, SchedulerRoleKind::Consumer>,  // Lesser
    build_generic<LesserEq<JitProvider>, SchedulerRoleKind::Consumer>,  // LesserEq
    build_generic<Max<JitProvider>, SchedulerRoleKind::Consumer>,  // Max
    build_generic<Merger<JitProvider>, SchedulerRoleKind::Consumer>,  // Merger
    build_generic<Min<JitProvider>, SchedulerRoleKind::Consumer>,  // Min
    build_generic<Monostable<JitProvider>, SchedulerRoleKind::Consumer>,  // Monostable
    build_generic<Multiply<JitProvider>, SchedulerRoleKind::Consumer>,  // Multiply
    build_generic<NAND<JitProvider>, SchedulerRoleKind::Consumer>,  // NAND
    build_generic<NOT<JitProvider>, SchedulerRoleKind::Consumer>,  // NOT
    build_generic<Normalize<JitProvider>, SchedulerRoleKind::Consumer>,  // Normalize
    build_generic<OR<JitProvider>, SchedulerRoleKind::Consumer>,  // OR
    build_generic<P<JitProvider>, SchedulerRoleKind::Consumer>,  // P
    build_generic<PD<JitProvider>, SchedulerRoleKind::Consumer>,  // PD
    build_generic<PI<JitProvider>, SchedulerRoleKind::Consumer>,  // PI
    build_generic<PID<JitProvider>, SchedulerRoleKind::Consumer>,  // PID
    build_generic<PneumaticCompressor<JitProvider>, SchedulerRoleKind::None>,  // PneumaticCompressor
    build_generic<PneumaticRef<JitProvider>, SchedulerRoleKind::Source>,  // PneumaticRef
    build_generic<PneumaticValve<JitProvider>, SchedulerRoleKind::None>,  // PneumaticValve
    build_generic<Positive_V_to_Bool<JitProvider>, SchedulerRoleKind::Consumer>,  // Positive_V_to_Bool
    build_generic<PressureRef<JitProvider>, SchedulerRoleKind::Source>,  // PressureRef
    build_generic<Radiator<JitProvider>, SchedulerRoleKind::Consumer>,  // Radiator
    build_RefNode,  // RefNode (special: fixed signals)
    build_generic<Relay<JitProvider>, SchedulerRoleKind::None>,  // Relay
    build_generic<Resistor<JitProvider>, SchedulerRoleKind::None>,  // Resistor
    build_generic<RotarySwitch1ToN<JitProvider>, SchedulerRoleKind::None>,  // RotarySwitch1ToN
    build_generic<RotarySwitchNTo1<JitProvider>, SchedulerRoleKind::None>,  // RotarySwitchNTo1
    build_generic<SampleHold<JitProvider>, SchedulerRoleKind::Consumer>,  // SampleHold
    build_generic<SlewRate<JitProvider>, SchedulerRoleKind::Consumer>,  // SlewRate
    build_generic<Slider<JitProvider>, SchedulerRoleKind::Consumer>,  // Slider
    build_generic<SolenoidValve<JitProvider>, SchedulerRoleKind::None>,  // SolenoidValve
    build_generic<Splitter<JitProvider>, SchedulerRoleKind::Consumer>,  // Splitter
    build_generic<Spring<JitProvider>, SchedulerRoleKind::Consumer>,  // Spring
    build_generic<Subtract<JitProvider>, SchedulerRoleKind::Consumer>,  // Subtract
    build_generic<Switch<JitProvider>, SchedulerRoleKind::Consumer>,  // Switch
    build_generic<TempSensor<JitProvider>, SchedulerRoleKind::Consumer>,  // TempSensor
    build_generic<TimeDelay<JitProvider>, SchedulerRoleKind::Consumer>,  // TimeDelay
    build_generic<Transformer<JitProvider>, SchedulerRoleKind::Consumer>,  // Transformer
    build_generic<Value<JitProvider>, SchedulerRoleKind::Source>,  // Value
    build_generic<VariableConductance<JitProvider>, SchedulerRoleKind::None>,  // VariableConductance
    build_generic<VoltageSense<JitProvider>, SchedulerRoleKind::Consumer>,  // VoltageSense
    build_generic<Voltmeter<JitProvider>, SchedulerRoleKind::Consumer>,  // Voltmeter
    build_generic<XOR<JitProvider>, SchedulerRoleKind::Consumer>,  // XOR
    build_unsupported,  // Unknown (sentinel — guarded by has_component_metadata)
};

static_assert(sizeof(BUILD_TABLE) / sizeof(BUILD_TABLE[0]) == static_cast<size_t>(ComponentKind::_COUNT),
    "BUILD_TABLE size must match ComponentKind count");

void build_and_register_components(
    BuildResult& result,
    const std::vector<SolverDevice>& devices)
{
    result.devices.reserve(devices.size());  // Prevent rehash invalidating scheduler pointers

    std::vector<std::string> consumer_device_names;

    for (const auto& dev : devices) {
        if (!has_component_metadata(dev.kind)) {
            throw std::runtime_error("Missing generated port metadata for component class '" + dev.classname + "'");
        }

        if (dev.scheduler_role_kind == SchedulerRoleKind::Consumer) {
            consumer_device_names.push_back(dev.name);
        }

        ParamReader param_reader(dev.params, dev);

        BUILD_TABLE[static_cast<size_t>(dev.kind)](result, dev, param_reader);
    }

    // Post-registration pass: Deduplicate fixed signals
    std::sort(result.fixed_signals.begin(), result.fixed_signals.end());
    result.fixed_signals.erase(
        std::unique(result.fixed_signals.begin(), result.fixed_signals.end()),
        result.fixed_signals.end());

    // Sentinel is a fixed signal: always allocated at the end, never changes
    result.fixed_signals.push_back(result.signal_count - 1);

    validate_source_writer_conflicts(result, devices);
    validate_consumer_guardrails(result, consumer_device_names, devices);
    topological_sort_consumers(result, consumer_device_names, devices);
}

}  // namespace jit_solver_impl
