// Auto-generated by codegen from library/*.blueprint
// DO NOT EDIT - changes will be overwritten

#include "jit_solver_internal.h"
#include "build_components_common.h"
#include "components/all.h"

#include <algorithm>
#include <spdlog/spdlog.h>

namespace jit_solver_impl {

/// Template helper for KnobSwitch-family components.
/// Generated because multiple ComponentKinds share identical params.
template <typename CompType>
static void build_knob_switch_impl(
    BuildResult& result, const ResolvedDevice& dev, ParamReader& param_reader)
{
    CompType comp;
    comp.g_closed = param_reader.consume_float_optional("g_closed", 1000.0f);
    comp.g_open = param_reader.consume_float_optional("g_open", 1e-6f);
    comp.selected = static_cast<int>(param_reader.consume_float_optional("initial_position", 0.0f));
    comp.positions = static_cast<int>(param_reader.consume_float_optional("positions", 2.0f));
    comp.pre_load();
    setup_component_ports(result, dev, comp);
    param_reader.validate_all_consumed();
    result.devices[dev.name] = std::move(comp);
}

void build_and_register_components(
    BuildResult& result,
    const std::vector<ResolvedDevice>& devices)
{
    std::vector<std::string> consumer_device_names;

    for (const auto& dev : devices) {
        if (!has_component_metadata(dev.kind)) {
            throw std::runtime_error("Missing generated port metadata for component class '" + dev.classname + "'");
        }

        const bool is_source = dev.scheduler_source;
        const bool is_solver_owned = dev.solver_owned_electrical;

        if (!is_source && !is_solver_owned) {
            consumer_device_names.push_back(dev.name);
        }

        ParamReader param_reader(dev.params, dev);

        switch (dev.kind) {
        case ComponentKind::AND: {
            AND<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<AND<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::AZS: {
            AZS<JitProvider> comp;
            comp.closed = param_reader.consume_bool_optional("closed", false);
            comp.g_closed = param_reader.consume_float_optional("g_closed", 1000.0f);
            comp.g_open = param_reader.consume_float_optional("g_open", 1e-6f);
            comp.i_nominal = param_reader.consume_float_optional("i_nominal", 20.0f);
            comp.k_cool = param_reader.consume_float_optional("k_cool", 1.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            break;
        }
        case ComponentKind::Accumulator: {
            Accumulator<JitProvider> comp;
            comp.initial_val = param_reader.consume_float_optional("initial_val", 0.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Accumulator<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Add: {
            Add<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Add<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Any_V_to_Bool: {
            Any_V_to_Bool<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Any_V_to_Bool<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::AsymSlewRate: {
            AsymSlewRate<JitProvider> comp;
            comp.deadzone = param_reader.consume_float_optional("deadzone", 0.0001f);
            comp.rate_down = param_reader.consume_float_optional("rate_down", 0.5f);
            comp.rate_up = param_reader.consume_float_optional("rate_up", 1.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<AsymSlewRate<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::AsymTMO: {
            AsymTMO<JitProvider> comp;
            comp.deadzone = param_reader.consume_float_optional("deadzone", 0.001f);
            comp.tau_down = param_reader.consume_float_optional("tau_down", 0.5f);
            comp.tau_up = param_reader.consume_float_optional("tau_up", 0.1f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<AsymTMO<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Bus: {
            Bus<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Bus<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Clamp: {
            Clamp<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Clamp<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Comparator: {
            Comparator<JitProvider> comp;
            comp.Voff = param_reader.consume_float_optional("Voff", 2.0f);
            comp.Von = param_reader.consume_float_optional("Von", 5.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Comparator<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::ControlledCurrentSource: {
            ControlledCurrentSource<JitProvider> comp;
            comp.g_shunt = param_reader.consume_float_optional("g_shunt", 0.001f);
            comp.gain = param_reader.consume_float_optional("gain", 1.0f);
            comp.max_i = param_reader.consume_float_optional("max_i", 100.0f);
            comp.min_i = param_reader.consume_float_optional("min_i", 0.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<ControlledCurrentSource<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::ControlledVoltageSource: {
            ControlledVoltageSource<JitProvider> comp;
            comp.r_internal = param_reader.consume_float_optional("r_internal", 0.1f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            break;
        }
        case ComponentKind::CurrentSense: {
            CurrentSense<JitProvider> comp;
            comp.conductance = param_reader.consume_float_optional("conductance", 0.05f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<CurrentSense<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Divide: {
            Divide<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Divide<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::ElectricHeater: {
            ElectricHeater<JitProvider> comp;
            comp.efficiency = param_reader.consume_float_optional("efficiency", 0.9f);
            comp.max_power = param_reader.consume_float_optional("max_power", 1000.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<ElectricHeater<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::ElectricPump: {
            ElectricPump<JitProvider> comp;
            comp.max_pressure = param_reader.consume_float_optional("max_pressure", 1000.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<ElectricPump<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::ElectricalConductance: {
            ElectricalConductance<JitProvider> comp;
            comp.conductance = param_reader.consume_float_optional("conductance", 0.1f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            break;
        }
        case ComponentKind::ElectricalSource: {
            ElectricalSource<JitProvider> comp;
            comp.resistance = param_reader.consume_float_optional("resistance", 0.01f);
            comp.voltage = param_reader.consume_float_optional("voltage", 28.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            break;
        }
        case ComponentKind::FastTMO: {
            FastTMO<JitProvider> comp;
            comp.deadzone = param_reader.consume_float_optional("deadzone", 0.001f);
            comp.tau = param_reader.consume_float_optional("tau", 0.1f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<FastTMO<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::FuelTank: {
            FuelTank<JitProvider> comp;
            comp.capacity = param_reader.consume_float_optional("capacity", 1000.0f);
            comp.consumption_rate = param_reader.consume_float_optional("consumption_rate", 0.0f);
            comp.density = param_reader.consume_float_optional("density", 0.78f);
            comp.level = param_reader.consume_float_optional("level", 1000.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<FuelTank<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Generator: {
            Generator<JitProvider> comp;
            comp.internal_r = param_reader.consume_float_optional("internal_r", 0.005f);
            comp.v_nominal = param_reader.consume_float_optional("v_nominal", 28.5f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            break;
        }
        case ComponentKind::GidroAccumulator: {
            GidroAccumulator<JitProvider> comp;
            comp.precharge_pressure = param_reader.consume_float_optional("precharge_pressure", 50.0f);
            comp.volume = param_reader.consume_float_optional("volume", 10.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<GidroAccumulator<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Greater: {
            Greater<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Greater<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::GreaterEq: {
            GreaterEq<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<GreaterEq<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Gyroscope: {
            Gyroscope<JitProvider> comp;
            comp.conductance = param_reader.consume_float_optional("conductance", 0.035f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Gyroscope<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::HoldButton: {
            HoldButton<JitProvider> comp;
            comp.g_closed = param_reader.consume_float_optional("g_closed", 1000.0f);
            comp.g_open = param_reader.consume_float_optional("g_open", 1e-6f);
            comp.idle = param_reader.consume_float_optional("idle", 0.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            break;
        }
        case ComponentKind::IndicatorLight: {
            IndicatorLight<JitProvider> comp;
            comp.conductance = param_reader.consume_float_optional("conductance", 0.002f);
            comp.rated_voltage = param_reader.consume_float_optional("rated_voltage", 28.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<IndicatorLight<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::InertiaNode: {
            InertiaNode<JitProvider> comp;
            comp.initial_rpm = param_reader.consume_float_optional("initial_rpm", 1.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<InertiaNode<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Integrator: {
            Integrator<JitProvider> comp;
            comp.initial_val = param_reader.consume_float_optional("initial_val", 0.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Integrator<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Inverter: {
            Inverter<JitProvider> comp;
            comp.efficiency = param_reader.consume_float_optional("efficiency", 0.95f);
            comp.frequency = param_reader.consume_float_optional("frequency", 400.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Inverter<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::KnobSwitch:
            build_knob_switch_impl<KnobSwitch<JitProvider>>(result, dev, param_reader);
            break;
        case ComponentKind::LUT: {
            LUT<JitProvider> comp;
            if (auto it = dev.params.find("table"); it != dev.params.end()) {
                const std::string table_str = param_reader.consume_string_optional("table", "");
                std::vector<float> keys, vals;
                if (LUT<JitProvider>::parse_table(table_str, keys, vals)) {
                    comp.table_offset = static_cast<uint32_t>(result.lut_keys.size());
                    comp.table_size = static_cast<uint16_t>(keys.size());
                    result.lut_keys.insert(result.lut_keys.end(), keys.begin(), keys.end());
                    result.lut_values.insert(result.lut_values.end(), vals.begin(), vals.end());
                }
            }
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<LUT<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::LerpNode: {
            LerpNode<JitProvider> comp;
            comp.deadzone = param_reader.consume_float_optional("deadzone", 0.001f);
            comp.factor = param_reader.consume_float_optional("factor", 0.05f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<LerpNode<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Lesser: {
            Lesser<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Lesser<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::LesserEq: {
            LesserEq<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<LesserEq<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Max: {
            Max<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Max<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Merger: {
            Merger<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Merger<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Min: {
            Min<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Min<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Monostable: {
            Monostable<JitProvider> comp;
            comp.duration = param_reader.consume_float_optional("duration", 30.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Monostable<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Multiply: {
            Multiply<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Multiply<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::NAND: {
            NAND<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<NAND<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::NOT: {
            NOT<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<NOT<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Normalize: {
            Normalize<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Normalize<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::OR: {
            OR<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<OR<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::P: {
            P<JitProvider> comp;
            comp.Kp = param_reader.consume_float_optional("Kp", 1.0f);
            comp.output_max = param_reader.consume_float_optional("output_max", 1000.0f);
            comp.output_min = param_reader.consume_float_optional("output_min", -1000.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<P<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::PD: {
            PD<JitProvider> comp;
            comp.Kd = param_reader.consume_float_optional("Kd", 0.0f);
            comp.Kp = param_reader.consume_float_optional("Kp", 1.0f);
            comp.filter_alpha = param_reader.consume_float_optional("filter_alpha", 0.2f);
            comp.output_max = param_reader.consume_float_optional("output_max", 1000.0f);
            comp.output_min = param_reader.consume_float_optional("output_min", -1000.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<PD<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::PI: {
            PI<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<PI<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::PID: {
            PID<JitProvider> comp;
            comp.Kd = param_reader.consume_float_optional("Kd", 0.0f);
            comp.Ki = param_reader.consume_float_optional("Ki", 0.0f);
            comp.Kp = param_reader.consume_float_optional("Kp", 1.0f);
            comp.filter_alpha = param_reader.consume_float_optional("filter_alpha", 0.2f);
            comp.output_max = param_reader.consume_float_optional("output_max", 1000.0f);
            comp.output_min = param_reader.consume_float_optional("output_min", -1000.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<PID<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Positive_V_to_Bool: {
            Positive_V_to_Bool<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Positive_V_to_Bool<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Radiator: {
            Radiator<JitProvider> comp;
            comp.cooling_capacity = param_reader.consume_float_optional("cooling_capacity", 1000.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Radiator<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::RefNode: {
            RefNode<JitProvider> comp;
            comp.value = param_reader.consume_float_optional("value", 0.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_source(&std::get<RefNode<JitProvider>>(result.devices[dev.name]));
            {
                const std::string key = dev.name + ".v";
                const ui::InternedId iid = result.signal_key_interner.lookup(key);
                auto it_sig = result.port_to_signal.find(iid);
                if (it_sig != result.port_to_signal.end()) {
                    result.fixed_signals.push_back(it_sig->second);
                }
            }
            break;
        }
        case ComponentKind::Relay: {
            Relay<JitProvider> comp;
            comp.closed = param_reader.consume_bool_optional("closed", false);
            comp.g_closed = param_reader.consume_float_optional("g_closed", 1000.0f);
            comp.g_open = param_reader.consume_float_optional("g_open", 1e-6f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            break;
        }
        case ComponentKind::Resistor: {
            Resistor<JitProvider> comp;
            comp.conductance = param_reader.consume_float_optional("conductance", 0.1f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            break;
        }
        case ComponentKind::RotarySwitch1ToN:
            build_knob_switch_impl<RotarySwitch1ToN<JitProvider>>(result, dev, param_reader);
            break;
        case ComponentKind::RotarySwitchNTo1:
            build_knob_switch_impl<RotarySwitchNTo1<JitProvider>>(result, dev, param_reader);
            break;
        case ComponentKind::SampleHold: {
            SampleHold<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<SampleHold<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::SlewRate: {
            SlewRate<JitProvider> comp;
            comp.deadzone = param_reader.consume_float_optional("deadzone", 0.0001f);
            comp.max_rate = param_reader.consume_float_optional("max_rate", 1.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<SlewRate<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Slider: {
            Slider<JitProvider> comp;
            comp.max = param_reader.consume_float_optional("max", 1.0f);
            comp.min = param_reader.consume_float_optional("min", 0.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Slider<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::SolenoidValve: {
            SolenoidValve<JitProvider> comp;
            comp.normally_closed = param_reader.consume_bool_optional("normally_closed", true);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<SolenoidValve<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Splitter: {
            Splitter<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Splitter<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Spring: {
            Spring<JitProvider> comp;
            comp.c = param_reader.consume_float_optional("c", 10.0f);
            comp.compression_only = param_reader.consume_bool_optional("compression_only", true);
            comp.k = param_reader.consume_float_optional("k", 1000.0f);
            comp.rest_length = param_reader.consume_float_optional("rest_length", 0.1f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Spring<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Subtract: {
            Subtract<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Subtract<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Switch: {
            Switch<JitProvider> comp;
            comp.closed = param_reader.consume_bool_optional("closed", false);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Switch<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::TempSensor: {
            TempSensor<JitProvider> comp;
            comp.sensitivity = param_reader.consume_float_optional("sensitivity", 1.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<TempSensor<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::TimeDelay: {
            TimeDelay<JitProvider> comp;
            comp.delay_off = param_reader.consume_float_optional("delay_off", 0.1f);
            comp.delay_on = param_reader.consume_float_optional("delay_on", 0.5f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<TimeDelay<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Transformer: {
            Transformer<JitProvider> comp;
            comp.ratio = param_reader.consume_float_optional("ratio", 1.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Transformer<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Value: {
            Value<JitProvider> comp;
            comp.value = param_reader.consume_float_optional("value", 0.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_source(&std::get<Value<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::VariableConductance: {
            VariableConductance<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            break;
        }
        case ComponentKind::VoltageSense: {
            VoltageSense<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<VoltageSense<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::Voltmeter: {
            Voltmeter<JitProvider> comp;
            comp.max = param_reader.consume_float_optional("max", 28.0f);
            comp.min = param_reader.consume_float_optional("min", 0.0f);
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<Voltmeter<JitProvider>>(result.devices[dev.name]));
            break;
        }
        case ComponentKind::XOR: {
            XOR<JitProvider> comp;
            comp.pre_load();
            setup_component_ports(result, dev, comp);
            param_reader.validate_all_consumed();
            result.devices[dev.name] = std::move(comp);
            result.scheduler.add_consumer(&std::get<XOR<JitProvider>>(result.devices[dev.name]));
            break;
        }
        default:
            throw std::runtime_error("Unknown component class '" + std::string(dev.classname)
                + "' for device '" + dev.name + "'. No factory handler registered.");
        }
    }

    // Post-registration pass: Deduplicate fixed signals
    std::sort(result.fixed_signals.begin(), result.fixed_signals.end());
    result.fixed_signals.erase(
        std::unique(result.fixed_signals.begin(), result.fixed_signals.end()),
        result.fixed_signals.end());

    // Sentinel is a fixed signal: always allocated at the end, never changes
    result.fixed_signals.push_back(result.signal_count - 1);

    validate_source_writer_conflicts(result, devices);
    validate_consumer_guardrails(result, consumer_device_names, devices);
    topological_sort_consumers(result, consumer_device_names, devices);
}

}  // namespace jit_solver_impl
