#pragma once

#include "jit_solver.h"
#include <string>
#include <string_view>
#include <vector>
#include <unordered_map>
#include <unordered_set>

// Internal implementation details - not exposed to external users
namespace jit_solver_impl {

/// Helper functions and utilities for build_systems_dev
std::vector<std::string> active_source_writer_ports_for(ComponentKind kind);
std::unordered_set<std::string> output_ports_for_class(ComponentKind kind);
bool parse_bool_param_value(const std::string& value);

/// ParamReader class for parameter parsing
class ParamReader {
public:
    ParamReader(const std::unordered_map<std::string, std::string>& params, const SolverDevice& dev)
        : params_(params), dev_(dev) {}

    float consume_float_optional(const std::string& key, float default_val);
    bool consume_bool_optional(const std::string& key, bool default_val);
    std::string consume_string_optional(const std::string& key, const std::string& default_val);
    float consume_float_required(const std::string& key);
    bool consume_bool_required(const std::string& key);
    void validate_all_consumed() const;

private:
    const std::string& get_required(const std::string& key) const;
    const std::unordered_map<std::string, std::string>& params_;
    const SolverDevice& dev_;
    std::unordered_set<std::string> consumed_params_;
};

/// Component factory — generated by codegen from library/*.blueprint
void build_and_register_components(
    BuildResult& result,
    const std::vector<SolverDevice>& devices);

void validate_source_writer_conflicts(
    const BuildResult& result,
    const std::vector<SolverDevice>& devices);

void validate_consumer_guardrails(
    const BuildResult& result,
    const std::vector<std::string>& consumer_device_names,
    const std::vector<SolverDevice>& devices);

void topological_sort_consumers(
    BuildResult& result,
    std::vector<std::string>& consumer_device_names,
    const std::vector<SolverDevice>& devices);

/// Electrical building functions
void build_electrical_islands(
    BuildResult& result,
    const std::vector<SolverDevice>& devices);

void build_electrical_patch_ops(BuildResult& result);

void build_solver_step_ops(BuildResult& result);

/// Hydraulic building functions
void build_hydraulic_islands(
    BuildResult& result,
    const std::vector<SolverDevice>& devices);

void build_hydraulic_patch_ops(BuildResult& result);

void build_hydraulic_step_ops(BuildResult& result);

/// Type-erased component adapters — shared by electrical and hydraulic build.
template <typename Comp>
void execute_component_adapter(void* instance, SimulationState& st, double dt) {
    static_cast<Comp*>(instance)->execute(st, dt);
}

template <typename Comp>
void commit_component_adapter(void* instance, SimulationState& st, double dt) {
    static_cast<Comp*>(instance)->commit(st, dt);
}

}  // namespace jit_solver_impl
