// Auto-generated by codegen from library/*.blueprint
// DO NOT EDIT - changes will be overwritten

#pragma once

#include <cstddef>
#include <cstdint>

#include "core/solvers/common/port_names.h"
#include "blueprint_v2/interface/direction.h"

constexpr size_t AND_PORT_COUNT = 3;
constexpr size_t AZS_PORT_COUNT = 6;
constexpr size_t Accumulator_PORT_COUNT = 2;
constexpr size_t Add_PORT_COUNT = 3;
constexpr size_t Any_V_to_Bool_PORT_COUNT = 2;
constexpr size_t AsymSlewRate_PORT_COUNT = 2;
constexpr size_t AsymTMO_PORT_COUNT = 2;
constexpr size_t Bus_PORT_COUNT = 1;
constexpr size_t Clamp_PORT_COUNT = 4;
constexpr size_t Comparator_PORT_COUNT = 3;
constexpr size_t ControlledCurrentSource_PORT_COUNT = 3;
constexpr size_t ControlledVoltageSource_PORT_COUNT = 8;
constexpr size_t CurrentSense_PORT_COUNT = 3;
constexpr size_t Divide_PORT_COUNT = 3;
constexpr size_t ElectricHeater_PORT_COUNT = 2;
constexpr size_t ElectricPump_PORT_COUNT = 3;
constexpr size_t ElectricalConductance_PORT_COUNT = 2;
constexpr size_t ElectricalSource_PORT_COUNT = 2;
constexpr size_t FastTMO_PORT_COUNT = 2;
constexpr size_t FuelTank_PORT_COUNT = 2;
constexpr size_t Generator_PORT_COUNT = 2;
constexpr size_t GidroAccumulator_PORT_COUNT = 2;
constexpr size_t Greater_PORT_COUNT = 3;
constexpr size_t GreaterEq_PORT_COUNT = 3;
constexpr size_t Gyroscope_PORT_COUNT = 1;
constexpr size_t HoldButton_PORT_COUNT = 4;
constexpr size_t IndicatorLight_PORT_COUNT = 3;
constexpr size_t InertiaNode_PORT_COUNT = 5;
constexpr size_t Integrator_PORT_COUNT = 4;
constexpr size_t Inverter_PORT_COUNT = 2;
constexpr size_t KnobSwitch_PORT_COUNT = 8;
constexpr size_t LUT_PORT_COUNT = 2;
constexpr size_t LerpNode_PORT_COUNT = 2;
constexpr size_t Lesser_PORT_COUNT = 3;
constexpr size_t LesserEq_PORT_COUNT = 3;
constexpr size_t Max_PORT_COUNT = 3;
constexpr size_t Merger_PORT_COUNT = 3;
constexpr size_t Min_PORT_COUNT = 3;
constexpr size_t Monostable_PORT_COUNT = 2;
constexpr size_t Multiply_PORT_COUNT = 3;
constexpr size_t NAND_PORT_COUNT = 3;
constexpr size_t NOT_PORT_COUNT = 2;
constexpr size_t Normalize_PORT_COUNT = 4;
constexpr size_t OR_PORT_COUNT = 3;
constexpr size_t P_PORT_COUNT = 3;
constexpr size_t PD_PORT_COUNT = 3;
constexpr size_t PI_PORT_COUNT = 7;
constexpr size_t PID_PORT_COUNT = 3;
constexpr size_t Positive_V_to_Bool_PORT_COUNT = 2;
constexpr size_t Radiator_PORT_COUNT = 2;
constexpr size_t RefNode_PORT_COUNT = 1;
constexpr size_t Relay_PORT_COUNT = 5;
constexpr size_t Resistor_PORT_COUNT = 2;
constexpr size_t RotarySwitch1ToN_PORT_COUNT = 8;
constexpr size_t RotarySwitchNTo1_PORT_COUNT = 8;
constexpr size_t SampleHold_PORT_COUNT = 3;
constexpr size_t SlewRate_PORT_COUNT = 2;
constexpr size_t Slider_PORT_COUNT = 2;
constexpr size_t SolenoidValve_PORT_COUNT = 3;
constexpr size_t Splitter_PORT_COUNT = 3;
constexpr size_t Spring_PORT_COUNT = 3;
constexpr size_t Subtract_PORT_COUNT = 3;
constexpr size_t Switch_PORT_COUNT = 4;
constexpr size_t TempSensor_PORT_COUNT = 2;
constexpr size_t TimeDelay_PORT_COUNT = 2;
constexpr size_t Transformer_PORT_COUNT = 2;
constexpr size_t Value_PORT_COUNT = 1;
constexpr size_t VariableConductance_PORT_COUNT = 5;
constexpr size_t VoltageSense_PORT_COUNT = 5;
constexpr size_t Voltmeter_PORT_COUNT = 1;
constexpr size_t XOR_PORT_COUNT = 3;

constexpr const char* AND_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* AZS_PORTS[] = {
    "control",
    "state",
    "temp",
    "tripped",
    "v_in",
    "v_out"
};
constexpr const char* Accumulator_PORTS[] = {
    "in",
    "out"
};
constexpr const char* Add_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* Any_V_to_Bool_PORTS[] = {
    "Vin",
    "o"
};
constexpr const char* AsymSlewRate_PORTS[] = {
    "in",
    "out"
};
constexpr const char* AsymTMO_PORTS[] = {
    "in",
    "out"
};
constexpr const char* Bus_PORTS[] = {
    "v"
};
constexpr const char* Clamp_PORTS[] = {
    "in",
    "max",
    "min",
    "out"
};
constexpr const char* Comparator_PORTS[] = {
    "Va",
    "Vb",
    "o"
};
constexpr const char* ControlledCurrentSource_PORTS[] = {
    "cmd",
    "v_neg",
    "v_pos"
};
constexpr const char* ControlledVoltageSource_PORTS[] = {
    "cmd",
    "gain",
    "i_out",
    "max_v",
    "min_v",
    "offset",
    "v_neg",
    "v_pos"
};
constexpr const char* CurrentSense_PORTS[] = {
    "i_out",
    "v_in",
    "v_out"
};
constexpr const char* Divide_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* ElectricHeater_PORTS[] = {
    "heat_out",
    "power"
};
constexpr const char* ElectricPump_PORTS[] = {
    "p_in",
    "p_out",
    "v_in"
};
constexpr const char* ElectricalConductance_PORTS[] = {
    "v_in",
    "v_out"
};
constexpr const char* ElectricalSource_PORTS[] = {
    "v_in",
    "v_out"
};
constexpr const char* FastTMO_PORTS[] = {
    "in",
    "out"
};
constexpr const char* FuelTank_PORTS[] = {
    "flow_out",
    "level_out"
};
constexpr const char* Generator_PORTS[] = {
    "v_in",
    "v_out"
};
constexpr const char* GidroAccumulator_PORTS[] = {
    "p_in",
    "p_out"
};
constexpr const char* Greater_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* GreaterEq_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* Gyroscope_PORTS[] = {
    "input"
};
constexpr const char* HoldButton_PORTS[] = {
    "control",
    "state",
    "v_in",
    "v_out"
};
constexpr const char* IndicatorLight_PORTS[] = {
    "brightness",
    "v_in",
    "v_out"
};
constexpr const char* InertiaNode_PORTS[] = {
    "damping",
    "inv_inertia",
    "mass",
    "rpm_out",
    "torque_in"
};
constexpr const char* Integrator_PORTS[] = {
    "gain",
    "in",
    "out",
    "reset"
};
constexpr const char* Inverter_PORTS[] = {
    "ac_out",
    "dc_in"
};
constexpr const char* KnobSwitch_PORTS[] = {
    "control",
    "position",
    "throw1",
    "throw2",
    "throw3",
    "throw4",
    "throw5",
    "wiper"
};
constexpr const char* LUT_PORTS[] = {
    "input",
    "output"
};
constexpr const char* LerpNode_PORTS[] = {
    "input",
    "output"
};
constexpr const char* Lesser_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* LesserEq_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* Max_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* Merger_PORTS[] = {
    "i1",
    "i2",
    "o"
};
constexpr const char* Min_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* Monostable_PORTS[] = {
    "in",
    "out"
};
constexpr const char* Multiply_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* NAND_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* NOT_PORTS[] = {
    "A",
    "o"
};
constexpr const char* Normalize_PORTS[] = {
    "in",
    "max",
    "min",
    "out"
};
constexpr const char* OR_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* P_PORTS[] = {
    "feedback",
    "output",
    "setpoint"
};
constexpr const char* PD_PORTS[] = {
    "feedback",
    "output",
    "setpoint"
};
constexpr const char* PI_PORTS[] = {
    "Ki",
    "Kp",
    "feedback",
    "output",
    "output_max",
    "output_min",
    "setpoint"
};
constexpr const char* PID_PORTS[] = {
    "feedback",
    "output",
    "setpoint"
};
constexpr const char* Positive_V_to_Bool_PORTS[] = {
    "Vin",
    "o"
};
constexpr const char* Radiator_PORTS[] = {
    "heat_in",
    "heat_out"
};
constexpr const char* RefNode_PORTS[] = {
    "v"
};
constexpr const char* Relay_PORTS[] = {
    "control",
    "hold_threshold",
    "state",
    "v_in",
    "v_out"
};
constexpr const char* Resistor_PORTS[] = {
    "v_in",
    "v_out"
};
constexpr const char* RotarySwitch1ToN_PORTS[] = {
    "control",
    "position",
    "throw1",
    "throw2",
    "throw3",
    "throw4",
    "throw5",
    "wiper"
};
constexpr const char* RotarySwitchNTo1_PORTS[] = {
    "control",
    "position",
    "throw1",
    "throw2",
    "throw3",
    "throw4",
    "throw5",
    "wiper"
};
constexpr const char* SampleHold_PORTS[] = {
    "in",
    "out",
    "trigger"
};
constexpr const char* SlewRate_PORTS[] = {
    "in",
    "out"
};
constexpr const char* Slider_PORTS[] = {
    "control",
    "out"
};
constexpr const char* SolenoidValve_PORTS[] = {
    "ctrl",
    "flow_in",
    "flow_out"
};
constexpr const char* Splitter_PORTS[] = {
    "i",
    "o1",
    "o2"
};
constexpr const char* Spring_PORTS[] = {
    "force_out",
    "pos_a",
    "pos_b"
};
constexpr const char* Subtract_PORTS[] = {
    "A",
    "B",
    "o"
};
constexpr const char* Switch_PORTS[] = {
    "control",
    "state",
    "v_in",
    "v_out"
};
constexpr const char* TempSensor_PORTS[] = {
    "temp_in",
    "temp_out"
};
constexpr const char* TimeDelay_PORTS[] = {
    "in",
    "out"
};
constexpr const char* Transformer_PORTS[] = {
    "primary",
    "secondary"
};
constexpr const char* Value_PORTS[] = {
    "o"
};
constexpr const char* VariableConductance_PORTS[] = {
    "cmd",
    "g_max",
    "g_min",
    "v_in",
    "v_out"
};
constexpr const char* VoltageSense_PORTS[] = {
    "gain",
    "offset",
    "out",
    "v_in",
    "v_ref"
};
constexpr const char* Voltmeter_PORTS[] = {
    "v_in"
};
constexpr const char* XOR_PORTS[] = {
    "A",
    "B",
    "o"
};

constexpr bp2::Direction AND_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t AND_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool AND_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction AZS_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Output,
    bp2::Direction::Output,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t AZS_PORT_DOMAINS[] = {
    16,
    2,
    16,
    2,
    1,
    1
};
constexpr bool AZS_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false,
    false,
    false
};
constexpr bp2::Direction Accumulator_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Accumulator_PORT_DOMAINS[] = {
    2,
    2
};
constexpr bool Accumulator_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction Add_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Add_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool Add_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction Any_V_to_Bool_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Any_V_to_Bool_PORT_DOMAINS[] = {
    1,
    2
};
constexpr bool Any_V_to_Bool_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction AsymSlewRate_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t AsymSlewRate_PORT_DOMAINS[] = {
    2,
    2
};
constexpr bool AsymSlewRate_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction AsymTMO_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t AsymTMO_PORT_DOMAINS[] = {
    2,
    2
};
constexpr bool AsymTMO_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction Bus_PORT_DIRECTIONS[] = {
    bp2::Direction::InOut
};
constexpr uint8_t Bus_PORT_DOMAINS[] = {
    1
};
constexpr bool Bus_PORT_SOURCE_WRITER[] = {
    false
};
constexpr bp2::Direction Clamp_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Clamp_PORT_DOMAINS[] = {
    2,
    2,
    2,
    2
};
constexpr bool Clamp_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false
};
constexpr bp2::Direction Comparator_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Comparator_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool Comparator_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction ControlledCurrentSource_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Output
};
constexpr uint8_t ControlledCurrentSource_PORT_DOMAINS[] = {
    2,
    1,
    1
};
constexpr bool ControlledCurrentSource_PORT_SOURCE_WRITER[] = {
    false,
    false,
    true
};
constexpr bp2::Direction ControlledVoltageSource_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t ControlledVoltageSource_PORT_DOMAINS[] = {
    2,
    2,
    1,
    2,
    2,
    2,
    1,
    1
};
constexpr bool ControlledVoltageSource_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true
};
constexpr bp2::Direction CurrentSense_PORT_DIRECTIONS[] = {
    bp2::Direction::Output,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t CurrentSense_PORT_DOMAINS[] = {
    1,
    1,
    1
};
constexpr bool CurrentSense_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction Divide_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Divide_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool Divide_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction ElectricHeater_PORT_DIRECTIONS[] = {
    bp2::Direction::Output,
    bp2::Direction::Input
};
constexpr uint8_t ElectricHeater_PORT_DOMAINS[] = {
    16,
    1
};
constexpr bool ElectricHeater_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction ElectricPump_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input
};
constexpr uint8_t ElectricPump_PORT_DOMAINS[] = {
    8,
    8,
    1
};
constexpr bool ElectricPump_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction ElectricalConductance_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t ElectricalConductance_PORT_DOMAINS[] = {
    1,
    1
};
constexpr bool ElectricalConductance_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction ElectricalSource_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t ElectricalSource_PORT_DOMAINS[] = {
    1,
    1
};
constexpr bool ElectricalSource_PORT_SOURCE_WRITER[] = {
    false,
    true
};
constexpr bp2::Direction FastTMO_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t FastTMO_PORT_DOMAINS[] = {
    2,
    2
};
constexpr bool FastTMO_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction FuelTank_PORT_DIRECTIONS[] = {
    bp2::Direction::Output,
    bp2::Direction::Output
};
constexpr uint8_t FuelTank_PORT_DOMAINS[] = {
    8,
    2
};
constexpr bool FuelTank_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction Generator_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Generator_PORT_DOMAINS[] = {
    1,
    1
};
constexpr bool Generator_PORT_SOURCE_WRITER[] = {
    false,
    true
};
constexpr bp2::Direction GidroAccumulator_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t GidroAccumulator_PORT_DOMAINS[] = {
    8,
    8
};
constexpr bool GidroAccumulator_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction Greater_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Greater_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool Greater_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction GreaterEq_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t GreaterEq_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool GreaterEq_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction Gyroscope_PORT_DIRECTIONS[] = {
    bp2::Direction::Input
};
constexpr uint8_t Gyroscope_PORT_DOMAINS[] = {
    1
};
constexpr bool Gyroscope_PORT_SOURCE_WRITER[] = {
    false
};
constexpr bp2::Direction HoldButton_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t HoldButton_PORT_DOMAINS[] = {
    16,
    2,
    1,
    1
};
constexpr bool HoldButton_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false
};
constexpr bp2::Direction IndicatorLight_PORT_DIRECTIONS[] = {
    bp2::Direction::Output,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t IndicatorLight_PORT_DOMAINS[] = {
    1,
    1,
    1
};
constexpr bool IndicatorLight_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction InertiaNode_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input
};
constexpr uint8_t InertiaNode_PORT_DOMAINS[] = {
    2,
    2,
    2,
    4,
    2
};
constexpr bool InertiaNode_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false,
    false
};
constexpr bp2::Direction Integrator_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input
};
constexpr uint8_t Integrator_PORT_DOMAINS[] = {
    2,
    2,
    2,
    2
};
constexpr bool Integrator_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false
};
constexpr bp2::Direction Inverter_PORT_DIRECTIONS[] = {
    bp2::Direction::Output,
    bp2::Direction::Input
};
constexpr uint8_t Inverter_PORT_DOMAINS[] = {
    16,
    1
};
constexpr bool Inverter_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction KnobSwitch_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::InOut,
    bp2::Direction::InOut,
    bp2::Direction::InOut,
    bp2::Direction::InOut,
    bp2::Direction::InOut,
    bp2::Direction::InOut
};
constexpr uint8_t KnobSwitch_PORT_DOMAINS[] = {
    2,
    2,
    1,
    1,
    1,
    1,
    1,
    1
};
constexpr bool KnobSwitch_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false
};
constexpr bp2::Direction LUT_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t LUT_PORT_DOMAINS[] = {
    2,
    2
};
constexpr bool LUT_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction LerpNode_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t LerpNode_PORT_DOMAINS[] = {
    2,
    2
};
constexpr bool LerpNode_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction Lesser_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Lesser_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool Lesser_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction LesserEq_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t LesserEq_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool LesserEq_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction Max_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Max_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool Max_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction Merger_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Merger_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool Merger_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction Min_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Min_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool Min_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction Monostable_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Monostable_PORT_DOMAINS[] = {
    2,
    2
};
constexpr bool Monostable_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction Multiply_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Multiply_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool Multiply_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction NAND_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t NAND_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool NAND_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction NOT_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t NOT_PORT_DOMAINS[] = {
    2,
    2
};
constexpr bool NOT_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction Normalize_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Normalize_PORT_DOMAINS[] = {
    2,
    2,
    2,
    2
};
constexpr bool Normalize_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false
};
constexpr bp2::Direction OR_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t OR_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool OR_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction P_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input
};
constexpr uint8_t P_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool P_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction PD_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input
};
constexpr uint8_t PD_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool PD_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction PI_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Input
};
constexpr uint8_t PI_PORT_DOMAINS[] = {
    2,
    2,
    2,
    2,
    2,
    2,
    2
};
constexpr bool PI_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false,
    false,
    false,
    false
};
constexpr bp2::Direction PID_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input
};
constexpr uint8_t PID_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool PID_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction Positive_V_to_Bool_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Positive_V_to_Bool_PORT_DOMAINS[] = {
    1,
    2
};
constexpr bool Positive_V_to_Bool_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction Radiator_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Radiator_PORT_DOMAINS[] = {
    1,
    16
};
constexpr bool Radiator_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction RefNode_PORT_DIRECTIONS[] = {
    bp2::Direction::Output
};
constexpr uint8_t RefNode_PORT_DOMAINS[] = {
    1
};
constexpr bool RefNode_PORT_SOURCE_WRITER[] = {
    false
};
constexpr bp2::Direction Relay_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Relay_PORT_DOMAINS[] = {
    2,
    2,
    2,
    1,
    1
};
constexpr bool Relay_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false,
    false
};
constexpr bp2::Direction Resistor_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Resistor_PORT_DOMAINS[] = {
    1,
    1
};
constexpr bool Resistor_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction RotarySwitch1ToN_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Output,
    bp2::Direction::Output,
    bp2::Direction::Output,
    bp2::Direction::Output,
    bp2::Direction::Output,
    bp2::Direction::Input
};
constexpr uint8_t RotarySwitch1ToN_PORT_DOMAINS[] = {
    2,
    2,
    1,
    1,
    1,
    1,
    1,
    1
};
constexpr bool RotarySwitch1ToN_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false
};
constexpr bp2::Direction RotarySwitchNTo1_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t RotarySwitchNTo1_PORT_DOMAINS[] = {
    2,
    2,
    1,
    1,
    1,
    1,
    1,
    1
};
constexpr bool RotarySwitchNTo1_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false
};
constexpr bp2::Direction SampleHold_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input
};
constexpr uint8_t SampleHold_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool SampleHold_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction SlewRate_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t SlewRate_PORT_DOMAINS[] = {
    2,
    2
};
constexpr bool SlewRate_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction Slider_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Slider_PORT_DOMAINS[] = {
    2,
    2
};
constexpr bool Slider_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction SolenoidValve_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t SolenoidValve_PORT_DOMAINS[] = {
    1,
    8,
    8
};
constexpr bool SolenoidValve_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction Splitter_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Output
};
constexpr uint8_t Splitter_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool Splitter_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction Spring_PORT_DIRECTIONS[] = {
    bp2::Direction::Output,
    bp2::Direction::Input,
    bp2::Direction::Input
};
constexpr uint8_t Spring_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool Spring_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction Subtract_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Subtract_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool Subtract_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
constexpr bp2::Direction Switch_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Switch_PORT_DOMAINS[] = {
    16,
    2,
    1,
    1
};
constexpr bool Switch_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false
};
constexpr bp2::Direction TempSensor_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t TempSensor_PORT_DOMAINS[] = {
    1,
    16
};
constexpr bool TempSensor_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction TimeDelay_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t TimeDelay_PORT_DOMAINS[] = {
    2,
    2
};
constexpr bool TimeDelay_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction Transformer_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t Transformer_PORT_DOMAINS[] = {
    1,
    2
};
constexpr bool Transformer_PORT_SOURCE_WRITER[] = {
    false,
    false
};
constexpr bp2::Direction Value_PORT_DIRECTIONS[] = {
    bp2::Direction::Output
};
constexpr uint8_t Value_PORT_DOMAINS[] = {
    2
};
constexpr bool Value_PORT_SOURCE_WRITER[] = {
    false
};
constexpr bp2::Direction VariableConductance_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t VariableConductance_PORT_DOMAINS[] = {
    2,
    2,
    2,
    1,
    1
};
constexpr bool VariableConductance_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false,
    false
};
constexpr bp2::Direction VoltageSense_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output,
    bp2::Direction::Input,
    bp2::Direction::Input
};
constexpr uint8_t VoltageSense_PORT_DOMAINS[] = {
    2,
    2,
    2,
    1,
    1
};
constexpr bool VoltageSense_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false,
    false,
    false
};
constexpr bp2::Direction Voltmeter_PORT_DIRECTIONS[] = {
    bp2::Direction::Input
};
constexpr uint8_t Voltmeter_PORT_DOMAINS[] = {
    1
};
constexpr bool Voltmeter_PORT_SOURCE_WRITER[] = {
    false
};
constexpr bp2::Direction XOR_PORT_DIRECTIONS[] = {
    bp2::Direction::Input,
    bp2::Direction::Input,
    bp2::Direction::Output
};
constexpr uint8_t XOR_PORT_DOMAINS[] = {
    2,
    2,
    2
};
constexpr bool XOR_PORT_SOURCE_WRITER[] = {
    false,
    false,
    false
};
