// Auto-generated by codegen from library/*.blueprint
// DO NOT EDIT - changes will be overwritten

#pragma once

#include <cstddef>
#include <cstdint>

#include "core/solvers/common/port_names.h"
#include "blueprint_v2/interface/direction.h"
#include "core/model/component_kind.h"

/// True for valid ComponentKind values (not Unknown, not _COUNT).
inline constexpr bool has_component_metadata(ComponentKind kind) {
    return kind != ComponentKind::Unknown && static_cast<size_t>(kind) < static_cast<size_t>(ComponentKind::_COUNT);
}

/// Per-port metadata — name, direction, domain mask, source_writer flag.
struct PortMeta {
    const char* name;
    bp2::Direction direction;
    uint8_t domain;
    bool source_writer;
};

/// Per-component port info — indexed by ComponentKind.
/// Provides port range (offset + count) into PORT_META[] and component-level traits.
struct ComponentPortInfo {
    size_t port_offset;
    size_t port_count;
    bool scheduler_source;
    bool solver_owned_electrical;
    bool requires_solver_role;
};

constexpr PortMeta PORT_META[] = {
    // AND
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // AZS
    {"control", bp2::Direction::Input, 16, false},
    {"state", bp2::Direction::Output, 2, false},
    {"temp", bp2::Direction::Output, 16, false},
    {"tripped", bp2::Direction::Output, 2, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // Accumulator
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // Add
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Any_V_to_Bool
    {"Vin", bp2::Direction::Input, 1, false},
    {"o", bp2::Direction::Output, 2, false},
    // AsymSlewRate
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // AsymTMO
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // Bus
    {"v", bp2::Direction::InOut, 1, false},
    // Clamp
    {"in", bp2::Direction::Input, 2, false},
    {"max", bp2::Direction::Input, 2, false},
    {"min", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // Comparator
    {"Va", bp2::Direction::Input, 2, false},
    {"Vb", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // ControlledCurrentSource
    {"cmd", bp2::Direction::Input, 2, false},
    {"v_neg", bp2::Direction::Output, 1, false},
    {"v_pos", bp2::Direction::Output, 1, true},
    // ControlledVoltageSource
    {"cmd", bp2::Direction::Input, 2, false},
    {"gain", bp2::Direction::Input, 2, false},
    {"i_out", bp2::Direction::Output, 1, false},
    {"max_v", bp2::Direction::Input, 2, false},
    {"min_v", bp2::Direction::Input, 2, false},
    {"offset", bp2::Direction::Input, 2, false},
    {"v_neg", bp2::Direction::Input, 1, false},
    {"v_pos", bp2::Direction::Output, 1, true},
    // CurrentSense
    {"i_out", bp2::Direction::Output, 1, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // Divide
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // ElectricHeater
    {"heat_out", bp2::Direction::Output, 16, false},
    {"power", bp2::Direction::Input, 1, false},
    // ElectricPump
    {"p_in", bp2::Direction::Input, 8, false},
    {"p_out", bp2::Direction::Output, 8, false},
    {"v_in", bp2::Direction::Input, 1, false},
    // ElectricalConductance
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // ElectricalSource
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, true},
    // FastTMO
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // FuelTank
    {"flow_out", bp2::Direction::Output, 8, true},
    {"level_out", bp2::Direction::Output, 2, false},
    {"p_ref", bp2::Direction::Output, 8, false},
    {"p_source", bp2::Direction::Output, 2, false},
    // Generator
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, true},
    // Greater
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // GreaterEq
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Gyroscope
    {"input", bp2::Direction::Input, 1, false},
    // HoldButton
    {"control", bp2::Direction::Input, 16, false},
    {"state", bp2::Direction::Output, 2, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // HydraulicAccumulator
    {"p_in", bp2::Direction::Input, 8, false},
    {"p_out", bp2::Direction::Output, 8, false},
    // IndicatorLight
    {"brightness", bp2::Direction::Output, 1, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // InertiaNode
    {"damping", bp2::Direction::Input, 2, false},
    {"inv_inertia", bp2::Direction::Input, 2, false},
    {"mass", bp2::Direction::Input, 2, false},
    {"rpm_out", bp2::Direction::Output, 4, false},
    {"torque_in", bp2::Direction::Input, 2, false},
    // Integrator
    {"gain", bp2::Direction::Input, 2, false},
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    {"reset", bp2::Direction::Input, 2, false},
    // Inverter
    {"ac_out", bp2::Direction::Output, 16, false},
    {"dc_in", bp2::Direction::Input, 1, false},
    // KnobSwitch
    {"control", bp2::Direction::Input, 2, false},
    {"position", bp2::Direction::Output, 2, false},
    {"throw1", bp2::Direction::InOut, 1, false},
    {"throw2", bp2::Direction::InOut, 1, false},
    {"throw3", bp2::Direction::InOut, 1, false},
    {"throw4", bp2::Direction::InOut, 1, false},
    {"throw5", bp2::Direction::InOut, 1, false},
    {"wiper", bp2::Direction::InOut, 1, false},
    // LUT
    {"input", bp2::Direction::Input, 2, false},
    {"output", bp2::Direction::Output, 2, false},
    // LerpNode
    {"input", bp2::Direction::Input, 2, false},
    {"output", bp2::Direction::Output, 2, false},
    // Lesser
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // LesserEq
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Max
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Merger
    {"i1", bp2::Direction::Input, 2, false},
    {"i2", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Min
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Monostable
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // Multiply
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // NAND
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // NOT
    {"A", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Normalize
    {"in", bp2::Direction::Input, 2, false},
    {"max", bp2::Direction::Input, 2, false},
    {"min", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // OR
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // P
    {"feedback", bp2::Direction::Input, 2, false},
    {"output", bp2::Direction::Output, 2, false},
    {"setpoint", bp2::Direction::Input, 2, false},
    // PD
    {"feedback", bp2::Direction::Input, 2, false},
    {"output", bp2::Direction::Output, 2, false},
    {"setpoint", bp2::Direction::Input, 2, false},
    // PI
    {"Ki", bp2::Direction::Input, 2, false},
    {"Kp", bp2::Direction::Input, 2, false},
    {"feedback", bp2::Direction::Input, 2, false},
    {"output", bp2::Direction::Output, 2, false},
    {"output_max", bp2::Direction::Input, 2, false},
    {"output_min", bp2::Direction::Input, 2, false},
    {"setpoint", bp2::Direction::Input, 2, false},
    // PID
    {"feedback", bp2::Direction::Input, 2, false},
    {"output", bp2::Direction::Output, 2, false},
    {"setpoint", bp2::Direction::Input, 2, false},
    // Positive_V_to_Bool
    {"Vin", bp2::Direction::Input, 1, false},
    {"o", bp2::Direction::Output, 2, false},
    // PressureRef
    {"p", bp2::Direction::Output, 8, false},
    // Radiator
    {"heat_in", bp2::Direction::Input, 1, false},
    {"heat_out", bp2::Direction::Output, 16, false},
    // RefNode
    {"v", bp2::Direction::Output, 1, false},
    // Relay
    {"control", bp2::Direction::Input, 2, false},
    {"hold_threshold", bp2::Direction::Input, 2, false},
    {"state", bp2::Direction::Output, 2, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // Resistor
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // RotarySwitch1ToN
    {"control", bp2::Direction::Input, 2, false},
    {"position", bp2::Direction::Output, 2, false},
    {"throw1", bp2::Direction::Output, 1, false},
    {"throw2", bp2::Direction::Output, 1, false},
    {"throw3", bp2::Direction::Output, 1, false},
    {"throw4", bp2::Direction::Output, 1, false},
    {"throw5", bp2::Direction::Output, 1, false},
    {"wiper", bp2::Direction::Input, 1, false},
    // RotarySwitchNTo1
    {"control", bp2::Direction::Input, 2, false},
    {"position", bp2::Direction::Output, 2, false},
    {"throw1", bp2::Direction::Input, 1, false},
    {"throw2", bp2::Direction::Input, 1, false},
    {"throw3", bp2::Direction::Input, 1, false},
    {"throw4", bp2::Direction::Input, 1, false},
    {"throw5", bp2::Direction::Input, 1, false},
    {"wiper", bp2::Direction::Output, 1, false},
    // SampleHold
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    {"trigger", bp2::Direction::Input, 2, false},
    // SlewRate
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // Slider
    {"control", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // SolenoidValve
    {"ctrl", bp2::Direction::Input, 1, false},
    {"flow_in", bp2::Direction::Input, 8, false},
    {"flow_out", bp2::Direction::Output, 8, false},
    {"state", bp2::Direction::Output, 2, false},
    // Splitter
    {"i", bp2::Direction::Input, 2, false},
    {"o1", bp2::Direction::Output, 2, false},
    {"o2", bp2::Direction::Output, 2, false},
    // Spring
    {"force_out", bp2::Direction::Output, 2, false},
    {"pos_a", bp2::Direction::Input, 2, false},
    {"pos_b", bp2::Direction::Input, 2, false},
    // Subtract
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Switch
    {"control", bp2::Direction::Input, 16, false},
    {"state", bp2::Direction::Output, 2, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // TempSensor
    {"temp_in", bp2::Direction::Input, 1, false},
    {"temp_out", bp2::Direction::Output, 16, false},
    // TimeDelay
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // Transformer
    {"primary", bp2::Direction::Input, 1, false},
    {"secondary", bp2::Direction::Output, 2, false},
    // Value
    {"o", bp2::Direction::Output, 2, false},
    // VariableConductance
    {"cmd", bp2::Direction::Input, 2, false},
    {"g_max", bp2::Direction::Input, 2, false},
    {"g_min", bp2::Direction::Input, 2, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // VoltageSense
    {"gain", bp2::Direction::Input, 2, false},
    {"offset", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_ref", bp2::Direction::Input, 1, false},
    // Voltmeter
    {"v_in", bp2::Direction::Input, 1, false},
    // XOR
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
};

constexpr ComponentPortInfo COMPONENT_PORT_INFO[] = {
    {0, 3, false, false, false},  // AND
    {3, 6, false, true, true},  // AZS
    {9, 2, false, false, false},  // Accumulator
    {11, 3, false, false, false},  // Add
    {14, 2, false, false, false},  // Any_V_to_Bool
    {16, 2, false, false, false},  // AsymSlewRate
    {18, 2, false, false, false},  // AsymTMO
    {20, 1, false, false, false},  // Bus
    {21, 4, false, false, false},  // Clamp
    {25, 3, false, false, false},  // Comparator
    {28, 3, false, false, false},  // ControlledCurrentSource
    {31, 8, false, true, true},  // ControlledVoltageSource
    {39, 3, false, false, true},  // CurrentSense
    {42, 3, false, false, false},  // Divide
    {45, 2, false, false, false},  // ElectricHeater
    {47, 3, false, false, false},  // ElectricPump
    {50, 2, false, true, true},  // ElectricalConductance
    {52, 2, false, true, true},  // ElectricalSource
    {54, 2, false, false, false},  // FastTMO
    {56, 4, false, false, true},  // FuelTank
    {60, 2, true, true, true},  // Generator
    {62, 3, false, false, false},  // Greater
    {65, 3, false, false, false},  // GreaterEq
    {68, 1, false, false, false},  // Gyroscope
    {69, 4, false, true, true},  // HoldButton
    {73, 2, false, false, false},  // HydraulicAccumulator
    {75, 3, false, false, true},  // IndicatorLight
    {78, 5, false, false, false},  // InertiaNode
    {83, 4, false, false, false},  // Integrator
    {87, 2, false, false, false},  // Inverter
    {89, 8, false, true, true},  // KnobSwitch
    {97, 2, false, false, false},  // LUT
    {99, 2, false, false, false},  // LerpNode
    {101, 3, false, false, false},  // Lesser
    {104, 3, false, false, false},  // LesserEq
    {107, 3, false, false, false},  // Max
    {110, 3, false, false, false},  // Merger
    {113, 3, false, false, false},  // Min
    {116, 2, false, false, false},  // Monostable
    {118, 3, false, false, false},  // Multiply
    {121, 3, false, false, false},  // NAND
    {124, 2, false, false, false},  // NOT
    {126, 4, false, false, false},  // Normalize
    {130, 3, false, false, false},  // OR
    {133, 3, false, false, false},  // P
    {136, 3, false, false, false},  // PD
    {139, 7, false, false, false},  // PI
    {146, 3, false, false, false},  // PID
    {149, 2, false, false, false},  // Positive_V_to_Bool
    {151, 1, true, false, true},  // PressureRef
    {152, 2, false, false, false},  // Radiator
    {154, 1, true, false, true},  // RefNode
    {155, 5, false, true, true},  // Relay
    {160, 2, false, true, true},  // Resistor
    {162, 8, false, true, true},  // RotarySwitch1ToN
    {170, 8, false, true, true},  // RotarySwitchNTo1
    {178, 3, false, false, false},  // SampleHold
    {181, 2, false, false, false},  // SlewRate
    {183, 2, false, false, false},  // Slider
    {185, 4, false, false, true},  // SolenoidValve
    {189, 3, false, false, false},  // Splitter
    {192, 3, false, false, false},  // Spring
    {195, 3, false, false, false},  // Subtract
    {198, 4, false, false, false},  // Switch
    {202, 2, false, false, false},  // TempSensor
    {204, 2, false, false, false},  // TimeDelay
    {206, 2, false, false, false},  // Transformer
    {208, 1, true, false, false},  // Value
    {209, 5, false, true, true},  // VariableConductance
    {214, 5, false, false, false},  // VoltageSense
    {219, 1, false, false, false},  // Voltmeter
    {220, 3, false, false, false},  // XOR
    {0, 0, false, false, false},  // Unknown (sentinel)
};

static_assert(sizeof(COMPONENT_PORT_INFO) / sizeof(COMPONENT_PORT_INFO[0]) == static_cast<size_t>(ComponentKind::_COUNT),
    "COMPONENT_PORT_INFO size must match ComponentKind count");
static_assert(223 == sizeof(PORT_META) / sizeof(PORT_META[0]),
    "PORT_META total entries must match sum of all component port counts");

/// Number of ports for a given ComponentKind. Returns 0 for Unknown.
inline constexpr size_t port_count(ComponentKind kind) {
    if (!has_component_metadata(kind)) return 0;
    return COMPONENT_PORT_INFO[static_cast<size_t>(kind)].port_count;
}

