// Auto-generated by codegen from library/*.blueprint
// DO NOT EDIT - changes will be overwritten

#pragma once

#include <variant>

#include "core/solvers/common/port_traits.h"
#include "core/solvers/common/provider.h"
#include "core/solvers/jit/components/all.h"

using ComponentVariant = std::variant<
    AND<JitProvider>,
    AZS<JitProvider>,
    Accumulator<JitProvider>,
    Add<JitProvider>,
    Any_V_to_Bool<JitProvider>,
    AsymSlewRate<JitProvider>,
    AsymTMO<JitProvider>,
    Bus<JitProvider>,
    Clamp<JitProvider>,
    Comparator<JitProvider>,
    ControlledCurrentSource<JitProvider>,
    ControlledVoltageSource<JitProvider>,
    CurrentSense<JitProvider>,
    Divide<JitProvider>,
    ElectricHeater<JitProvider>,
    ElectricPump<JitProvider>,
    ElectricalConductance<JitProvider>,
    ElectricalSource<JitProvider>,
    FastTMO<JitProvider>,
    FuelTank<JitProvider>,
    Generator<JitProvider>,
    Greater<JitProvider>,
    GreaterEq<JitProvider>,
    Gyroscope<JitProvider>,
    HoldButton<JitProvider>,
    HydraulicAccumulator<JitProvider>,
    IndicatorLight<JitProvider>,
    InertiaNode<JitProvider>,
    Integrator<JitProvider>,
    Inverter<JitProvider>,
    KnobSwitch<JitProvider>,
    LUT<JitProvider>,
    LerpNode<JitProvider>,
    Lesser<JitProvider>,
    LesserEq<JitProvider>,
    LuaScript<JitProvider>,
    Max<JitProvider>,
    Merger<JitProvider>,
    Min<JitProvider>,
    Monostable<JitProvider>,
    Multiply<JitProvider>,
    NAND<JitProvider>,
    NOT<JitProvider>,
    Normalize<JitProvider>,
    OR<JitProvider>,
    P<JitProvider>,
    PD<JitProvider>,
    PI<JitProvider>,
    PID<JitProvider>,
    PneumaticCompressor<JitProvider>,
    PneumaticRef<JitProvider>,
    PneumaticValve<JitProvider>,
    Positive_V_to_Bool<JitProvider>,
    PressureRef<JitProvider>,
    Radiator<JitProvider>,
    RefNode<JitProvider>,
    Relay<JitProvider>,
    Resistor<JitProvider>,
    RotarySwitch1ToN<JitProvider>,
    RotarySwitchNTo1<JitProvider>,
    SampleHold<JitProvider>,
    SimConnectInput<JitProvider>,
    SimConnectOutput<JitProvider>,
    SlewRate<JitProvider>,
    Slider<JitProvider>,
    SolenoidValve<JitProvider>,
    Splitter<JitProvider>,
    Spring<JitProvider>,
    Subtract<JitProvider>,
    Switch<JitProvider>,
    TempSensor<JitProvider>,
    TimeDelay<JitProvider>,
    Transformer<JitProvider>,
    Value<JitProvider>,
    VariableConductance<JitProvider>,
    VoltageSense<JitProvider>,
    Voltmeter<JitProvider>,
    XOR<JitProvider>
>;

static_assert(
    std::variant_size_v<ComponentVariant> == static_cast<size_t>(ComponentKind::Unknown),
    "ComponentVariant size doesn't match real component count — re-run update_port_registry"
);

static_assert(static_cast<size_t>(ComponentKind::AND) == 0ull, "AND enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::AZS) == 1ull, "AZS enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Accumulator) == 2ull, "Accumulator enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Add) == 3ull, "Add enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Any_V_to_Bool) == 4ull, "Any_V_to_Bool enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::AsymSlewRate) == 5ull, "AsymSlewRate enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::AsymTMO) == 6ull, "AsymTMO enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Bus) == 7ull, "Bus enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Clamp) == 8ull, "Clamp enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Comparator) == 9ull, "Comparator enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::ControlledCurrentSource) == 10ull, "ControlledCurrentSource enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::ControlledVoltageSource) == 11ull, "ControlledVoltageSource enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::CurrentSense) == 12ull, "CurrentSense enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Divide) == 13ull, "Divide enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::ElectricHeater) == 14ull, "ElectricHeater enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::ElectricPump) == 15ull, "ElectricPump enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::ElectricalConductance) == 16ull, "ElectricalConductance enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::ElectricalSource) == 17ull, "ElectricalSource enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::FastTMO) == 18ull, "FastTMO enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::FuelTank) == 19ull, "FuelTank enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Generator) == 20ull, "Generator enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Greater) == 21ull, "Greater enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::GreaterEq) == 22ull, "GreaterEq enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Gyroscope) == 23ull, "Gyroscope enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::HoldButton) == 24ull, "HoldButton enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::HydraulicAccumulator) == 25ull, "HydraulicAccumulator enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::IndicatorLight) == 26ull, "IndicatorLight enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::InertiaNode) == 27ull, "InertiaNode enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Integrator) == 28ull, "Integrator enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Inverter) == 29ull, "Inverter enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::KnobSwitch) == 30ull, "KnobSwitch enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::LUT) == 31ull, "LUT enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::LerpNode) == 32ull, "LerpNode enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Lesser) == 33ull, "Lesser enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::LesserEq) == 34ull, "LesserEq enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::LuaScript) == 35ull, "LuaScript enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Max) == 36ull, "Max enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Merger) == 37ull, "Merger enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Min) == 38ull, "Min enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Monostable) == 39ull, "Monostable enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Multiply) == 40ull, "Multiply enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::NAND) == 41ull, "NAND enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::NOT) == 42ull, "NOT enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Normalize) == 43ull, "Normalize enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::OR) == 44ull, "OR enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::P) == 45ull, "P enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::PD) == 46ull, "PD enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::PI) == 47ull, "PI enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::PID) == 48ull, "PID enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::PneumaticCompressor) == 49ull, "PneumaticCompressor enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::PneumaticRef) == 50ull, "PneumaticRef enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::PneumaticValve) == 51ull, "PneumaticValve enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Positive_V_to_Bool) == 52ull, "Positive_V_to_Bool enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::PressureRef) == 53ull, "PressureRef enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Radiator) == 54ull, "Radiator enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::RefNode) == 55ull, "RefNode enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Relay) == 56ull, "Relay enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Resistor) == 57ull, "Resistor enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::RotarySwitch1ToN) == 58ull, "RotarySwitch1ToN enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::RotarySwitchNTo1) == 59ull, "RotarySwitchNTo1 enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::SampleHold) == 60ull, "SampleHold enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::SimConnectInput) == 61ull, "SimConnectInput enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::SimConnectOutput) == 62ull, "SimConnectOutput enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::SlewRate) == 63ull, "SlewRate enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Slider) == 64ull, "Slider enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::SolenoidValve) == 65ull, "SolenoidValve enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Splitter) == 66ull, "Splitter enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Spring) == 67ull, "Spring enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Subtract) == 68ull, "Subtract enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Switch) == 69ull, "Switch enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::TempSensor) == 70ull, "TempSensor enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::TimeDelay) == 71ull, "TimeDelay enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Transformer) == 72ull, "Transformer enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Value) == 73ull, "Value enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::VariableConductance) == 74ull, "VariableConductance enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::VoltageSense) == 75ull, "VoltageSense enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::Voltmeter) == 76ull, "Voltmeter enum position mismatch — re-run update_port_registry");
static_assert(static_cast<size_t>(ComponentKind::XOR) == 77ull, "XOR enum position mismatch — re-run update_port_registry");

