// Auto-generated by codegen from library/*.blueprint
// DO NOT EDIT - changes will be overwritten

#pragma once

#include <cstddef>
#include <cstdint>

#include "core/solvers/common/port_names.h"
#include "core/model/component_types.h"
#include "blueprint_v2/interface/direction.h"
#include "core/model/component_kind.h"

/// True for valid ComponentKind values (not Unknown, not _COUNT).
inline constexpr bool has_component_metadata(ComponentKind kind) {
    return kind != ComponentKind::Unknown && static_cast<size_t>(kind) < static_cast<size_t>(ComponentKind::_COUNT);
}

/// Per-port metadata — name, direction, domain mask, source_writer flag.
struct PortMeta {
    const char* name;
    bp2::Direction direction;
    uint8_t domain;
    bool source_writer;
};

/// Per-component port info — indexed by ComponentKind.
/// Provides port range (offset + count) into PORT_META[] and component-level traits.
struct ComponentPortInfo {
    size_t port_offset;
    size_t port_count;
    SchedulerRoleKind scheduler_role_kind;
    bool requires_solver_role;
};

constexpr PortMeta PORT_META[] = {
    // AND
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // AZS
    {"control", bp2::Direction::Input, 16, false},
    {"state", bp2::Direction::Output, 2, false},
    {"temp", bp2::Direction::Output, 16, false},
    {"tripped", bp2::Direction::Output, 2, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // Accumulator
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // Add
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Any_V_to_Bool
    {"Vin", bp2::Direction::Input, 1, false},
    {"o", bp2::Direction::Output, 2, false},
    // AsymSlewRate
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // AsymTMO
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // Bus
    {"v", bp2::Direction::InOut, 1, false},
    // Clamp
    {"in", bp2::Direction::Input, 2, false},
    {"max", bp2::Direction::Input, 2, false},
    {"min", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // Comparator
    {"Va", bp2::Direction::Input, 2, false},
    {"Vb", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // ControlledCurrentSource
    {"cmd", bp2::Direction::Input, 2, false},
    {"v_neg", bp2::Direction::Output, 1, false},
    {"v_pos", bp2::Direction::Output, 1, true},
    // ControlledVoltageSource
    {"cmd", bp2::Direction::Input, 2, false},
    {"gain", bp2::Direction::Input, 2, false},
    {"i_out", bp2::Direction::Output, 1, false},
    {"max_v", bp2::Direction::Input, 2, false},
    {"min_v", bp2::Direction::Input, 2, false},
    {"offset", bp2::Direction::Input, 2, false},
    {"v_neg", bp2::Direction::Input, 1, false},
    {"v_pos", bp2::Direction::Output, 1, true},
    // CurrentSense
    {"i_out", bp2::Direction::Output, 1, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // Divide
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // ElectricHeater
    {"heat_out", bp2::Direction::Output, 16, false},
    {"power", bp2::Direction::Input, 1, false},
    // ElectricPump
    {"p_in", bp2::Direction::Input, 8, false},
    {"p_out", bp2::Direction::Output, 8, false},
    {"v_in", bp2::Direction::Input, 1, false},
    // ElectricalConductance
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // ElectricalSource
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, true},
    // FastTMO
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // FuelTank
    {"flow_out", bp2::Direction::Output, 8, true},
    {"level_out", bp2::Direction::Output, 2, false},
    {"p_ref", bp2::Direction::Output, 8, false},
    {"p_source", bp2::Direction::Output, 2, false},
    // Generator
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, true},
    // Greater
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // GreaterEq
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Gyroscope
    {"input", bp2::Direction::Input, 1, false},
    // HoldButton
    {"control", bp2::Direction::Input, 16, false},
    {"state", bp2::Direction::Output, 2, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // HydraulicAccumulator
    {"p_in", bp2::Direction::Input, 8, false},
    {"p_out", bp2::Direction::Output, 8, false},
    // IndicatorLight
    {"brightness", bp2::Direction::Output, 1, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // InertiaNode
    {"damping", bp2::Direction::Input, 2, false},
    {"inv_inertia", bp2::Direction::Input, 2, false},
    {"mass", bp2::Direction::Input, 2, false},
    {"rpm_out", bp2::Direction::Output, 4, false},
    {"torque_in", bp2::Direction::Input, 2, false},
    // Integrator
    {"gain", bp2::Direction::Input, 2, false},
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    {"reset", bp2::Direction::Input, 2, false},
    // Inverter
    {"ac_out", bp2::Direction::Output, 16, false},
    {"dc_in", bp2::Direction::Input, 1, false},
    // KnobSwitch
    {"control", bp2::Direction::Input, 2, false},
    {"position", bp2::Direction::Output, 2, false},
    {"throw1", bp2::Direction::InOut, 1, false},
    {"throw2", bp2::Direction::InOut, 1, false},
    {"throw3", bp2::Direction::InOut, 1, false},
    {"throw4", bp2::Direction::InOut, 1, false},
    {"throw5", bp2::Direction::InOut, 1, false},
    {"wiper", bp2::Direction::InOut, 1, false},
    // LUT
    {"input", bp2::Direction::Input, 2, false},
    {"output", bp2::Direction::Output, 2, false},
    // LerpNode
    {"input", bp2::Direction::Input, 2, false},
    {"output", bp2::Direction::Output, 2, false},
    // Lesser
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // LesserEq
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // LuaScript
    {"in1", bp2::Direction::Input, 2, false},
    {"in10", bp2::Direction::Input, 2, false},
    {"in11", bp2::Direction::Input, 2, false},
    {"in12", bp2::Direction::Input, 2, false},
    {"in13", bp2::Direction::Input, 2, false},
    {"in14", bp2::Direction::Input, 2, false},
    {"in15", bp2::Direction::Input, 2, false},
    {"in16", bp2::Direction::Input, 2, false},
    {"in2", bp2::Direction::Input, 2, false},
    {"in3", bp2::Direction::Input, 2, false},
    {"in4", bp2::Direction::Input, 2, false},
    {"in5", bp2::Direction::Input, 2, false},
    {"in6", bp2::Direction::Input, 2, false},
    {"in7", bp2::Direction::Input, 2, false},
    {"in8", bp2::Direction::Input, 2, false},
    {"in9", bp2::Direction::Input, 2, false},
    {"out1", bp2::Direction::Output, 2, false},
    {"out10", bp2::Direction::Output, 2, false},
    {"out11", bp2::Direction::Output, 2, false},
    {"out12", bp2::Direction::Output, 2, false},
    {"out13", bp2::Direction::Output, 2, false},
    {"out14", bp2::Direction::Output, 2, false},
    {"out15", bp2::Direction::Output, 2, false},
    {"out16", bp2::Direction::Output, 2, false},
    {"out2", bp2::Direction::Output, 2, false},
    {"out3", bp2::Direction::Output, 2, false},
    {"out4", bp2::Direction::Output, 2, false},
    {"out5", bp2::Direction::Output, 2, false},
    {"out6", bp2::Direction::Output, 2, false},
    {"out7", bp2::Direction::Output, 2, false},
    {"out8", bp2::Direction::Output, 2, false},
    {"out9", bp2::Direction::Output, 2, false},
    // Max
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Merger
    {"i1", bp2::Direction::Input, 2, false},
    {"i2", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Min
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Monostable
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // Multiply
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // NAND
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // NOT
    {"A", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Normalize
    {"in", bp2::Direction::Input, 2, false},
    {"max", bp2::Direction::Input, 2, false},
    {"min", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // OR
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // P
    {"feedback", bp2::Direction::Input, 2, false},
    {"output", bp2::Direction::Output, 2, false},
    {"setpoint", bp2::Direction::Input, 2, false},
    // PD
    {"feedback", bp2::Direction::Input, 2, false},
    {"output", bp2::Direction::Output, 2, false},
    {"setpoint", bp2::Direction::Input, 2, false},
    // PI
    {"Ki", bp2::Direction::Input, 2, false},
    {"Kp", bp2::Direction::Input, 2, false},
    {"feedback", bp2::Direction::Input, 2, false},
    {"output", bp2::Direction::Output, 2, false},
    {"output_max", bp2::Direction::Input, 2, false},
    {"output_min", bp2::Direction::Input, 2, false},
    {"setpoint", bp2::Direction::Input, 2, false},
    // PID
    {"feedback", bp2::Direction::Input, 2, false},
    {"output", bp2::Direction::Output, 2, false},
    {"setpoint", bp2::Direction::Input, 2, false},
    // PneumaticCompressor
    {"p_out", bp2::Direction::Output, 32, true},
    {"p_ref", bp2::Direction::Output, 32, false},
    {"p_source", bp2::Direction::Output, 2, false},
    {"rpm_in", bp2::Direction::Input, 4, false},
    // PneumaticRef
    {"p", bp2::Direction::Output, 32, false},
    // PneumaticValve
    {"ctrl", bp2::Direction::Input, 1, false},
    {"flow_in", bp2::Direction::Input, 32, false},
    {"flow_out", bp2::Direction::Output, 32, false},
    {"state", bp2::Direction::Output, 2, false},
    // Positive_V_to_Bool
    {"Vin", bp2::Direction::Input, 1, false},
    {"o", bp2::Direction::Output, 2, false},
    // PressureRef
    {"p", bp2::Direction::Output, 8, false},
    // Radiator
    {"heat_in", bp2::Direction::Input, 1, false},
    {"heat_out", bp2::Direction::Output, 16, false},
    // RefNode
    {"v", bp2::Direction::Output, 1, false},
    // Relay
    {"control", bp2::Direction::Input, 2, false},
    {"hold_threshold", bp2::Direction::Input, 2, false},
    {"state", bp2::Direction::Output, 2, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // Resistor
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // RotarySwitch1ToN
    {"control", bp2::Direction::Input, 2, false},
    {"position", bp2::Direction::Output, 2, false},
    {"throw1", bp2::Direction::Output, 1, false},
    {"throw2", bp2::Direction::Output, 1, false},
    {"throw3", bp2::Direction::Output, 1, false},
    {"throw4", bp2::Direction::Output, 1, false},
    {"throw5", bp2::Direction::Output, 1, false},
    {"wiper", bp2::Direction::Input, 1, false},
    // RotarySwitchNTo1
    {"control", bp2::Direction::Input, 2, false},
    {"position", bp2::Direction::Output, 2, false},
    {"throw1", bp2::Direction::Input, 1, false},
    {"throw2", bp2::Direction::Input, 1, false},
    {"throw3", bp2::Direction::Input, 1, false},
    {"throw4", bp2::Direction::Input, 1, false},
    {"throw5", bp2::Direction::Input, 1, false},
    {"wiper", bp2::Direction::Output, 1, false},
    // SampleHold
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    {"trigger", bp2::Direction::Input, 2, false},
    // SlewRate
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // Slider
    {"control", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // SolenoidValve
    {"ctrl", bp2::Direction::Input, 1, false},
    {"flow_in", bp2::Direction::Input, 8, false},
    {"flow_out", bp2::Direction::Output, 8, false},
    {"state", bp2::Direction::Output, 2, false},
    // Splitter
    {"i", bp2::Direction::Input, 2, false},
    {"o1", bp2::Direction::Output, 2, false},
    {"o2", bp2::Direction::Output, 2, false},
    // Spring
    {"force_out", bp2::Direction::Output, 2, false},
    {"pos_a", bp2::Direction::Input, 2, false},
    {"pos_b", bp2::Direction::Input, 2, false},
    // Subtract
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
    // Switch
    {"control", bp2::Direction::Input, 16, false},
    {"state", bp2::Direction::Output, 2, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // TempSensor
    {"temp_in", bp2::Direction::Input, 1, false},
    {"temp_out", bp2::Direction::Output, 16, false},
    // TimeDelay
    {"in", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    // Transformer
    {"primary", bp2::Direction::Input, 1, false},
    {"secondary", bp2::Direction::Output, 2, false},
    // Value
    {"o", bp2::Direction::Output, 2, false},
    // VariableConductance
    {"cmd", bp2::Direction::Input, 2, false},
    {"g_max", bp2::Direction::Input, 2, false},
    {"g_min", bp2::Direction::Input, 2, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_out", bp2::Direction::Output, 1, false},
    // VoltageSense
    {"gain", bp2::Direction::Input, 2, false},
    {"offset", bp2::Direction::Input, 2, false},
    {"out", bp2::Direction::Output, 2, false},
    {"v_in", bp2::Direction::Input, 1, false},
    {"v_ref", bp2::Direction::Input, 1, false},
    // Voltmeter
    {"v_in", bp2::Direction::Input, 1, false},
    // XOR
    {"A", bp2::Direction::Input, 2, false},
    {"B", bp2::Direction::Input, 2, false},
    {"o", bp2::Direction::Output, 2, false},
};

constexpr ComponentPortInfo COMPONENT_PORT_INFO[] = {
    {0, 3, SchedulerRoleKind::Consumer, false},  // AND
    {3, 6, SchedulerRoleKind::None, true},  // AZS
    {9, 2, SchedulerRoleKind::Consumer, false},  // Accumulator
    {11, 3, SchedulerRoleKind::Consumer, false},  // Add
    {14, 2, SchedulerRoleKind::Consumer, false},  // Any_V_to_Bool
    {16, 2, SchedulerRoleKind::Consumer, false},  // AsymSlewRate
    {18, 2, SchedulerRoleKind::Consumer, false},  // AsymTMO
    {20, 1, SchedulerRoleKind::Consumer, false},  // Bus
    {21, 4, SchedulerRoleKind::Consumer, false},  // Clamp
    {25, 3, SchedulerRoleKind::Consumer, false},  // Comparator
    {28, 3, SchedulerRoleKind::Consumer, false},  // ControlledCurrentSource
    {31, 8, SchedulerRoleKind::None, true},  // ControlledVoltageSource
    {39, 3, SchedulerRoleKind::None, true},  // CurrentSense
    {42, 3, SchedulerRoleKind::Consumer, false},  // Divide
    {45, 2, SchedulerRoleKind::Consumer, false},  // ElectricHeater
    {47, 3, SchedulerRoleKind::Consumer, false},  // ElectricPump
    {50, 2, SchedulerRoleKind::None, true},  // ElectricalConductance
    {52, 2, SchedulerRoleKind::None, true},  // ElectricalSource
    {54, 2, SchedulerRoleKind::Consumer, false},  // FastTMO
    {56, 4, SchedulerRoleKind::None, true},  // FuelTank
    {60, 2, SchedulerRoleKind::None, true},  // Generator
    {62, 3, SchedulerRoleKind::Consumer, false},  // Greater
    {65, 3, SchedulerRoleKind::Consumer, false},  // GreaterEq
    {68, 1, SchedulerRoleKind::Consumer, false},  // Gyroscope
    {69, 4, SchedulerRoleKind::None, true},  // HoldButton
    {73, 2, SchedulerRoleKind::Consumer, false},  // HydraulicAccumulator
    {75, 3, SchedulerRoleKind::None, true},  // IndicatorLight
    {78, 5, SchedulerRoleKind::Consumer, false},  // InertiaNode
    {83, 4, SchedulerRoleKind::Consumer, false},  // Integrator
    {87, 2, SchedulerRoleKind::Consumer, false},  // Inverter
    {89, 8, SchedulerRoleKind::None, true},  // KnobSwitch
    {97, 2, SchedulerRoleKind::Consumer, false},  // LUT
    {99, 2, SchedulerRoleKind::Consumer, false},  // LerpNode
    {101, 3, SchedulerRoleKind::Consumer, false},  // Lesser
    {104, 3, SchedulerRoleKind::Consumer, false},  // LesserEq
    {107, 32, SchedulerRoleKind::Consumer, false},  // LuaScript
    {139, 3, SchedulerRoleKind::Consumer, false},  // Max
    {142, 3, SchedulerRoleKind::Consumer, false},  // Merger
    {145, 3, SchedulerRoleKind::Consumer, false},  // Min
    {148, 2, SchedulerRoleKind::Consumer, false},  // Monostable
    {150, 3, SchedulerRoleKind::Consumer, false},  // Multiply
    {153, 3, SchedulerRoleKind::Consumer, false},  // NAND
    {156, 2, SchedulerRoleKind::Consumer, false},  // NOT
    {158, 4, SchedulerRoleKind::Consumer, false},  // Normalize
    {162, 3, SchedulerRoleKind::Consumer, false},  // OR
    {165, 3, SchedulerRoleKind::Consumer, false},  // P
    {168, 3, SchedulerRoleKind::Consumer, false},  // PD
    {171, 7, SchedulerRoleKind::Consumer, false},  // PI
    {178, 3, SchedulerRoleKind::Consumer, false},  // PID
    {181, 4, SchedulerRoleKind::None, true},  // PneumaticCompressor
    {185, 1, SchedulerRoleKind::Source, true},  // PneumaticRef
    {186, 4, SchedulerRoleKind::None, true},  // PneumaticValve
    {190, 2, SchedulerRoleKind::Consumer, false},  // Positive_V_to_Bool
    {192, 1, SchedulerRoleKind::Source, true},  // PressureRef
    {193, 2, SchedulerRoleKind::Consumer, false},  // Radiator
    {195, 1, SchedulerRoleKind::Source, true},  // RefNode
    {196, 5, SchedulerRoleKind::None, true},  // Relay
    {201, 2, SchedulerRoleKind::None, true},  // Resistor
    {203, 8, SchedulerRoleKind::None, true},  // RotarySwitch1ToN
    {211, 8, SchedulerRoleKind::None, true},  // RotarySwitchNTo1
    {219, 3, SchedulerRoleKind::Consumer, false},  // SampleHold
    {222, 2, SchedulerRoleKind::Consumer, false},  // SlewRate
    {224, 2, SchedulerRoleKind::Consumer, false},  // Slider
    {226, 4, SchedulerRoleKind::None, true},  // SolenoidValve
    {230, 3, SchedulerRoleKind::Consumer, false},  // Splitter
    {233, 3, SchedulerRoleKind::Consumer, false},  // Spring
    {236, 3, SchedulerRoleKind::Consumer, false},  // Subtract
    {239, 4, SchedulerRoleKind::Consumer, false},  // Switch
    {243, 2, SchedulerRoleKind::Consumer, false},  // TempSensor
    {245, 2, SchedulerRoleKind::Consumer, false},  // TimeDelay
    {247, 2, SchedulerRoleKind::Consumer, false},  // Transformer
    {249, 1, SchedulerRoleKind::Source, false},  // Value
    {250, 5, SchedulerRoleKind::None, true},  // VariableConductance
    {255, 5, SchedulerRoleKind::Consumer, false},  // VoltageSense
    {260, 1, SchedulerRoleKind::Consumer, false},  // Voltmeter
    {261, 3, SchedulerRoleKind::Consumer, false},  // XOR
    {0, 0, SchedulerRoleKind::Consumer, false},  // Unknown (sentinel)
};

static_assert(sizeof(COMPONENT_PORT_INFO) / sizeof(COMPONENT_PORT_INFO[0]) == static_cast<size_t>(ComponentKind::_COUNT),
    "COMPONENT_PORT_INFO size must match ComponentKind count");
static_assert(264 == sizeof(PORT_META) / sizeof(PORT_META[0]),
    "PORT_META total entries must match sum of all component port counts");

/// Number of ports for a given ComponentKind. Returns 0 for Unknown.
inline constexpr size_t port_count(ComponentKind kind) {
    if (!has_component_metadata(kind)) return 0;
    return COMPONENT_PORT_INFO[static_cast<size_t>(kind)].port_count;
}

