// Auto-generated by codegen from library/*.blueprint
// DO NOT EDIT - changes will be overwritten
//
// Port traits: lookup functions, trait arrays, and predicate helpers.
// Zero component-header dependencies — only needs port_metadata.h + component_kind.h.

#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>
#include <optional>
#include <vector>

#include "core/solvers/common/port_metadata.h"
#include "core/model/component_kind.h"

inline std::optional<PortNames> string_to_port_name(const std::string& name) {
    static const std::unordered_map<std::string, PortNames> map = {
        {"A", PortNames::A},
        {"B", PortNames::B},
        {"Ki", PortNames::Ki},
        {"Kp", PortNames::Kp},
        {"Va", PortNames::Va},
        {"Vb", PortNames::Vb},
        {"Vin", PortNames::Vin},
        {"ac_out", PortNames::ac_out},
        {"brightness", PortNames::brightness},
        {"cmd", PortNames::cmd},
        {"control", PortNames::control},
        {"ctrl", PortNames::ctrl},
        {"damping", PortNames::damping},
        {"dc_in", PortNames::dc_in},
        {"feedback", PortNames::feedback},
        {"flow_in", PortNames::flow_in},
        {"flow_out", PortNames::flow_out},
        {"force_out", PortNames::force_out},
        {"g_max", PortNames::g_max},
        {"g_min", PortNames::g_min},
        {"gain", PortNames::gain},
        {"heat_in", PortNames::heat_in},
        {"heat_out", PortNames::heat_out},
        {"hold_threshold", PortNames::hold_threshold},
        {"i", PortNames::i},
        {"i1", PortNames::i1},
        {"i2", PortNames::i2},
        {"i_out", PortNames::i_out},
        {"in", PortNames::in},
        {"in1", PortNames::in1},
        {"in10", PortNames::in10},
        {"in11", PortNames::in11},
        {"in12", PortNames::in12},
        {"in13", PortNames::in13},
        {"in14", PortNames::in14},
        {"in15", PortNames::in15},
        {"in16", PortNames::in16},
        {"in2", PortNames::in2},
        {"in3", PortNames::in3},
        {"in4", PortNames::in4},
        {"in5", PortNames::in5},
        {"in6", PortNames::in6},
        {"in7", PortNames::in7},
        {"in8", PortNames::in8},
        {"in9", PortNames::in9},
        {"input", PortNames::input},
        {"inv_inertia", PortNames::inv_inertia},
        {"level_out", PortNames::level_out},
        {"mass", PortNames::mass},
        {"max", PortNames::max},
        {"max_v", PortNames::max_v},
        {"min", PortNames::min},
        {"min_v", PortNames::min_v},
        {"o", PortNames::o},
        {"o1", PortNames::o1},
        {"o2", PortNames::o2},
        {"offset", PortNames::offset},
        {"out", PortNames::out},
        {"out1", PortNames::out1},
        {"out10", PortNames::out10},
        {"out11", PortNames::out11},
        {"out12", PortNames::out12},
        {"out13", PortNames::out13},
        {"out14", PortNames::out14},
        {"out15", PortNames::out15},
        {"out16", PortNames::out16},
        {"out2", PortNames::out2},
        {"out3", PortNames::out3},
        {"out4", PortNames::out4},
        {"out5", PortNames::out5},
        {"out6", PortNames::out6},
        {"out7", PortNames::out7},
        {"out8", PortNames::out8},
        {"out9", PortNames::out9},
        {"output", PortNames::output},
        {"output_max", PortNames::output_max},
        {"output_min", PortNames::output_min},
        {"p", PortNames::p},
        {"p_in", PortNames::p_in},
        {"p_out", PortNames::p_out},
        {"p_ref", PortNames::p_ref},
        {"p_source", PortNames::p_source},
        {"pos_a", PortNames::pos_a},
        {"pos_b", PortNames::pos_b},
        {"position", PortNames::position},
        {"power", PortNames::power},
        {"primary", PortNames::primary},
        {"reset", PortNames::reset},
        {"rpm_in", PortNames::rpm_in},
        {"rpm_out", PortNames::rpm_out},
        {"secondary", PortNames::secondary},
        {"setpoint", PortNames::setpoint},
        {"state", PortNames::state},
        {"temp", PortNames::temp},
        {"temp_in", PortNames::temp_in},
        {"temp_out", PortNames::temp_out},
        {"throw1", PortNames::throw1},
        {"throw2", PortNames::throw2},
        {"throw3", PortNames::throw3},
        {"throw4", PortNames::throw4},
        {"throw5", PortNames::throw5},
        {"torque_in", PortNames::torque_in},
        {"trigger", PortNames::trigger},
        {"tripped", PortNames::tripped},
        {"v", PortNames::v},
        {"v_in", PortNames::v_in},
        {"v_neg", PortNames::v_neg},
        {"v_out", PortNames::v_out},
        {"v_pos", PortNames::v_pos},
        {"v_ref", PortNames::v_ref},
        {"wiper", PortNames::wiper},
    };
    auto it = map.find(name);
    if (it != map.end()) return it->second;
    return std::nullopt;
}

inline std::vector<std::string> get_component_ports(ComponentKind kind) {
    if (!has_component_metadata(kind)) return {};
    const auto& meta = COMPONENT_PORT_INFO[static_cast<size_t>(kind)];
    std::vector<std::string> result;
    result.reserve(meta.port_count);
    for (size_t i = meta.port_offset; i < meta.port_offset + meta.port_count; ++i)
        result.push_back(PORT_META[i].name);
    return result;
}

inline std::vector<std::string> get_output_ports(ComponentKind kind) {
    if (!has_component_metadata(kind)) return {};
    const auto& meta = COMPONENT_PORT_INFO[static_cast<size_t>(kind)];
    std::vector<std::string> result;
    for (size_t i = meta.port_offset; i < meta.port_offset + meta.port_count; ++i) {
        if (PORT_META[i].direction == bp2::Direction::Output ||
            PORT_META[i].direction == bp2::Direction::InOut)
            result.push_back(PORT_META[i].name);
    }
    return result;
}

inline std::vector<std::string> get_source_writer_ports(ComponentKind kind, uint8_t domain_mask) {
    if (!has_component_metadata(kind)) return {};
    const auto& meta = COMPONENT_PORT_INFO[static_cast<size_t>(kind)];
    std::vector<std::string> result;
    for (size_t i = meta.port_offset; i < meta.port_offset + meta.port_count; ++i) {
        if (PORT_META[i].source_writer && (PORT_META[i].domain & domain_mask) != 0)
            result.push_back(PORT_META[i].name);
    }
    return result;
}

inline SchedulerRoleKind component_scheduler_role(ComponentKind kind) {
    return has_component_metadata(kind) ? COMPONENT_PORT_INFO[static_cast<size_t>(kind)].scheduler_role_kind : SchedulerRoleKind::Consumer;
}

inline bool is_scheduler_source_component(ComponentKind kind) {
    return component_scheduler_role(kind) == SchedulerRoleKind::Source;
}

inline bool is_solver_owned_component(ComponentKind kind) {
    return component_scheduler_role(kind) == SchedulerRoleKind::None;
}

inline bool requires_solver_role_component(ComponentKind kind) {
    return has_component_metadata(kind) && COMPONENT_PORT_INFO[static_cast<size_t>(kind)].requires_solver_role;
}

