#include "codegen.h"
#include "codegen_utils.h"
#include "../parse_number.h"
#include <spdlog/spdlog.h>
#include <fstream>
#include <sstream>
#include <iostream>
#include <algorithm>
#include <cctype>
#include <map>
#include <set>
#include <unordered_set>
#include <charconv>
#include <climits>
#include <cstdlib>
#include <cstdio>


namespace {

std::string to_upper(const std::string& s) {
    std::string result = s;
    for (char& c : result) c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    return result;
}

std::string sanitize_name(const std::string& s) {
    return sanitize_codegen_name(s);
}

// Infer C++ type from parameter value (locale-independent)
std::string infer_type(const std::string& value) {
    if (value.empty()) return "float";

    long long ival;
    if (locale_safe::parse_int64(value, ival)) {
        if (ival > INT32_MAX || ival < INT32_MIN) return "int64_t";
        return "int32_t";
    }

    if (locale_safe::is_float_literal(value)) {
        return "float";
    }

    if (value == "true" || value == "false") return "bool";

    return "std::string";
}

// Format value for C++ code (locale-independent)
std::string format_value(const std::string& value, const std::string& type) {
    if (type == "float") {
        float f;
        if (locale_safe::parse_float(value, f)) {
            return locale_safe::format_float(f) + "f";
        }
        // Fallback: ensure it has a decimal point
        std::string v = value;
        if (v.find('.') == std::string::npos) {
            v += ".0";
        }
        return v;
    } else if (type == "bool") {
        return value;
    } else if (type == "int32_t" || type == "int64_t") {
        return value;
    } else if (type == "std::string") {
        return "std::string(\"" + value + "\")";
    } else {
        return "\"" + value + "\"";
    }
}

// Generate AotProvider<Binding<...>, ...> type string for a device
std::string generate_aot_provider_type(
    const DeviceInstance& dev,
    const std::unordered_map<std::string, uint32_t>& port_to_signal,
    uint32_t signal_count
) {
    std::ostringstream oss;
    oss << "AotProvider<";
    bool first = true;
    for (const auto& port : dev.ports) {
        const std::string& port_name = port.first;
        if (port.second.alias.has_value() && !port.second.alias.value().empty()) {
            continue;
        }
        std::string port_key = dev.name + "." + port_name;
        uint32_t sig = port_to_signal.count(port_key) ? port_to_signal.at(port_key) : signal_count;
        if (!first) oss << ", ";
        oss << "Binding<PortNames::" << port_name << ", " << sig << ">";
        first = false;
    }
    oss << ">";
    return oss.str();
}

// Get port name from device port definitions - NO FALLBACKS, fail hard
std::string get_port_name(const std::unordered_map<std::string, Port>& ports, const std::string& required_port) {
    if (ports.count(required_port)) {
        return required_port;
    }

    // Build error message listing available ports
    std::string available = "{";
    for (const auto& [name, port] : ports) {
        available += name + " ";
    }
    available += "}";

    throw std::runtime_error("_codegen error: required port '" + required_port + "' not found. Available ports: " + available);
}

} // anonymous namespace

std::string CodeGen::generate_header(
    const std::string& source_file,
    const std::vector<DeviceInstance>& devices_unfiltered,
    const std::vector<Connection>& connections,
    const std::unordered_map<std::string, uint32_t>& port_to_signal,
    uint32_t signal_count,
    const std::string& class_name,
    const ElectricalPlanCodegen& electrical_plan
) {
    // Filter out visual-only devices (no simulation behavior, e.g. Group)
    std::vector<DeviceInstance> devices;
    devices.reserve(devices_unfiltered.size());
    for (const auto& d : devices_unfiltered)
        if (!d.visual_only) devices.push_back(d);

    std::ostringstream oss;

    // Header guard
    std::string guard = "GENERATED_" + sanitize_name(source_file);
    std::replace(guard.begin(), guard.end(), '/', '_');
    std::replace(guard.begin(), guard.end(), '\\', '_');
    guard += "_H";

    oss << "// Auto-generated by codegen from " << source_file << "\n";
    oss << "// DO NOT EDIT - this will be overwritten on next build\n";
    oss << "// ECS-like optimized: jump table, __restrict, no aliasing\n\n";

    oss << "#pragma once\n\n";
    oss << "#include <cstdint>\n";
    oss << "#include <string>\n";
    oss << "#include <array>\n";
    oss << "#include <vector>\n";
    oss << "#include <cmath>\n";
    oss << "#include \"jit_solver/state.h\"\n";
    oss << "#include \"jit_solver/components/all.h\"\n";
    oss << "#include \"jit_solver/components/port_registry.h\"\n\n";
    oss << "// Compiler hints for optimization\n";
    oss << "#ifdef __GNUC__\n";
    oss << "#define AOT_INLINE __attribute__((always_inline)) inline\n";
    oss << "#define AOT_LIKELY(x) __builtin_expect(!!(x), 1)\n";
    oss << "#define AOT_UNLIKELY(x) __builtin_expect(!!(x), 0)\n";
    oss << "#else\n";
    oss << "#define AOT_INLINE inline\n";
    oss << "#define AOT_LIKELY(x) (x)\n";
    oss << "#define AOT_UNLIKELY(x) (x)\n";
    oss << "#endif\n\n";

    // Signal constants
    oss << "// ==============================================================================\n";
    oss << "// SIGNAL INDICES (ECS-like: direct array access, no lookups)\n";
    oss << "// ==============================================================================\n\n";

    for (const auto& [port, sig] : port_to_signal) {
        std::string const_name = "SIG_" + sanitize_name(to_upper(port));
        oss << "constexpr uint32_t " << const_name << " = " << sig << ";\n";
    }
    oss << "\n";

    // Fixed signals
    oss << "/// Fixed signal indices (RefNode bus voltages)\n";
    oss << "constexpr uint32_t FIXED_SIGNALS[] = {";
    bool first = true;
    for (const auto& dev : devices) {
        if (dev.classname == "RefNode") {
            std::string port_key = dev.name + ".v";
            if (port_to_signal.count(port_key)) {
                if (!first) oss << ", ";
                oss << port_to_signal.at(port_key);
                first = false;
            }
        }
    }
    oss << "};\n\n";

    // Signal count
    oss << "/// Total number of unique signals (for memory allocation)\n";
    oss << "constexpr uint32_t SIGNAL_COUNT = " << signal_count << ";\n\n";

    // Device count
    oss << "/// Number of devices in this system\n";
    oss << "constexpr uint32_t DEVICE_COUNT = " << devices.size() << ";\n\n";

    // Electrical plan — static island data for AOT solve_electrical()
    if (!electrical_plan.islands.empty()) {
        oss << "// ==============================================================================\n";
        oss << "// ELECTRICAL ISLAND PLAN (AOT static arrays)\n";
        oss << "// ==============================================================================\n\n";

        oss << "constexpr uint32_t ELECTRICAL_ISLAND_COUNT = "
            << electrical_plan.islands.size() << ";\n\n";

        // Emit element kind enum for codegen use in static arrays
        // (runtime uses ElectricalElementKind which has same values)
        for (size_t island_idx = 0; island_idx < electrical_plan.islands.size(); ++island_idx) {
            const auto& island = electrical_plan.islands[island_idx];
            oss << "// -- Island " << island_idx << " --\n";

            // Signal indices for this island
            oss << "constexpr uint32_t island_" << island_idx << "_nodes[] = {";
            for (size_t i = 0; i < island.signal_indices.size(); ++i) {
                if (i > 0) oss << ", ";
                oss << island.signal_indices[i];
            }
            oss << "};\n";

            // Elements for this island
            oss << "constexpr uint32_t island_" << island_idx << "_element_count = "
                << island.elements.size() << ";\n";

            oss << "constexpr ElectricalElement island_" << island_idx << "_elements[] = {\n";
            for (const auto& elem : island.elements) {
                const char* kind_str = "ElectricalElementKind::FixedVoltageNode";
                if (elem.kind == ElectricalElementKindCodegen::TheveninSource) kind_str = "ElectricalElementKind::TheveninSource";
                else if (elem.kind == ElectricalElementKindCodegen::ConductanceBranch) kind_str = "ElectricalElementKind::ConductanceBranch";
                oss << "    { " << kind_str << ", " << elem.node_a << ", " << elem.node_b
                    << ", " << locale_safe::format_float(elem.value_a) << "f, "
                    << locale_safe::format_float(elem.value_b) << "f, " << elem.component_index << " },\n";
            }
            oss << "};\n\n";
        }

        // ElectricalBuildPlan struct using static arrays
        oss << "// ElectricalBuildPlan adapter: uses static constexpr arrays\n";
        oss << "struct AotElectricalPlan {\n";
        oss << "    std::vector<ElectricalIslandPlan> islands;\n";
        oss << "    AotElectricalPlan() {\n";
        for (size_t island_idx = 0; island_idx < electrical_plan.islands.size(); ++island_idx) {
            const auto& island = electrical_plan.islands[island_idx];
            oss << "        // Island " << island_idx << "\n";
            oss << "        ElectricalIslandPlan isl;\n";
            oss << "        isl.signal_indices.assign(island_" << island_idx << "_nodes, "
                << "island_" << island_idx << "_nodes + " << island.signal_indices.size() << ");\n";
            oss << "        isl.elements.assign(island_" << island_idx << "_elements, "
                << "island_" << island_idx << "_elements + " << island.elements.size() << ");\n";
            oss << "        islands.push_back(std::move(isl));\n";
        }
        oss << "    }\n";
        oss << "};\n\n";

        oss << "struct ElectricalDebugEntry {\n";
        oss << "    uint32_t component_index;\n";
        oss << "    uint32_t island_index;\n";
        oss << "    uint32_t element_index;\n";
        oss << "    const char* device_name;\n";
        oss << "    const char* classname;\n";
        oss << "    const char* role;\n";
        oss << "    uint32_t node_a;\n";
        oss << "    uint32_t node_b;\n";
        oss << "};\n\n";
        oss << "constexpr ElectricalDebugEntry ELECTRICAL_DEBUG_MAP[] = {\n";
        for (const auto& dbg : electrical_plan.component_debug) {
            oss << "    { " << dbg.component_index << ", " << dbg.island_index << ", "
                << dbg.element_index << ", \"" << dbg.device_name
                << "\", \"" << dbg.device_classname << "\", \"" << dbg.role
                << "\", " << dbg.node_a << ", " << dbg.node_b << " },\n";
        }
        oss << "};\n";
        oss << "constexpr uint32_t ELECTRICAL_DEBUG_COUNT = "
            << electrical_plan.component_debug.size() << ";\n\n";

        // Compute max island sizes for scratch buffer pre-allocation
        uint32_t max_island_nodes = 0;
        uint32_t max_island_elements = 0;
        uint32_t max_component_index = 0;
        for (const auto& island : electrical_plan.islands) {
            max_island_nodes = std::max(max_island_nodes, (uint32_t)island.signal_indices.size());
            max_island_elements = std::max(max_island_elements, (uint32_t)island.elements.size());
            for (const auto& elem : island.elements) {
                max_component_index = std::max(max_component_index, elem.component_index);
            }
        }
        oss << "/// Pre-allocated scratch buffer sizes for electrical solve\n";
        oss << "constexpr uint32_t ELECTRICAL_MAX_ISLAND_NODES = " << max_island_nodes << ";\n";
        oss << "constexpr uint32_t ELECTRICAL_MAX_ISLAND_ELEMENTS = " << max_island_elements << ";\n";
        oss << "constexpr uint32_t ELECTRICAL_MAX_COMPONENT_INDEX = " << max_component_index << ";\n\n";
    } else {
        oss << "constexpr uint32_t ELECTRICAL_ISLAND_COUNT = 0;\n\n";
        oss << "constexpr uint32_t ELECTRICAL_MAX_ISLAND_NODES = 0;\n";
        oss << "constexpr uint32_t ELECTRICAL_MAX_ISLAND_ELEMENTS = 0;\n";
        oss << "constexpr uint32_t ELECTRICAL_MAX_COMPONENT_INDEX = 0;\n\n";
        oss << "struct ElectricalDebugEntry {\n";
        oss << "    uint32_t component_index;\n";
        oss << "    uint32_t island_index;\n";
        oss << "    uint32_t element_index;\n";
        oss << "    const char* device_name;\n";
        oss << "    const char* classname;\n";
        oss << "    const char* role;\n";
        oss << "    uint32_t node_a;\n";
        oss << "    uint32_t node_b;\n";
        oss << "};\n\n";
        oss << "constexpr ElectricalDebugEntry ELECTRICAL_DEBUG_MAP[] = {};\n";
        oss << "constexpr uint32_t ELECTRICAL_DEBUG_COUNT = 0;\n\n";
    }

    // Global simulation state pointer (set at init, available globally)
    oss << "/// Global simulation state pointer (set once, used by all components)\n";
    oss << "extern SimulationState* g_state;\n\n";

    // Systems class - ECS-like optimized
    oss << "// ==============================================================================\n";
    oss << "// SYSTEMS CLASS (ECS-like: direct field access, no virtual calls)\n";
    oss << "// Components are NON-VIRTUAL for AOT - no vtable overhead\n";
    oss << "// ==============================================================================\n\n";

    oss << "class " << class_name << " {\n";
    oss << "public:\n";

    // Device objects with AotProvider - compile-time constexpr port index lookup
    // Zero-cost abstraction: provider.get(PortNames::v_in) compiles to a constant
    for (const auto& dev : devices) {
        std::string aot_type = generate_aot_provider_type(dev, port_to_signal, signal_count);
        oss << "    " << dev.classname << "<" << aot_type << "> " << sanitize_name(dev.name) << ";\n";
    }
    oss << "\n";

    // Port indices as flat arrays (DATA-ORIENTED: cache-friendly, no indirection)
    oss << "    // Port indices - stored separately for direct access (data-oriented)\n";
    oss << "    // This allows O(1) access without loading from object fields\n";
    for (const auto& dev : devices) {
        for (const auto& port : dev.ports) {
            const std::string& port_name = port.first;
            if (port.second.alias.has_value() && !port.second.alias.value().empty()) {
                continue;  // Skip alias ports
            }
            std::string port_key = dev.name + "." + port_name;
            uint32_t sig = port_to_signal.count(port_key) ? port_to_signal.at(port_key) : signal_count;
            oss << "    static constexpr uint32_t " << sanitize_name(dev.name) << "_" << port_name << "_idx = " << sig << ";\n";
        }
    }
    oss << "\n";

    // Global simulation step counter (not modulo cycle index)
    oss << "    uint32_t step_counter_ = 0;\n\n";

    // Electrical plan and runtime state (for AOT solve_electrical)
    if (!electrical_plan.islands.empty()) {
        oss << "    ElectricalBuildPlan electrical_plan_;\n";
        oss << "    ElectricalRuntimeState electrical_rt_;\n";
        oss << "    static constexpr float ELECTRICAL_DIAG_RESIDUAL_WARN = 1e-4f;\n";
        oss << "    static constexpr uint32_t ELECTRICAL_COUNTER_LOG_PERIOD = 600;\n";
        oss << "\n";
        oss << "    struct ElectricalBindings {\n";
        for (const auto& binding : electrical_plan.device_bindings) {
            oss << "        static constexpr uint32_t " << binding.device_field_name
                << "_island = " << binding.island_index << ";\n";
            oss << "        static constexpr uint32_t " << binding.device_field_name
                << "_element = " << binding.element_index << ";\n";
            oss << "        static constexpr uint32_t " << binding.device_field_name
                << "_component = " << binding.component_index << ";\n";
        }
        oss << "    };\n";

        oss << "\n";
        oss << "    static void dump_island_debug(uint32_t island_idx);\n";
    }
    oss << "\n";

    // Constructor / Destructor
    oss << "    " << class_name << "();\n";
    oss << "    ~" << class_name << "();\n\n";

    // Non-copyable (owns raw pointer)
    oss << "    " << class_name << "(const " << class_name << "&) = delete;\n";
    oss << "    " << class_name << "& operator=(const " << class_name << "&) = delete;\n\n";

    // Methods - all inline for optimization
    oss << "    /// Pre-load initialization\n";
    oss << "    void pre_load();\n\n";

    oss << "    /// Main solve step with jump table dispatch (ECS-like)\n";
    oss << "    void solve_step(void* state, uint32_t step, double dt);\n\n";

    // Generate CYCLE_LENGTH step methods
    for (int step = 0; step < 60; ++step) {
        oss << "    AOT_INLINE void step_" << step << "(void* state, double dt);\n";
    }
    oss << "\n";

    oss << "    /// Convergence check (sparse sampling)\n";
    oss << "    AOT_INLINE bool check_convergence(void* state, float tolerance) const;\n\n";

    oss << "    uint32_t component_count() const { return " << devices.size() << "; }\n";

    oss << "};\n\n";

    return oss.str();
}

std::string CodeGen::generate_source(
    const std::string& header_name,
    const std::vector<DeviceInstance>& devices_unfiltered,
    const std::vector<Connection>& connections,
    const std::unordered_map<std::string, uint32_t>& port_to_signal,
    uint32_t signal_count,
    const std::string& class_name,
    const ElectricalPlanCodegen& electrical_plan
) {
    // Filter out visual-only devices (no simulation behavior, e.g. Group)
    std::vector<DeviceInstance> devices;
    devices.reserve(devices_unfiltered.size());
    for (const auto& d : devices_unfiltered)
        if (!d.visual_only) devices.push_back(d);

    std::ostringstream oss;

    oss << "#include \"" << header_name << "\"\n";
    // Include template definitions from all.cpp so compiler can instantiate AotProvider versions
    oss << "#include \"jit_solver/components/all.cpp\"\n";
    // Electrical subsolver for AOT island solve
    oss << "#include \"jit_solver/subsolvers/electrical_subsolver.h\"\n";
    oss << "#include <spdlog/spdlog.h>\n";
    oss << "#include <cstring>  // memcpy\n\n";
    // Enable fast-math for generated code only (not spdlog)
    oss << "#ifdef __GNUC__\n";
    oss << "#pragma GCC optimize(\"fast-math,unroll-loops\")\n";
    oss << "#endif\n\n";

    // Explicit template instantiations for AotProvider
    // These tell the compiler to generate code for Component<AotProvider<Bindings...>>
    oss << "// Explicit template instantiations for AOT\n";
    for (const auto& dev : devices) {
        std::string aot_type = generate_aot_provider_type(dev, port_to_signal, signal_count);
        oss << "template class " << dev.classname << "<" << aot_type << ">;\n";
    }
    oss << "\n";

    // Constructor - initialize component parameters (port indices are compile-time constants)
    oss << class_name << "::" << class_name << "()\n";
    oss << "{\n";

    // Port indices are now static constexpr - no runtime initialization needed!

    // Collect LUT tables for arena generation
    struct LutEntry { std::string dev_name; std::vector<float> keys; std::vector<float> values; };
    std::vector<LutEntry> lut_entries;
    uint32_t lut_arena_offset = 0;

    // Generate parameter assignments
    for (const auto& dev : devices) {
        // LUT: parse table param into arena, emit offset/size instead
        if (dev.classname == "LUT") {
            auto it = dev.params.find("table");
            if (it != dev.params.end()) {
                LutEntry entry;
                entry.dev_name = sanitize_name(dev.name);
                // Inline parse (same format as LUT::parse_table)
                std::string tbl = it->second;
                size_t pos = 0;
                while (pos < tbl.size()) {
                    while (pos < tbl.size() && (tbl[pos] == ' ' || tbl[pos] == ';')) ++pos;
                    if (pos >= tbl.size()) break;
                    size_t colon = tbl.find(':', pos);
                    if (colon == std::string::npos) break;
                    size_t end = tbl.find(';', colon + 1);
                    if (end == std::string::npos) end = tbl.size();
                    float key_f, val_f;
                    if (locale_safe::parse_float(tbl.substr(pos, colon - pos), key_f) &&
                        locale_safe::parse_float(tbl.substr(colon + 1, end - colon - 1), val_f)) {
                        entry.keys.push_back(key_f);
                        entry.values.push_back(val_f);
                    } else { break; }
                    pos = end;
                }
                oss << "    " << entry.dev_name << ".table_offset = " << lut_arena_offset << ";\n";
                oss << "    " << entry.dev_name << ".table_size = " << entry.keys.size() << ";\n";
                lut_arena_offset += static_cast<uint32_t>(entry.keys.size());
                lut_entries.push_back(std::move(entry));
            }
            continue;  // skip generic param loop for LUT
        }

        for (const auto& param : dev.params) {
            const std::string& param_name = param.first;
            const std::string& value = param.second;

            // Skip internal computed fields
            if (param_name == "inv_internal_r" || param_name == "inv_capacity") continue;

            std::string type = infer_type(value);
            oss << "    " << sanitize_name(dev.name) << "." << param_name << " = " << format_value(value, type) << ";\n";
        }
    }

    // Initialize electrical plan and pre-allocate scratch buffers
    if (!electrical_plan.islands.empty()) {
        oss << "    { AotElectricalPlan aot_plan;\n";
        oss << "      electrical_plan_.islands = std::move(aot_plan.islands); }\n";
        oss << "    electrical_rt_.reserve(ELECTRICAL_MAX_ISLAND_NODES, "
            << "ELECTRICAL_MAX_ISLAND_ELEMENTS, ELECTRICAL_MAX_COMPONENT_INDEX);\n";
        for (const auto& binding : electrical_plan.device_bindings) {
            oss << "    " << binding.device_field_name << ".electrical_handle.island_index = "
                << "ElectricalBindings::" << binding.device_field_name << "_island;\n";
            oss << "    " << binding.device_field_name << ".electrical_handle.element_index = "
                << "ElectricalBindings::" << binding.device_field_name << "_element;\n";
            oss << "    " << binding.device_field_name << ".electrical_handle.component_index = "
                << "ElectricalBindings::" << binding.device_field_name << "_component;\n";
        }
    }
    oss << "}\n\n";

    // Destructor
    oss << class_name << "::~" << class_name << "() {}\n\n";

    // Pre-load: call pre_load() on components that have it, then LUT arena init
    oss << "void " << class_name << "::pre_load() {\n";
    // All cpp_class components have pre_load() (empty stub or real implementation)
    for (const auto& dev : devices) {
        oss << "    " << sanitize_name(dev.name) << ".pre_load();\n";
    }
    // Emit LUT arena initialization
    if (!lut_entries.empty()) {
        oss << "    // LUT arena: all breakpoint tables concatenated (" << lut_arena_offset << " floats total)\n";
        oss << "    static const float lut_keys_data[] = {";
        bool first_k = true;
        for (const auto& e : lut_entries) {
            for (float k : e.keys) {
                if (!first_k) oss << ", ";
                oss << locale_safe::format_float(k) << "f";
                first_k = false;
            }
        }
        oss << "};\n";
        oss << "    static const float lut_vals_data[] = {";
        bool first_v = true;
        for (const auto& e : lut_entries) {
            for (float v : e.values) {
                if (!first_v) oss << ", ";
                oss << locale_safe::format_float(v) << "f";
                first_v = false;
            }
        }
        oss << "};\n";
        oss << "    g_state->lut_keys.assign(lut_keys_data, lut_keys_data + " << lut_arena_offset << ");\n";
        oss << "    g_state->lut_values.assign(lut_vals_data, lut_vals_data + " << lut_arena_offset << ");\n";
    }
    oss << "}\n\n";

    // Jump table dispatch - computed goto (GCC/Clang) or switch fallback (MSVC)
    oss << "void " << class_name << "::solve_step(void* state, uint32_t step, double dt) {\n";
    oss << "    if (dt <= 0.0) return;\n";
    oss << "\n";
    oss << "#ifndef _MSC_VER\n";
    oss << "    // Computed goto dispatch table (static const for one-time init)\n";
    oss << "    static const void* dispatch_table[" << 60 << "] = {\n";
    for (int i = 0; i < 60; ++i) {
        oss << "        &&step_" << i << (i < 60 - 1 ? ",\n" : "\n");
    }
    oss << "    };\n\n";
    oss << "    // Direct jump - no bounds check needed (step % " << 60 << " is always 0-" << 60 - 1 << ")\n";
    oss << "    goto *dispatch_table[step % " << 60 << "];\n\n";
    for (int i = 0; i < 60; ++i) {
        oss << "    step_" << i << ":\n";
        oss << "        step_" << i << "(state, dt);\n";
        oss << "        ++step_counter_;\n";
        oss << "        return;\n\n";
    }
    oss << "#else\n";
    oss << "    // MSVC fallback: switch-based dispatch\n";
    oss << "    switch (step % " << 60 << ") {\n";
    for (int i = 0; i < 60; ++i) {
        oss << "        case " << i << ": step_" << i << "(state, dt); ++step_counter_; return;\n";
    }
    oss << "    }\n";
    oss << "#endif\n";
    oss << "}\n\n";

    // Push model: single-pass per frame, sources/consumers already encoded in
    // component execute() behavior and device ordering generated from blueprint.
    for (int step = 0; step < 60; ++step) {
        oss << "AOT_INLINE void " << class_name << "::step_" << step << "(void* state, double dt) {\n";
        oss << "    auto* st = static_cast<SimulationState*>(state);\n";
        // Electrical solve: compute node voltages and branch currents before component execute
        if (!electrical_plan.islands.empty()) {
            oss << "    st->electrical_rt = &electrical_rt_;\n";
            oss << "    solve_electrical(electrical_plan_, *st, electrical_rt_, dt);\n";
            oss << "    if (step_counter_ > 0 && (step_counter_ % ELECTRICAL_COUNTER_LOG_PERIOD) == 0) {\n";
            oss << "        const auto& c = electrical_rt_.counters;\n";
            oss << "        spdlog::info(\"[aot-elec] solve counters: islands={} n0={} n1={} n2={} dense={} singular={}\",\n";
            oss << "            c.islands_total, c.solves_n0, c.solves_n1, c.solves_n2, c.solves_dense, c.singular_fallbacks);\n";
            oss << "    }\n";
            oss << "    for (const auto& diag : electrical_rt_.island_diagnostics) {\n";
            oss << "        if (!diag.solve_ok || diag.max_abs_kcl_residual > ELECTRICAL_DIAG_RESIDUAL_WARN) {\n";
            oss << "            spdlog::warn(\"[aot-elec] island={} solve_ok={} unknowns={} max_abs_kcl={} worst_signal={} worst_v={} worst_branch_comp={}\",\n";
            oss << "                diag.island_index, diag.solve_ok, diag.unknown_count, diag.max_abs_kcl_residual,\n";
            oss << "                diag.worst_node_signal, diag.worst_node_voltage, diag.worst_branch_component_index);\n";
            oss << "            for (uint32_t i = 0; i < ELECTRICAL_DEBUG_COUNT; ++i) {\n";
            oss << "                const auto& e = ELECTRICAL_DEBUG_MAP[i];\n";
            oss << "                if (e.component_index == diag.worst_branch_component_index) {\n";
            oss << "                    spdlog::warn(\"[aot-elec] branch component={} device={} class={} role={} nodes=({},{})\",\n";
            oss << "                        e.component_index, e.device_name, e.classname, e.role, e.node_a, e.node_b);\n";
            oss << "                    break;\n";
            oss << "                }\n";
            oss << "            }\n";
            oss << "            dump_island_debug(diag.island_index);\n";
            oss << "        }\n";
            oss << "    }\n";
        }
        for (const auto& dev : devices) {
            oss << "    " << sanitize_name(dev.name) << ".execute(*st, dt);\n";
        }
        // Commit pass: update internal state for all components.
        // Mirrors JIT Simulator::step() which calls scheduler commit + commit_solver_owned_devices.
        // Battery::commit() performs discharge; Switch/Relay/HoldButton/AZS delegate to commit_control().
        for (const auto& dev : devices) {
            oss << "    " << sanitize_name(dev.name) << ".commit(*st, dt);\n";
        }
        if (!electrical_plan.islands.empty()) {
            oss << "    st->electrical_rt = nullptr;\n";
        }
        oss << "}\n\n";
    }

    // Push model single-pass has no iterative convergence stage.
    oss << "AOT_INLINE bool " << class_name << "::check_convergence(void* state, float tolerance) const {\n";
    oss << "    (void)state;\n";
    oss << "    (void)tolerance;\n";
    oss << "    return true;\n";
    oss << "}\n\n";

    if (!electrical_plan.islands.empty()) {
        oss << "void " << class_name << "::dump_island_debug(uint32_t island_idx) {\n";
        oss << "    spdlog::warn(\"[aot-elec] dump island={} entries={}\", island_idx, ELECTRICAL_DEBUG_COUNT);\n";
        oss << "    for (uint32_t i = 0; i < ELECTRICAL_DEBUG_COUNT; ++i) {\n";
        oss << "        const auto& e = ELECTRICAL_DEBUG_MAP[i];\n";
        oss << "        if (e.island_index != island_idx) continue;\n";
        oss << "        spdlog::warn(\"[aot-elec]   elem={} comp={} device={} class={} role={} nodes=({},{})\",\n";
        oss << "            e.element_index, e.component_index, e.device_name, e.classname, e.role, e.node_a, e.node_b);\n";
        oss << "    }\n";
        oss << "}\n\n";
    }

    return oss.str();
}

void CodeGen::write_files(
    const std::string& out_dir,
    const std::string& source_file,
    const std::vector<DeviceInstance>& devices,
    const std::vector<Connection>& connections,
    const std::unordered_map<std::string, uint32_t>& port_to_signal,
    uint32_t signal_count,
    const ElectricalPlanCodegen& electrical_plan_arg
) {
    // Extract electrical plan if not provided
    ElectricalPlanCodegen electrical_plan = electrical_plan_arg;
    if (electrical_plan.islands.empty() && !devices.empty()) {
        electrical_plan = extract_electrical_plan(devices, port_to_signal);
    }

    // Generate header name from source file
    std::string base_name = source_file;
    size_t pos = base_name.find_last_of("/\\");
    if (pos != std::string::npos) {
        base_name = base_name.substr(pos + 1);
    }
    pos = base_name.find_last_of('.');
    if (pos != std::string::npos) {
        base_name = base_name.substr(0, pos);
    }
    std::string header_name = "generated_" + base_name + ".h";

    std::string header_path = out_dir + "/" + header_name;
    std::string source_name = "generated_" + base_name + ".cpp";
    std::string source_path = out_dir + "/" + source_name;

    std::cerr << "[codegen] Writing optimized ECS-like header to: " << header_path << "\n";
    std::cerr << "[codegen] Writing optimized ECS-like source to: " << source_path << "\n";

    // Generate header
    std::string header = generate_header(source_file, devices, connections, port_to_signal, signal_count, "Systems", electrical_plan);
    std::ofstream hfile(header_path);
    if (!hfile.is_open()) {
        std::cerr << "Failed to open: " << header_path << "\n";
        return;
    }
    hfile << header;
    hfile.close();

    // Generate source
    std::string source = generate_source(header_name, devices, connections, port_to_signal, signal_count, "Systems", electrical_plan);
    std::ofstream sfile(source_path);
    if (!sfile.is_open()) {
        std::cerr << "Failed to open: " << source_path << "\n";
        return;
    }
    sfile << source;
    sfile.close();

    std::cerr << "[codegen] Done! Generated ECS-like code with:\n";
    std::cerr << "[codegen]   - Jump table dispatch (" << 60 << " cases)\n";
    std::cerr << "[codegen]   - Domain scheduling (" << 60 << " step methods)\n";
    std::cerr << "[codegen]   - __restrict pointers (no aliasing)\n";
    std::cerr << "[codegen]   - AOT_INLINE + AOT_LIKELY/AOT_UNLIKELY\n";
    std::cerr << "[codegen]   - Push single-pass step execution\n";
    if (!electrical_plan.islands.empty()) {
        std::cerr << "[codegen]   - Electrical plan: " << electrical_plan.islands.size() << " island(s)\n";
    }
}

void CodeGen::generate_port_registry(const TypeRegistry& registry, const std::string& output_path) {
    std::cerr << "[codegen] Generating port registry from TypeRegistry (" << registry.types.size() << " types)\n";

    struct PortMeta {
        std::string name;
        PortDirection direction = PortDirection::Out;
        Domain domain = Domain::Electrical;
        bool source_writer = false;
    };

    struct ComponentPorts {
        std::string classname;
        std::vector<PortMeta> ports;
        bool scheduler_source = false;
    };

    std::vector<ComponentPorts> all_components;

    for (const auto& [name, def] : registry.types) {
        if (!def.cpp_class) continue;

        ComponentPorts comp;
        comp.classname = def.classname;
        comp.scheduler_source = def.scheduler_source;
        for (const auto& [port_name, port] : def.ports) {
            PortMeta meta;
            meta.name = port_name;
            meta.direction = port.direction;
            meta.domain = port.domain;
            meta.source_writer = port.source_writer;
            comp.ports.push_back(std::move(meta));
        }
        std::sort(comp.ports.begin(), comp.ports.end(),
            [](const PortMeta& a, const PortMeta& b) {
                return a.name < b.name;
            });
        all_components.push_back(std::move(comp));
    }

    // Sort components by classname
    std::sort(all_components.begin(), all_components.end(),
        [](const ComponentPorts& a, const ComponentPorts& b) {
            return a.classname < b.classname;
        });

    // Collect all unique port names for Param enum
    std::set<std::string> all_port_names;
    for (const auto& comp : all_components) {
        for (const auto& port : comp.ports) {
            all_port_names.insert(port.name);
        }
    }

    // Generate header file
    std::ostringstream oss;

    oss << "// Auto-generated by codegen from library/*.blueprint\n";
    oss << "// DO NOT EDIT - changes will be overwritten\n";
    oss << "// \n";
    oss << "// This file contains port definitions for all components.\n";
    oss << "// Port offsets are calculated to ensure C++ fields match JSON registry.\n";
    oss << "\n";
    oss << "#pragma once\n";
    oss << "\n";
    oss << "#include <cstdint>\n";
    oss << "#include <string>\n";
    oss << "#include <unordered_map>\n";
    oss << "#include <unordered_set>\n";
    oss << "#include <optional>\n";
    oss << "#include <vector>\n";
    oss << "#include <variant>\n";
    oss << "\n";
    // Include Provider pattern and component definitions
    // These are relative to port_registry.h location (src/jit_solver/components/)
    oss << "#include \"provider.h\"\n";
    oss << "#include \"all.h\"\n";
    oss << "\n";
    // PortNames enum is in port_names.h (included transitively via provider.h)
    // Separated to break circular dependency: component.h -> port_registry.h -> all.h -> component.h
    oss << "// PortNames enum is defined in port_names.h (included transitively via provider.h)\n";
    oss << "// Separated to break circular dependency: component.h → port_registry.h → all.h → component.h\n";
    oss << "#include \"port_names.h\"\n";
    oss << "\n";

    // Generate enum for component types
    oss << "// Component type enumeration\n";
    oss << "enum class ComponentType {\n";
    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "    " << all_components[i].classname << ",\n";
    }
    oss << "    _COUNT  // sentinel — must be last\n";
    oss << "};\n";
    oss << "\n";

    // Generate port count constants
    oss << "// Port count for each component\n";
    for (const auto& comp : all_components) {
        oss << "constexpr size_t " << comp.classname << "_PORT_COUNT = " << comp.ports.size() << ";\n";
    }
    oss << "\n";

    // Generate port name lists
    oss << "// Port names for each component (in field declaration order)\n";
    for (const auto& comp : all_components) {
        oss << "constexpr const char* " << comp.classname << "_PORTS[] = {\n";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "    \"" << comp.ports[i].name << "\"";
            if (i < comp.ports.size() - 1) oss << ",\n";
            else oss << "\n";
        }
        oss << "};\n";
    }
    oss << "\n";

    // Generate strict metadata arrays (direction/domain/source_writer/scheduler_source)
    oss << "enum class RegistryPortDirection : uint8_t { In = 0, Out = 1, InOut = 2 };\n\n";
    for (const auto& comp : all_components) {
        oss << "constexpr RegistryPortDirection " << comp.classname << "_PORT_DIRECTIONS[] = {\n";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            const char* dir_name = "Out";
            if (comp.ports[i].direction == PortDirection::In) dir_name = "In";
            else if (comp.ports[i].direction == PortDirection::InOut) dir_name = "InOut";
            oss << "    RegistryPortDirection::" << dir_name;
            if (i < comp.ports.size() - 1) oss << ",\n";
            else oss << "\n";
        }
        oss << "};\n";

        oss << "constexpr uint8_t " << comp.classname << "_PORT_DOMAINS[] = {\n";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "    " << static_cast<int>(static_cast<uint8_t>(comp.ports[i].domain));
            if (i < comp.ports.size() - 1) oss << ",\n";
            else oss << "\n";
        }
        oss << "};\n";

        oss << "constexpr bool " << comp.classname << "_PORT_SOURCE_WRITER[] = {\n";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "    " << (comp.ports[i].source_writer ? "true" : "false");
            if (i < comp.ports.size() - 1) oss << ",\n";
            else oss << "\n";
        }
        oss << "};\n";

        oss << "constexpr bool " << comp.classname << "_SCHEDULER_SOURCE = "
            << (comp.scheduler_source ? "true" : "false") << ";\n\n";
    }

    // Generate helper function to get ports by classname
    oss << "// Get port names for a component type\n";

    // Generate string_to_port_name lookup (auto-generated, never hand-maintain!)
    oss << "// Convert port name string to PortNames enum\n";
    oss << "// Auto-generated from components/*.blueprint — never maintain by hand!\n";
    oss << "inline std::optional<PortNames> string_to_port_name(const std::string& name) {\n";
    oss << "    static const std::unordered_map<std::string, PortNames> map = {\n";
    for (const auto& port_name : all_port_names) {
        oss << "        {\"" << port_name << "\", PortNames::" << port_name << "},\n";
    }
    oss << "    };\n";
    oss << "    auto it = map.find(name);\n";
    oss << "    if (it != map.end()) return it->second;\n";
    oss << "    return std::nullopt;\n";
    oss << "}\n\n";

    oss << "// Get port names for a component type\n";
    oss << "inline std::vector<std::string> get_component_ports(const std::string& classname) {\n";
    oss << "    static const std::unordered_map<std::string, std::vector<std::string>> registry = {\n";
    for (const auto& comp : all_components) {
        oss << "        {\"" << comp.classname << "\", {";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "\"" << comp.ports[i].name << "\"";
            if (i < comp.ports.size() - 1) oss << ", ";
        }
        oss << "}},\n";
    }
    oss << "    };\n";
    oss << "\n";
    oss << "    auto it = registry.find(classname);\n";
    oss << "    if (it != registry.end()) {\n";
    oss << "        return it->second;\n";
    oss << "    }\n";
    oss << "    return {};\n";
    oss << "}\n";
    oss << "\n";

    oss << "inline bool has_component_metadata(const std::string& classname) {\n";
    oss << "    static const std::unordered_set<std::string> known = {\n";
    for (const auto& comp : all_components) {
        oss << "        \"" << comp.classname << "\",\n";
    }
    oss << "    };\n";
    oss << "    return known.count(classname) > 0;\n";
    oss << "}\n\n";

    oss << "inline bool is_scheduler_source_component(const std::string& classname) {\n";
    oss << "    static const std::unordered_map<std::string, bool> registry = {\n";
    for (const auto& comp : all_components) {
        oss << "        {\"" << comp.classname << "\", " << (comp.scheduler_source ? "true" : "false") << "},\n";
    }
    oss << "    };\n";
    oss << "    auto it = registry.find(classname);\n";
    oss << "    if (it == registry.end()) return false;\n";
    oss << "    return it->second;\n";
    oss << "}\n\n";

    oss << "inline std::vector<std::string> get_output_ports(const std::string& classname) {\n";
    oss << "    std::vector<std::string> result;\n";
    for (const auto& comp : all_components) {
        oss << "    if (classname == \"" << comp.classname << "\") {\n";
        oss << "        for (size_t i = 0; i < " << comp.classname << "_PORT_COUNT; ++i) {\n";
        oss << "            if (" << comp.classname << "_PORT_DIRECTIONS[i] == RegistryPortDirection::Out || "
            << comp.classname << "_PORT_DIRECTIONS[i] == RegistryPortDirection::InOut) {\n";
        oss << "                result.push_back(" << comp.classname << "_PORTS[i]);\n";
        oss << "            }\n";
        oss << "        }\n";
        oss << "        return result;\n";
        oss << "    }\n";
    }
    oss << "    return result;\n";
    oss << "}\n\n";

    oss << "inline std::vector<std::string> get_source_writer_ports(const std::string& classname, uint8_t domain_mask) {\n";
    oss << "    std::vector<std::string> result;\n";
    for (const auto& comp : all_components) {
        oss << "    if (classname == \"" << comp.classname << "\") {\n";
        oss << "        for (size_t i = 0; i < " << comp.classname << "_PORT_COUNT; ++i) {\n";
        oss << "            if (" << comp.classname << "_PORT_SOURCE_WRITER[i] && ((" << comp.classname << "_PORT_DOMAINS[i] & domain_mask) != 0)) {\n";
        oss << "                result.push_back(" << comp.classname << "_PORTS[i]);\n";
        oss << "            }\n";
        oss << "        }\n";
        oss << "        return result;\n";
        oss << "    }\n";
    }
    oss << "    return result;\n";
    oss << "}\n\n";

    // Generate ComponentVariant for dynamic component containers (Editor JIT)
    oss << "// Component variant for dynamic component storage (Editor JIT mode)\n";
    oss << "// Enables type-safe storage of any component type without virtual calls\n";
    oss << "using ComponentVariant = std::variant<\n";
    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "    " << all_components[i].classname << "<JitProvider>";
        if (i < all_components.size() - 1) oss << ",\n";
        else oss << "\n";
    }
    oss << ">;\n\n";

    // Compile-time guard: ComponentType enum and ComponentVariant must stay in sync
    oss << "// Compile-time guard: ComponentType and ComponentVariant must stay in sync\n";
    oss << "static_assert(\n";
    oss << "    std::variant_size_v<ComponentVariant> == static_cast<size_t>(ComponentType::_COUNT),\n";
    oss << "    \"ComponentType enum and ComponentVariant are out of sync — regenerate port_registry.h\"\n";
    oss << ");\n\n";

    // Write to file
    std::ofstream out(output_path);
    if (!out.is_open()) {
        std::cerr << "[codegen] Error: could not write to " << output_path << "\n";
        return;
    }

    out << oss.str();
    out.close();

    std::cerr << "[codegen] Generated port registry: " << output_path << "\n";
    std::cerr << "[codegen]   - " << all_components.size() << " components\n";

    // Generate port_names.h alongside port_registry.h
    // This lightweight header breaks the circular dependency:
    //   component.h → port_registry.h → all.h → component.h
    {
        // Derive port_names.h path from port_registry.h path
        std::string dir = output_path;
        auto slash = dir.find_last_of("/\\");
        if (slash != std::string::npos) {
            dir = dir.substr(0, slash + 1);
        } else {
            dir = "";
        }
        std::string port_names_path = dir + "port_names.h";

        std::ostringstream pn;
        pn << "// Auto-generated by codegen from library/*.blueprint\n";
        pn << "// DO NOT EDIT - changes will be overwritten\n";
        pn << "//\n";
        pn << "// Lightweight header containing only the PortNames enum.\n";
        pn << "// Split from port_registry.h to avoid circular includes:\n";
        pn << "//   component.h → port_registry.h → all.h → component.h\n";
        pn << "// This file has NO dependency on component headers.\n";
        pn << "\n";
        pn << "#pragma once\n";
        pn << "\n";
        pn << "#include <cstdint>\n";
        pn << "\n";
        pn << "// Port names enum (for constexpr Provider pattern)\n";
        pn << "// Used by AOT components to get compile-time port indices\n";
        pn << "enum class PortNames : uint32_t {\n";
        size_t pn_idx = 0;
        for (const auto& port_name : all_port_names) {
            pn << "    " << port_name;
            pn << ",\n";
            pn_idx++;
        }
        pn << "    _COUNT  // Sentinel: must always be last. Used to size flat arrays indexed by PortNames.\n";
        pn << "};\n";

        std::ofstream pn_out(port_names_path);
        if (pn_out.is_open()) {
            pn_out << pn.str();
            pn_out.close();
            std::cerr << "[codegen] Generated port names: " << port_names_path << "\n";
        } else {
            std::cerr << "[codegen] Warning: could not write " << port_names_path << "\n";
        }
    }

    // Count total ports
    size_t total_ports = 0;
    for (const auto& comp : all_components) {
        total_ports += comp.ports.size();
    }
    std::cerr << "[codegen]   - " << total_ports << " total ports\n";
}

CompositeCodegenResult CodeGen::generate_composite_systems(
    const TypeDefinition& td,
    const TypeRegistry& registry)
{
    // 1. Expand sub-blueprint references into flat devices + connections
    std::set<std::string> loading_stack;
    auto expanded = expand_sub_blueprint_references(td, registry, loading_stack);

    // 2. Merge each device with its type definition (ports, params, domains)
    for (auto& dev : expanded.devices) {
        const auto* type_def = registry.get(dev.classname);
        if (type_def) {
            dev = merge_device_instance(dev, *type_def);
        }
    }

    // 3. Signal allocation (union-find) — same algorithm as build_systems_dev
    std::vector<std::string> all_ports;
    std::unordered_map<std::string, uint32_t> port_to_idx;

    for (const auto& dev : expanded.devices) {
        for (const auto& [port_name, port] : dev.ports) {
            std::string full_port = dev.name + "." + port_name;
            uint32_t idx = static_cast<uint32_t>(all_ports.size());
            all_ports.push_back(full_port);
            port_to_idx[full_port] = idx;
        }
    }

    // Union-Find
    std::vector<uint32_t> uf_parent(all_ports.size());
    std::vector<uint32_t> uf_rank(all_ports.size(), 0);
    for (uint32_t i = 0; i < all_ports.size(); ++i) uf_parent[i] = i;

    auto uf_find = [&](uint32_t x) -> uint32_t {
        while (uf_parent[x] != x) {
            uf_parent[x] = uf_parent[uf_parent[x]];
            x = uf_parent[x];
        }
        return x;
    };
    auto uf_unite = [&](uint32_t a, uint32_t b) {
        uint32_t ra = uf_find(a), rb = uf_find(b);
        if (ra == rb) return;
        if (uf_rank[ra] < uf_rank[rb]) std::swap(ra, rb);
        uf_parent[rb] = ra;
        if (uf_rank[ra] == uf_rank[rb]) uf_rank[ra]++;
    };

    // === PARITY GUARD: BlueprintInput/Output Bridge Union ===
    // INVARIANT: ext↔port union MUST match JIT solver's logic.
    // [CRITICAL] This code must remain in sync with jit_solver.cpp bridge unification.
    // - Both paths (JIT in jit_solver.cpp:271-289, AOT here) must unify .ext and .port identically.
    // - Parser rewrite ensures parent connections use :instance:port.ext format.
    // - Failure to mirror this will cause JIT/AOT divergence for composite blueprints.
    for (const auto& dev : expanded.devices) {
        if (dev.classname == "BlueprintInput" || dev.classname == "BlueprintOutput") {
            std::string ext_key  = dev.name + ".ext";
            std::string port_key = dev.name + ".port";
            auto it_ext  = port_to_idx.find(ext_key);
            auto it_port = port_to_idx.find(port_key);
            if (it_ext != port_to_idx.end() && it_port != port_to_idx.end()) {
                uf_unite(it_ext->second, it_port->second);
            }
        }
    }

    // Union connected ports
    for (const auto& conn : expanded.connections) {
        auto it_from = port_to_idx.find(conn.from);
        auto it_to = port_to_idx.find(conn.to);
        if (it_from != port_to_idx.end() && it_to != port_to_idx.end()) {
            uf_unite(it_from->second, it_to->second);
        }
    }

    // Union alias ports within same device
    for (const auto& dev : expanded.devices) {
        for (const auto& [port_name, port] : dev.ports) {
            if (port.alias.has_value() && !port.alias->empty()) {
                std::string full_port = dev.name + "." + port_name;
                std::string full_alias = dev.name + "." + *port.alias;
                auto it_port = port_to_idx.find(full_port);
                auto it_alias = port_to_idx.find(full_alias);
                if (it_port != port_to_idx.end() && it_alias != port_to_idx.end()) {
                    uf_unite(it_port->second, it_alias->second);
                }
            }
        }
    }

    // Map each port → root, then remap roots to sequential 0-based signal indices
    std::unordered_map<std::string, uint32_t> port_to_signal;
    for (const auto& port : all_ports) {
        port_to_signal[port] = uf_find(port_to_idx[port]);
    }

    std::map<uint32_t, uint32_t> root_to_signal;
    std::vector<uint32_t> unique_roots;
    for (const auto& [port, root] : port_to_signal) {
        unique_roots.push_back(root);
    }
    std::sort(unique_roots.begin(), unique_roots.end());
    unique_roots.erase(std::unique(unique_roots.begin(), unique_roots.end()), unique_roots.end());

    uint32_t next_signal = 0;
    for (uint32_t root : unique_roots) {
        root_to_signal[root] = next_signal++;
    }
    for (auto& [port, sig] : port_to_signal) {
        sig = root_to_signal[sig];
    }
    uint32_t signal_count = next_signal;

    // 4. Extract electrical island plan (for AOT solve_electrical)
    ElectricalPlanCodegen electrical_plan = extract_electrical_plan(expanded.devices, port_to_signal);

    // 5. Delegate to existing generate_header/generate_source
    std::string class_name = sanitize_name(td.classname) + "_Systems";
    std::string source_file = td.classname + ".blueprint";
    std::string header_name = "generated_" + sanitize_name(td.classname) + ".h";

    CompositeCodegenResult result;
    result.class_name = class_name;
    result.header = generate_header(source_file, expanded.devices, expanded.connections,
                                    port_to_signal, signal_count, class_name, electrical_plan);
    result.source = generate_source(header_name, expanded.devices, expanded.connections,
                                    port_to_signal, signal_count, class_name, electrical_plan);
    return result;
}

std::map<std::string, CompositeCodegenResult> CodeGen::generate_all_composites(
    const TypeRegistry& registry)
{
    std::map<std::string, CompositeCodegenResult> results;

    auto order = registry.get_composites_topo_sorted();

    for (const auto& name : order) {
        const auto* td = registry.get(name);
        if (td && !td->cpp_class) {
            results[name] = generate_composite_systems(*td, registry);
        }
    }

    return results;
}
