#include "codegen.h"
#include <fstream>
#include <sstream>
#include <iostream>
#include <algorithm>
#include <cctype>
#include <map>
#include <set>
#include <filesystem>

// Use nlohmann::json - will be available when linked with json_parser
// This is a simple inline JSON parser for port registry generation
#include <nlohmann/json.hpp>

namespace an24 {

namespace {

std::string to_upper(const std::string& s) {
    std::string result = s;
    for (char& c : result) c = std::toupper(c);
    return result;
}

std::string sanitize_name(const std::string& s) {
    std::string result;
    for (char c : s) {
        if (c == '.' || c == '-' || c == ':') result += '_';
        else result += c;
    }
    return result;
}

// Infer C++ type from parameter value
std::string infer_type(const std::string& value) {
    if (value.empty()) return "float";

    try {
        size_t pos;
        long long ival = std::stoll(value, &pos);
        if (pos == value.size()) {
            if (ival > INT32_MAX || ival < INT32_MIN) return "int64_t";
            return "int32_t";
        }
    } catch (...) {}

    try {
        size_t pos;
        float fval = std::stof(value, &pos);
        if (pos == value.size()) {
            return "float";
        }
    } catch (...) {}

    if (value == "true" || value == "false") return "bool";

    return "std::string";
}

// Format value for C++ code
std::string format_value(const std::string& value, const std::string& type) {
    if (type == "float") {
        try {
            float f = std::stof(value);
            std::ostringstream oss;
            oss << f;
            return oss.str();
        } catch (...) {
            std::string v = value;
            if (v.find('.') == std::string::npos) {
                v += ".0";
            }
            return v;
        }
    } else if (type == "bool") {
        return value;
    } else if (type == "int32_t" || type == "int64_t") {
        return value;
    } else if (type == "std::string") {
        return "std::string(\"" + value + "\")";
    } else {
        return "\"" + value + "\"";
    }
}

// Get domain from device
std::string get_device_domain(const DeviceInstance& dev) {
    auto it = dev.params.find("domain");
    if (it != dev.params.end()) {
        return it->second;
    }
    return "Electrical";  // default
}

// Check if device has specific domain
bool has_domain(const DeviceInstance& dev, const std::string& domain) {
    std::string dev_domain = get_device_domain(dev);
    return dev_domain.find(domain) != std::string::npos;
}

// Generate AotProvider<Binding<...>, ...> type string for a device
std::string generate_aot_provider_type(
    const DeviceInstance& dev,
    const std::unordered_map<std::string, uint32_t>& port_to_signal,
    uint32_t signal_count
) {
    std::ostringstream oss;
    oss << "AotProvider<";
    bool first = true;
    for (const auto& port : dev.ports) {
        const std::string& port_name = port.first;
        if (port.second.alias.has_value() && !port.second.alias.value().empty()) {
            continue;
        }
        std::string port_key = dev.name + "." + port_name;
        uint32_t sig = port_to_signal.count(port_key) ? port_to_signal.at(port_key) : signal_count;
        if (!first) oss << ", ";
        oss << "Binding<PortNames::" << port_name << ", " << sig << ">";
        first = false;
    }
    oss << ">";
    return oss.str();
}

// Get port name from device port definitions - NO FALLBACKS, fail hard
std::string get_port_name(const std::unordered_map<std::string, Port>& ports, const std::string& required_port) {
    if (ports.count(required_port)) {
        return required_port;
    }

    // Build error message listing available ports
    std::string available = "{";
    for (const auto& [name, port] : ports) {
        available += name + " ";
    }
    available += "}";

    throw std::runtime_error("_codegen error: required port '" + required_port + "' not found. Available ports: " + available);
}

} // anonymous namespace

std::string CodeGen::generate_header(
    const std::string& source_file,
    const std::vector<DeviceInstance>& devices,
    const std::vector<Connection>& connections,
    const std::unordered_map<std::string, uint32_t>& port_to_signal,
    uint32_t signal_count
) {
    std::ostringstream oss;

    // Header guard
    std::string guard = "GENERATED_" + sanitize_name(source_file);
    std::replace(guard.begin(), guard.end(), '/', '_');
    std::replace(guard.begin(), guard.end(), '\\', '_');
    guard += "_H";

    oss << "// Auto-generated by codegen from " << source_file << "\n";
    oss << "// DO NOT EDIT - this will be overwritten on next build\n";
    oss << "// ECS-like optimized: jump table, __restrict, no aliasing\n\n";

    oss << "#pragma once\n\n";
    oss << "#include <cstdint>\n";
    oss << "#include <string>\n";
    oss << "#include <array>\n";
    oss << "#include <vector>\n";
    oss << "#include <cmath>\n";
    oss << "#include \"jit_solver/state.h\"\n";
    oss << "#include \"jit_solver/components/all.h\"\n";
    oss << "#include \"jit_solver/components/port_registry.h\"\n\n";
    oss << "// Compiler hints for optimization\n";
    oss << "#ifdef __GNUC__\n";
    oss << "#define AOT_INLINE __attribute__((always_inline)) inline\n";
    oss << "#define AOT_LIKELY(x) __builtin_expect(!!(x), 1)\n";
    oss << "#define AOT_UNLIKELY(x) __builtin_expect(!!(x), 0)\n";
    oss << "#else\n";
    oss << "#define AOT_INLINE inline\n";
    oss << "#define AOT_LIKELY(x) (x)\n";
    oss << "#define AOT_UNLIKELY(x) (x)\n";
    oss << "#endif\n\n";
    oss << "namespace an24 {\n\n";

    // Signal constants
    oss << "// ==============================================================================\n";
    oss << "// SIGNAL INDICES (ECS-like: direct array access, no lookups)\n";
    oss << "// ==============================================================================\n\n";

    for (const auto& [port, sig] : port_to_signal) {
        std::string const_name = "SIG_" + sanitize_name(to_upper(port));
        oss << "constexpr uint32_t " << const_name << " = " << sig << ";\n";
    }
    oss << "\n";

    // Fixed signals
    oss << "/// Fixed signal indices (RefNode bus voltages)\n";
    oss << "constexpr uint32_t FIXED_SIGNALS[] = {";
    bool first = true;
    for (const auto& dev : devices) {
        if (dev.classname == "RefNode") {
            std::string port_key = dev.name + ".v_out";
            if (port_to_signal.count(port_key)) {
                if (!first) oss << ", ";
                oss << port_to_signal.at(port_key);
                first = false;
            } else {
                port_key = dev.name + ".v";
                if (port_to_signal.count(port_key)) {
                    if (!first) oss << ", ";
                    oss << port_to_signal.at(port_key);
                    first = false;
                }
            }
        }
    }
    oss << "};\n\n";

    // Signal count
    oss << "/// Total number of unique signals (for memory allocation)\n";
    oss << "constexpr uint32_t SIGNAL_COUNT = " << signal_count << ";\n\n";

    // Device count
    oss << "/// Number of devices in this system\n";
    oss << "constexpr uint32_t DEVICE_COUNT = " << devices.size() << ";\n\n";

    // Global simulation state pointer (set at init, available globally)
    oss << "/// Global simulation state pointer (set once, used by all components)\n";
    oss << "extern SimulationState* g_state;\n\n";

    // Systems class - ECS-like optimized
    oss << "// ==============================================================================\n";
    oss << "// SYSTEMS CLASS (ECS-like: direct field access, no virtual calls)\n";
    oss << "// Components are NON-VIRTUAL for AOT - no vtable overhead\n";
    oss << "// ==============================================================================\n\n";

    oss << "class Systems {\n";
    oss << "public:\n";

    // Device objects with AotProvider - compile-time constexpr port index lookup
    // Zero-cost abstraction: provider.get(PortNames::v_in) compiles to a constant
    for (const auto& dev : devices) {
        std::string aot_type = generate_aot_provider_type(dev, port_to_signal, signal_count);
        oss << "    " << dev.classname << "<" << aot_type << "> " << dev.name << ";\n";
    }
    oss << "\n";

    // Port indices as flat arrays (DATA-ORIENTED: cache-friendly, no indirection)
    oss << "    // Port indices - stored separately for direct access (data-oriented)\n";
    oss << "    // This allows O(1) access without loading from object fields\n";
    for (const auto& dev : devices) {
        for (const auto& port : dev.ports) {
            const std::string& port_name = port.first;
            if (port.second.alias.has_value() && !port.second.alias.value().empty()) {
                continue;  // Skip alias ports
            }
            std::string port_key = dev.name + "." + port_name;
            uint32_t sig = port_to_signal.count(port_key) ? port_to_signal.at(port_key) : signal_count;
            oss << "    static constexpr uint32_t " << dev.name << "_" << port_name << "_idx = " << sig << ";\n";
        }
    }
    oss << "\n";

    // Pre-allocated convergence buffer pointer (set at init)
    oss << "    float* convergence_buffer = nullptr;\n\n";

    // Constructor
    oss << "    Systems();\n\n";

    // Methods - all inline for optimization
    oss << "    /// Pre-load initialization\n";
    oss << "    void pre_load();\n\n";

    oss << "    /// Main solve step with jump table dispatch (ECS-like)\n";
    oss << "    void solve_step(void* state, uint32_t step, float dt);\n\n";

    // Generate 60 step methods
    for (int step = 0; step < 60; ++step) {
        oss << "    AOT_INLINE void step_" << step << "(void* state, float dt);\n";
    }
    oss << "\n";

    // Balance methods - domain-specific for AOT optimization
    oss << "    /// Balance electrical domain (AOT-optimized, __restrict)\n";
    oss << "    AOT_INLINE void balance_electrical(void* state, float omega);\n\n";

    oss << "    /// Convergence check (sparse sampling)\n";
    oss << "    AOT_INLINE bool check_convergence(void* state, float tolerance) const;\n\n";

    oss << "    uint32_t component_count() const { return " << devices.size() << "; }\n";

    oss << "};\n\n";

    oss << "} // namespace an24\n";

    return oss.str();
}

std::string CodeGen::generate_source(
    const std::string& header_name,
    const std::vector<DeviceInstance>& devices,
    const std::vector<Connection>& connections,
    const std::unordered_map<std::string, uint32_t>& port_to_signal,
    uint32_t signal_count
) {
    std::ostringstream oss;

    oss << "#include \"" << header_name << "\"\n";
    // Include template definitions from all.cpp so compiler can instantiate AotProvider versions
    oss << "#include \"jit_solver/components/all.cpp\"\n";
    oss << "#include <cstring>  // memcpy\n\n";
    oss << "namespace an24 {\n\n";

    // Explicit template instantiations for AotProvider
    // These tell the compiler to generate code for Component<AotProvider<Bindings...>>
    oss << "// Explicit template instantiations for AOT\n";
    for (const auto& dev : devices) {
        std::string aot_type = generate_aot_provider_type(dev, port_to_signal, signal_count);
        oss << "template class " << dev.classname << "<" << aot_type << ">;\n";
    }
    oss << "\n";

    // Constructor - only initialize component parameters (port indices are compile-time constants)
    oss << "Systems::Systems()\n";
    oss << "{\n";
    oss << "    // Pre-allocate convergence buffer (zero-allocation in hot path)\n";
    oss << "    alignas(64) static float buf[SIGNAL_COUNT];\n";
    oss << "    convergence_buffer = buf;\n\n";

    // Port indices are now static constexpr - no runtime initialization needed!

    // Generate parameter assignments
    for (const auto& dev : devices) {
        for (const auto& param : dev.params) {
            const std::string& param_name = param.first;
            const std::string& value = param.second;

            // Skip internal computed fields
            if (param_name == "inv_internal_r" || param_name == "inv_capacity") continue;

            std::string type = infer_type(value);
            oss << "    " << dev.name << "." << param_name << " = " << format_value(value, type) << ";\n";
        }
    }
    oss << "}\n\n";

    // Pre-load
    oss << "void Systems::pre_load() {\n";
    for (const auto& dev : devices) {
        if (dev.classname == "Battery") {
            if (dev.params.count("internal_r")) {
                oss << "    " << dev.name << ".inv_internal_r = 1.0f / " << dev.name << ".internal_r;\n";
            }
        }
    }
    oss << "}\n\n";

    // Jump table dispatch - COMPUTED GOTO (faster than switch, branchless)
    // Uses GCC/Clang labels-as-values extension
    oss << "void Systems::solve_step(void* state, uint32_t step, float dt) {\n";
    oss << "    // Computed goto dispatch table (static const for one-time init)\n";
    oss << "    static const void* dispatch_table[60] = {\n";
    for (int i = 0; i < 60; ++i) {
        oss << "        &&step_" << i << (i < 59 ? ",\n" : "\n");
    }
    oss << "    };\n\n";
    oss << "    // Direct jump - no bounds check needed (step % 60 is always 0-59)\n";
    oss << "    goto *dispatch_table[step % 60];\n\n";
    for (int i = 0; i < 60; ++i) {
        oss << "    step_" << i << ":\n";
        oss << "        step_" << i << "(state, dt);\n";
        oss << "        return;\n\n";
    }
    oss << "}\n\n";

    // Generate 60 step methods with domain scheduling
    // Group devices by domain and step
    std::map<std::pair<int, std::string>, std::vector<std::string>> step_devices;

    for (const auto& dev : devices) {
        std::string domain = get_device_domain(dev);

        // Electrical: every step (0, 1, 2, ...)
        if (domain.find("Electrical") != std::string::npos) {
            for (int step = 0; step < 60; ++step) {
                step_devices[{step, "electrical"}].push_back(dev.name);
            }
        }

        // Mechanical: step (0, 3, 6, ...)
        if (domain.find("Mechanical") != std::string::npos) {
            for (int step = 0; step < 60; step += 3) {
                step_devices[{step, "mechanical"}].push_back(dev.name);
            }
        }

        // Hydraulic: every 12th step (0, 12, 24, ...)
        if (domain.find("Hydraulic") != std::string::npos) {
            for (int step = 0; step < 60; step += 12) {
                step_devices[{step, "hydraulic"}].push_back(dev.name);
            }
        }

        // Thermal: every 60th step (only step 0)
        if (domain.find("Thermal") != std::string::npos) {
            step_devices[{0, "thermal"}].push_back(dev.name);
        }

        // Logical: every step (0, 1, 2, ...) - 60Hz boolean logic
        if (domain.find("Logical") != std::string::npos) {
            for (int step = 0; step < 60; ++step) {
                step_devices[{step, "logical"}].push_back(dev.name);
            }
        }
    }

    // Generate each step method
    for (int step = 0; step < 60; ++step) {
        oss << "AOT_INLINE void Systems::step_" << step << "(void* state, float dt) {\n";
        oss << "    auto* st = static_cast<SimulationState*>(state);\n";

        // Electrical (every step) - DATA-ORIENTED: direct index access
        auto elec_it = step_devices.find({step, "electrical"});
        if (elec_it != step_devices.end()) {
            for (const auto& dev_name : elec_it->second) {
                // Find device
                auto dev_it = std::find_if(devices.begin(), devices.end(),
                    [&dev_name](const DeviceInstance& d) { return d.name == dev_name; });
                if (dev_it == devices.end()) continue;

                // Call component method (compiler will inline with -O3 -ffast-math)
                // Bus/RefNode are no-ops, others have solve_electrical()
                if (dev_it->classname == "Bus" || dev_it->classname == "RefNode" || dev_it->classname == "Voltmeter") {
                    oss << "    // " << dev_name << " (no-op)\n";
                } else {
                    oss << "    " << dev_name << ".solve_electrical(*st, dt);\n";
                }
            }
        }

        // Logical (every step) - boolean logic operations
        auto log_it = step_devices.find({step, "logical"});
        if (log_it != step_devices.end()) {
            for (const auto& dev_name : log_it->second) {
                // Find device
                auto dev_it = std::find_if(devices.begin(), devices.end(),
                    [&dev_name](const DeviceInstance& d) { return d.name == dev_name; });
                if (dev_it == devices.end()) continue;

                // Call component method (compiler will inline with -O3)
                oss << "    " << dev_name << ".solve_logical(*st, dt);\n";
            }
        }

        // Mechanical (every 3rd)
        if (step % 3 == 0) {
            auto mech_it = step_devices.find({step, "mechanical"});
            if (mech_it != step_devices.end()) {
                for (const auto& dev_name : mech_it->second) {
                    oss << "    " << dev_name << ".solve_mechanical(*st, dt * 3.0f);\n";
                }
            }
        }

        // Hydraulic (every 12th)
        if (step % 12 == 0) {
            auto hyd_it = step_devices.find({step, "hydraulic"});
            if (hyd_it != step_devices.end()) {
                for (const auto& dev_name : hyd_it->second) {
                    oss << "    " << dev_name << ".solve_hydraulic(*st, dt * 12.0f);\n";
                }
            }
        }

        // Thermal (step 0 only)
        if (step == 0) {
            auto therm_it = step_devices.find({step, "thermal"});
            if (therm_it != step_devices.end()) {
                for (const auto& dev_name : therm_it->second) {
                    oss << "    " << dev_name << ".solve_thermal(*st, dt * 60.0f);\n";
                }
            }
        }

        oss << "}\n\n";
    }

    // Balance electrical - FAST MATH version (no divisions, uses inv_omega = 1/omega)
    // For WASM: this is critical - div is expensive!
    oss << "AOT_INLINE void Systems::balance_electrical(void* state, float inv_omega) {\n";
    oss << "    auto* st = static_cast<SimulationState*>(state);\n";
    oss << "    // __restrict: no aliasing, enables SIMD\n";
    oss << "    float* __restrict acc = st->across.data();\n";
    oss << "    const float* __restrict thr = st->through.data();\n";
    oss << "    const float* __restrict inv_g = st->inv_conductance.data();\n";
    oss << "    const auto& types = st->signal_types;\n";
    oss << "    const uint32_t count = static_cast<uint32_t>(st->across.size());\n";
    oss << "\n";
    oss << "    for (uint32_t i = 0; i < count; ++i) {\n";
    oss << "        if (!types[i].is_fixed && inv_g[i] > 0.0f) {\n";
    oss << "            acc[i] += thr[i] * inv_g[i] * inv_omega;\n";
    oss << "        }\n";
    oss << "    }\n";
    oss << "}\n\n";

    // Convergence check - optimized with sparse sampling
    oss << "AOT_INLINE bool Systems::check_convergence(void* state, float tolerance) const {\n";
    oss << "    auto* st = static_cast<SimulationState*>(state);\n";
    oss << "    const float* __restrict across = st->across.data();\n";
    oss << "    const float* __restrict buf = convergence_buffer;\n";
    oss << "    const uint32_t count = st->dynamic_signals_count;\n";
    oss << "\n";
    oss << "    // Sparse check: every 4th signal - cache friendly\n";
    oss << "    for (uint32_t i = 0; i < count; i += 4) {\n";
    oss << "        float delta = std::abs(across[i] - buf[i]);\n";
    oss << "        if (AOT_UNLIKELY(delta > tolerance)) return false;\n";
    oss << "    }\n";
    oss << "    return true;\n";
    oss << "}\n\n";

    oss << "} // namespace an24\n";

    return oss.str();
}

void CodeGen::write_files(
    const std::string& out_dir,
    const std::string& source_file,
    const std::vector<DeviceInstance>& devices,
    const std::vector<Connection>& connections,
    const std::unordered_map<std::string, uint32_t>& port_to_signal,
    uint32_t signal_count
) {
    // Generate header name from source file
    std::string base_name = source_file;
    size_t pos = base_name.find_last_of("/\\");
    if (pos != std::string::npos) {
        base_name = base_name.substr(pos + 1);
    }
    pos = base_name.find_last_of('.');
    if (pos != std::string::npos) {
        base_name = base_name.substr(0, pos);
    }
    std::string header_name = "generated_" + base_name + ".h";

    std::string header_path = out_dir + "/" + header_name;
    std::string source_name = "generated_" + base_name + ".cpp";
    std::string source_path = out_dir + "/" + source_name;

    std::cerr << "[codegen] Writing optimized ECS-like header to: " << header_path << "\n";
    std::cerr << "[codegen] Writing optimized ECS-like source to: " << source_path << "\n";

    // Generate header
    std::string header = generate_header(source_file, devices, connections, port_to_signal, signal_count);
    std::ofstream hfile(header_path);
    if (!hfile.is_open()) {
        std::cerr << "Failed to open: " << header_path << "\n";
        return;
    }
    hfile << header;
    hfile.close();

    // Generate source
    std::string source = generate_source(header_name, devices, connections, port_to_signal, signal_count);
    std::ofstream sfile(source_path);
    if (!sfile.is_open()) {
        std::cerr << "Failed to open: " << source_path << "\n";
        return;
    }
    sfile << source;
    sfile.close();

    std::cerr << "[codegen] Done! Generated ECS-like code with:\n";
    std::cerr << "[codegen]   - Jump table dispatch (60 cases)\n";
    std::cerr << "[codegen]   - Domain scheduling (60 step methods)\n";
    std::cerr << "[codegen]   - __restrict pointers (no aliasing)\n";
    std::cerr << "[codegen]   - AOT_INLINE + AOT_LIKELY/AOT_UNLIKELY\n";
    std::cerr << "[codegen]   - Sparse convergence check\n";
}

void CodeGen::generate_port_registry(const std::string& components_dir, const std::string& output_path) {
    using json = nlohmann::json;

    std::cerr << "[codegen] Generating port registry from " << components_dir << "\n";

    // Structure to hold component port information
    struct ComponentPorts {
        std::string classname;
        std::vector<std::string> ports;
    };

    std::vector<ComponentPorts> all_components;

    // Scan components directory for JSON files
    for (const auto& entry : std::filesystem::directory_iterator(components_dir)) {
        if (entry.path().extension() != ".json") continue;

        std::ifstream file(entry.path());
        if (!file.is_open()) {
            std::cerr << "[codegen] Warning: could not open " << entry.path() << "\n";
            continue;
        }

        try {
            json json;
            file >> json;

            if (!json.contains("classname") || !json.contains("default_ports")) {
                continue;
            }

            ComponentPorts comp;
            comp.classname = json["classname"];

            // Collect all port names
            for (const auto& [port_name, _] : json["default_ports"].items()) {
                comp.ports.push_back(port_name);
            }

            // Sort ports for consistency
            std::sort(comp.ports.begin(), comp.ports.end());

            all_components.push_back(comp);
        } catch (const std::exception& e) {
            std::cerr << "[codegen] Error parsing " << entry.path() << ": " << e.what() << "\n";
        }
    }

    // Sort components by classname
    std::sort(all_components.begin(), all_components.end(),
        [](const ComponentPorts& a, const ComponentPorts& b) {
            return a.classname < b.classname;
        });

    // Collect all unique port names for Param enum
    std::set<std::string> all_port_names;
    for (const auto& comp : all_components) {
        for (const auto& port : comp.ports) {
            all_port_names.insert(port);
        }
    }

    // Generate header file
    std::ostringstream oss;

    oss << "// Auto-generated by codegen from components/*.json\n";
    oss << "// DO NOT EDIT - changes will be overwritten\n";
    oss << "// \n";
    oss << "// This file contains port definitions for all components.\n";
    oss << "// Port offsets are calculated to ensure C++ fields match JSON registry.\n";
    oss << "\n";
    oss << "#pragma once\n";
    oss << "\n";
    oss << "#include <cstdint>\n";
    oss << "#include <string>\n";
    oss << "#include <unordered_map>\n";
    oss << "#include <vector>\n";
    oss << "#include <variant>\n";
    oss << "\n";
    // Forward declare PortNames for Provider pattern
    oss << "namespace an24 {\n";
    oss << "enum class PortNames : uint32_t;\n";
    oss << "} // namespace an24\n";
    oss << "\n";
    // Include Provider pattern and component definitions
    // These are relative to port_registry.h location (src/jit_solver/components/)
    oss << "#include \"provider.h\"\n";
    oss << "#include \"all.h\"\n";
    oss << "\n";
    oss << "namespace an24 {\n";
    oss << "\n";

    // Generate enum for all port names (for Provider pattern)
    oss << "// Port names enum (for constexpr Provider pattern)\n";
    oss << "// Used by AOT components to get compile-time port indices\n";
    oss << "enum class PortNames : uint32_t {\n";
    size_t param_idx = 0;
    for (const auto& port_name : all_port_names) {
        oss << "    " << port_name;
        if (param_idx < all_port_names.size() - 1) oss << ",\n";
        else oss << "\n";
        param_idx++;
    }
    oss << "};\n";
    oss << "\n";

    // Generate enum for component types
    oss << "// Component type enumeration\n";
    oss << "enum class ComponentType {\n";
    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "    " << all_components[i].classname;
        if (i < all_components.size() - 1) oss << ",\n";
        else oss << "\n";
    }
    oss << "};\n";
    oss << "\n";

    // Generate port count constants
    oss << "// Port count for each component\n";
    for (const auto& comp : all_components) {
        oss << "constexpr size_t " << comp.classname << "_PORT_COUNT = " << comp.ports.size() << ";\n";
    }
    oss << "\n";

    // Generate port name lists
    oss << "// Port names for each component (in field declaration order)\n";
    for (const auto& comp : all_components) {
        oss << "constexpr const char* " << comp.classname << "_PORTS[] = {\n";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "    \"" << comp.ports[i] << "\"";
            if (i < comp.ports.size() - 1) oss << ",\n";
            else oss << "\n";
        }
        oss << "};\n";
    }
    oss << "\n";

    // Generate helper function to get ports by classname
    oss << "// Get port names for a component type\n";
    oss << "inline std::vector<std::string> get_component_ports(const std::string& classname) {\n";
    oss << "    static const std::unordered_map<std::string, std::vector<std::string>> registry = {\n";
    for (const auto& comp : all_components) {
        oss << "        {\"" << comp.classname << "\", {";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "\"" << comp.ports[i] << "\"";
            if (i < comp.ports.size() - 1) oss << ", ";
        }
        oss << "}},\n";
    }
    oss << "    };\n";
    oss << "\n";
    oss << "    auto it = registry.find(classname);\n";
    oss << "    if (it != registry.end()) {\n";
    oss << "        return it->second;\n";
    oss << "    }\n";
    oss << "    return {};\n";
    oss << "}\n";
    oss << "\n";

    // Generate ComponentVariant for dynamic component containers (Editor JIT)
    oss << "// Component variant for dynamic component storage (Editor JIT mode)\n";
    oss << "// Enables type-safe storage of any component type without virtual calls\n";
    oss << "using ComponentVariant = std::variant<\n";
    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "    " << all_components[i].classname << "<JitProvider>";
        if (i < all_components.size() - 1) oss << ",\n";
        else oss << "\n";
    }
    oss << ">;\n\n";

    // Generate visitor helper for calling solve methods on variant
    oss << "// Visitor helper for calling solve_electrical on component variant\n";
    oss << "template <typename... Visitors>\n";
    oss << "struct overloaded : Visitors... {\n";
    oss << "    using Visitors::operator()...;\n";
    oss << "};\n\n";

    oss << "// Helper visitor to call solve_electrical on any component\n";
    oss << "inline auto solve_electrical_visitor = [](auto& component, SimulationState& st, float dt) {\n";
    oss << "    component.solve_electrical(st, dt);\n";
    oss << "};\n\n";

    oss << "// Helper visitor to call post_step on any component (optional)\n";
    oss << "inline auto post_step_visitor = [](auto& component, SimulationState& st, float dt) {\n";
    oss << "    if constexpr (requires { component.post_step(st, dt); }) {\n";
    oss << "        component.post_step(st, dt);\n";
    oss << "    }\n";
    oss << "};\n\n";

    oss << "} // namespace an24\n";

    // Write to file
    std::ofstream out(output_path);
    if (!out.is_open()) {
        std::cerr << "[codegen] Error: could not write to " << output_path << "\n";
        return;
    }

    out << oss.str();
    out.close();

    std::cerr << "[codegen] Generated port registry: " << output_path << "\n";
    std::cerr << "[codegen]   - " << all_components.size() << " components\n";

    // Count total ports
    size_t total_ports = 0;
    for (const auto& comp : all_components) {
        total_ports += comp.ports.size();
    }
    std::cerr << "[codegen]   - " << total_ports << " total ports\n";
}

} // namespace an24
