if(EXISTS "/Users/vladimir/an24_cpp/build_off/tests/bake_in_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_off/tests/bake_in_tests[1]_tests.cmake")
else()
  add_test(bake_in_tests_NOT_BUILT bake_in_tests_NOT_BUILT)
endif()
