if(EXISTS "/Users/vladimir/an24_cpp/build_off/tests/canvas_input_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_off/tests/canvas_input_tests[1]_tests.cmake")
else()
  add_test(canvas_input_tests_NOT_BUILT canvas_input_tests_NOT_BUILT)
endif()
