if(EXISTS "/Users/vladimir/an24_cpp/build_off/tests/editor_settings_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_off/tests/editor_settings_tests[1]_tests.cmake")
else()
  add_test(editor_settings_tests_NOT_BUILT editor_settings_tests_NOT_BUILT)
endif()
