if(EXISTS "/Users/vladimir/an24_cpp/build_off/tests/fuel_tank_regression_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_off/tests/fuel_tank_regression_tests[1]_tests.cmake")
else()
  add_test(fuel_tank_regression_tests_NOT_BUILT fuel_tank_regression_tests_NOT_BUILT)
endif()
