if(EXISTS "/Users/vladimir/an24_cpp/build_off/tests/generator_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_off/tests/generator_tests[1]_tests.cmake")
else()
  add_test(generator_tests_NOT_BUILT generator_tests_NOT_BUILT)
endif()
