if(EXISTS "/Users/vladimir/an24_cpp/build_off/tests/pid_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_off/tests/pid_tests[1]_tests.cmake")
else()
  add_test(pid_tests_NOT_BUILT pid_tests_NOT_BUILT)
endif()
