if(EXISTS "/Users/vladimir/an24_cpp/build_off/tests/rug82_regression_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_off/tests/rug82_regression_tests[1]_tests.cmake")
else()
  add_test(rug82_regression_tests_NOT_BUILT rug82_regression_tests_NOT_BUILT)
endif()
