if(EXISTS "/Users/vladimir/an24_cpp/build_off/tests/scene_mutations_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_off/tests/scene_mutations_tests[1]_tests.cmake")
else()
  add_test(scene_mutations_tests_NOT_BUILT scene_mutations_tests_NOT_BUILT)
endif()
