if(EXISTS "/Users/vladimir/an24_cpp/build_off/tests/ui_scene_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_off/tests/ui_scene_tests[1]_tests.cmake")
else()
  add_test(ui_scene_tests_NOT_BUILT ui_scene_tests_NOT_BUILT)
endif()
