if(EXISTS "/Users/vladimir/an24_cpp/build_off/tests/unmapped_port_regression_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_off/tests/unmapped_port_regression_tests[1]_tests.cmake")
else()
  add_test(unmapped_port_regression_tests_NOT_BUILT unmapped_port_regression_tests_NOT_BUILT)
endif()
