if(EXISTS "/Users/vladimir/an24_cpp/build_off/tests/visual_wire_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_off/tests/visual_wire_tests[1]_tests.cmake")
else()
  add_test(visual_wire_tests_NOT_BUILT visual_wire_tests_NOT_BUILT)
endif()
