if(EXISTS "/Users/vladimir/an24_cpp/build_test/tests/bp2_bake_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_test/tests/bp2_bake_tests[1]_tests.cmake")
else()
  add_test(bp2_bake_tests_NOT_BUILT bp2_bake_tests_NOT_BUILT)
endif()
