if(EXISTS "/Users/vladimir/an24_cpp/build_test/tests/clamp_normalize_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_test/tests/clamp_normalize_tests[1]_tests.cmake")
else()
  add_test(clamp_normalize_tests_NOT_BUILT clamp_normalize_tests_NOT_BUILT)
endif()
