if(EXISTS "/Users/vladimir/an24_cpp/build_test/tests/electrical_subsolver_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_test/tests/electrical_subsolver_tests[1]_tests.cmake")
else()
  add_test(electrical_subsolver_tests_NOT_BUILT electrical_subsolver_tests_NOT_BUILT)
endif()
