if(EXISTS "/Users/vladimir/an24_cpp/build_test/tests/electric_pump_regression_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_test/tests/electric_pump_regression_tests[1]_tests.cmake")
else()
  add_test(electric_pump_regression_tests_NOT_BUILT electric_pump_regression_tests_NOT_BUILT)
endif()
