if(EXISTS "/Users/vladimir/an24_cpp/build_test/tests/pi_zn_tuner_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_test/tests/pi_zn_tuner_tests[1]_tests.cmake")
else()
  add_test(pi_zn_tuner_tests_NOT_BUILT pi_zn_tuner_tests_NOT_BUILT)
endif()
