if(EXISTS "/Users/vladimir/an24_cpp/build_test/tests/push_state_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/build_test/tests/push_state_tests[1]_tests.cmake")
else()
  add_test(push_state_tests_NOT_BUILT push_state_tests_NOT_BUILT)
endif()
