#include "codegen_internal.h"

#include <core/model/component_kind.h>

#include <cstring>
#include <fstream>
#include <iostream>
#include <set>
#include <spdlog/spdlog.h>
#include <unordered_set>
#include <variant>

void warn_lua_script_devices(const std::vector<ResolvedDevice>& devices) {
    for (const auto& dev : devices) {
        if (dev.kind == ComponentKind::LuaScript) {
            spdlog::warn(
                "=========================================================\n"
                "[AOT WARNING] LuaScript node '{}' found in simulation.\n"
                "  LuaScript relies on a Lua interpreter which is NOT available\n"
                "  on AOT/embedded targets. Replace with native composite nodes\n"
                "  before deploying to production.\n"
                "=========================================================",
                dev.name);
        }
    }
}

namespace {

/// Solver role kind constants — single source of truth for codegen predicates.
static constexpr SolverRoleKind KNOB_SWITCH_BRANCHES_ROLE = SolverRoleKind::KnobSwitchBranches;

struct PortMeta {
    std::string name;
    bp2::Direction direction = bp2::Direction::Output;
    Domain domain = Domain::Electrical;
    bool source_writer = false;
};

/// Codegen representation of a param entry from param_schema.
struct CodegenParam {
    std::string name;             ///< JSON param key (e.g. "v_nominal")
    std::string field;            ///< C++ field name override (empty = same as name)
    ParamSchemaType type;         ///< float/int/bool/string/table
    std::string default_value;    ///< From param_defaults (string form)
    std::string arena_field_offset; ///< For table type: component field receiving arena offset
    std::string arena_field_size;   ///< For table type: component field receiving entry count
};

struct ComponentPorts {
    std::string classname;
    std::vector<PortMeta> ports;
    std::vector<CodegenParam> params;
    std::optional<SolverRoleKind> solver_role_kind;  ///< nullopt if no solver_role
    SchedulerRoleKind scheduler_role_kind = SchedulerRoleKind::Consumer;
};

std::vector<ComponentPorts> build_component_metadata(const ComponentRegistry& registry) {
    std::vector<ComponentPorts> all_components;

    for (const auto& [name, spec] : registry.all_types()) {
        (void)name;
        const auto* def = as_primitive(spec);
        if (!def) {
            continue;
        }

        ComponentPorts comp;
        comp.classname = def->classname;
        comp.solver_role_kind = def->solver.solver_role.has_value()
            ? std::optional<SolverRoleKind>(def->solver.solver_role->kind) : std::nullopt;
        comp.scheduler_role_kind = def->solver.scheduler_role_kind;

        // Collect non-visual-only params sorted by name for deterministic codegen
        for (const auto& [param_name, param_spec] : def->params) {
            if (param_spec.visual_only) continue;
            CodegenParam cp;
            cp.name = param_name;
            cp.field = param_spec.field.empty() ? param_name : param_spec.field;
            cp.type = param_spec.type;
            cp.default_value = param_spec.default_value;
            cp.arena_field_offset = param_spec.arena_field_offset;
            cp.arena_field_size = param_spec.arena_field_size;
            comp.params.push_back(std::move(cp));
        }
        std::sort(comp.params.begin(), comp.params.end(),
            [](const CodegenParam& a, const CodegenParam& b) { return a.name < b.name; });

        for (const auto& [port_name, port] : def->ports) {
            PortMeta meta;
            meta.name = port_name;
            meta.direction = port.direction;
            meta.domain = port.domain;
            meta.source_writer = port.source_writer;
            comp.ports.push_back(std::move(meta));
        }
        std::sort(comp.ports.begin(), comp.ports.end(),
            [](const PortMeta& a, const PortMeta& b) { return a.name < b.name; });
        all_components.push_back(std::move(comp));
    }

    std::sort(all_components.begin(), all_components.end(),
        [](const ComponentPorts& a, const ComponentPorts& b) { return a.classname < b.classname; });

    return all_components;
}

void generate_port_names_header(const std::string& output_path, const std::set<std::string>& all_port_names) {
    std::string dir = output_path;
    auto slash = dir.find_last_of("/\\");
    if (slash != std::string::npos) {
        dir = dir.substr(0, slash + 1);
    } else {
        dir.clear();
    }
    std::string const port_names_path = dir + "port_names.h";

    std::ostringstream pn;
    pn << "// Auto-generated by codegen from library/*.blueprint\n";
    pn << "// DO NOT EDIT - changes will be overwritten\n\n";
    pn << "#pragma once\n\n";
    pn << "#include <cstdint>\n\n";
    pn << "enum class PortNames : uint32_t {\n";
    for (const auto& port_name : all_port_names) {
        pn << "    " << port_name << ",\n";
    }
    pn << "    _COUNT\n";
    pn << "};\n";

    std::ofstream pn_out(port_names_path);
    if (pn_out.is_open()) {
        pn_out << pn.str();
        pn_out.close();
    }
}

// ======================================================================
// Build factory codegen — data-driven dispatch table approach
// ======================================================================

/// Convert a default value string to a valid C++ float literal.
static std::string float_literal(const std::string& v) {
    if (v.empty()) return "0.0f";
    if (v.find('.') != std::string::npos || v.find('e') != std::string::npos || v.find('E') != std::string::npos) {
        return v + "f";
    }
    return v + ".0f";
}

/// Emit a single param assignment line with given indentation.
/// Returns true if code was emitted (false for table params, handled separately).
static bool emit_param_assignment(std::ostringstream& oss, const CodegenParam& p, const char* indent = "    ") {
    const std::string& def = p.default_value;

    switch (p.type) {
    case ParamSchemaType::Float:
        oss << indent << "comp." << p.field << " = param_reader.consume_float_optional(\""
            << p.name << "\", " << float_literal(def) << ");\n";
        return true;
    case ParamSchemaType::Int:
        oss << indent << "comp." << p.field << " = static_cast<int>(param_reader.consume_float_optional(\""
            << p.name << "\", " << float_literal(def) << "));\n";
        return true;
    case ParamSchemaType::Bool:
        oss << indent << "comp." << p.field << " = param_reader.consume_bool_optional(\""
            << p.name << "\", " << (def == "true" || def == "1" ? "true" : "false") << ");\n";
        return true;
    case ParamSchemaType::String:
        oss << indent << "comp." << p.field << " = param_reader.consume_string_optional(\""
            << p.name << "\", \"" << p.default_value << "\");\n";
        return true;
    case ParamSchemaType::Table:
        return false;
    }
    return false;
}

/// Determine scheduler role string for the generic template.
static const char* scheduler_role_for(const ComponentPorts& comp) {
    switch (comp.scheduler_role_kind) {
        case SchedulerRoleKind::None:    return "None";
        case SchedulerRoleKind::Source:  return "Source";
        case SchedulerRoleKind::Consumer: return "Consumer";
    }
    return "Consumer";
}

/// Emit the scheduler registration line derived from component metadata.
/// Uses the same logic as build_generic's if constexpr dispatch.
static void emit_scheduler_add(std::ostringstream& oss, const ComponentPorts& comp, const char* indent = "    ") {
    const std::string& cn = comp.classname;
    switch (comp.scheduler_role_kind) {
        case SchedulerRoleKind::None:
            // No scheduler registration — managed by subsolver
            break;
        case SchedulerRoleKind::Source:
            oss << indent << "result.scheduler.add_source(&std::get<" << cn << "<JitProvider>>(result.devices[dev.name]));\n";
            break;
        case SchedulerRoleKind::Consumer:
            oss << indent << "result.scheduler.add_consumer(&std::get<" << cn << "<JitProvider>>(result.devices[dev.name]));\n";
            break;
    }
}

/// Does this component require a special (non-generic) builder?
/// Special cases: LUT (table arena allocation), RefNode (fixed signal registration).
static bool needs_special_builder(const ComponentPorts& comp) {
    if (comp.solver_role_kind == SolverRoleKind::FixedVoltageNode) return true;
    for (const auto& p : comp.params) {
        if (p.type == ParamSchemaType::Table) return true;
    }
    return false;
}

/// Emit the consume_params() overload for a single component.
/// Overloaded on CompType — the generic build template calls the right one via ADL.
static void emit_consume_params_overload(std::ostringstream& oss, const ComponentPorts& comp) {
    const std::string& cn = comp.classname;
    oss << "static void consume_params(" << cn << "<JitProvider>& comp, ParamReader& param_reader) {\n";
    bool emitted = false;
    for (const auto& p : comp.params) {
        if (p.type != ParamSchemaType::Table) {
            emit_param_assignment(oss, p, "    ");
            emitted = true;
        }
    }
    if (!emitted) {
        oss << "    (void)comp; (void)param_reader;  // no params\n";
    }
    oss << "}\n\n";
}

/// Emit the generic build template — shared construct→finish flow for all vanilla components.
static void emit_build_generic_template(std::ostringstream& oss) {
    oss << R"(/// Generic builder template: construct → consume_params → build_finish.
/// Handles 69/71 components — only LUT (arena) and RefNode (fixed signals) need custom builders.
template <typename CompType, SchedulerRoleKind Role>
static void build_generic(BuildResult& result, const SolverDevice& dev, ParamReader& param_reader) {
     CompType comp;
     consume_params(comp, param_reader);
     if constexpr (requires { comp.pre_load(); }) { comp.pre_load(); }
     setup_component_ports(result, dev, comp);
     param_reader.validate_all_consumed();
     result.devices[dev.name] = std::move(comp);
     if constexpr (Role == SchedulerRoleKind::Consumer)
         result.scheduler.add_consumer(&std::get<CompType>(result.devices[dev.name]));
     else if constexpr (Role == SchedulerRoleKind::Source)
         result.scheduler.add_source(&std::get<CompType>(result.devices[dev.name]));
 }

)";

}

/// Emit the special builder for LUT — arena allocation for table data.
static void emit_build_LUT(std::ostringstream& oss, const ComponentPorts& comp) {
    const std::string& cn = comp.classname;
    oss << "/// Special builder: " << cn << " — table arena allocation before pre_load.\n";
    oss << "static void build_" << cn << "(BuildResult& result, const SolverDevice& dev, ParamReader& param_reader) {\n";
    oss << "    " << cn << "<JitProvider> comp;\n";
    oss << "    consume_params(comp, param_reader);\n";
    // Emit table arena block (function-level indentation)
    for (const auto& p : comp.params) {
        if (p.type != ParamSchemaType::Table) continue;
        oss << "    if (auto it = dev.params.find(\"" << p.name << "\"); it != dev.params.end()) {\n";
        oss << "        const std::string " << p.name << "_str = param_reader.consume_string_optional(\""
            << p.name << "\", \"\");\n";
        oss << "        std::vector<float> keys, vals;\n";
        oss << "        if (" << cn << "<JitProvider>::parse_table(" << p.name << "_str, keys, vals)) {\n";
        oss << "            comp." << p.arena_field_offset << " = static_cast<uint32_t>(result.lut_keys.size());\n";
        oss << "            comp." << p.arena_field_size << " = static_cast<uint16_t>(keys.size());\n";
        oss << "            result.lut_keys.insert(result.lut_keys.end(), keys.begin(), keys.end());\n";
        oss << "            result.lut_values.insert(result.lut_values.end(), vals.begin(), vals.end());\n";
        oss << "        }\n";
        oss << "    }\n";
    }
    oss << "    setup_component_ports(result, dev, comp);\n";
    oss << "    param_reader.validate_all_consumed();\n";
    oss << "    result.devices[dev.name] = std::move(comp);\n";
    emit_scheduler_add(oss, comp);
    oss << "}\n\n";
}

/// Emit the special builder for RefNode — fixed signal registration after build.
static void emit_build_RefNode(std::ostringstream& oss, const ComponentPorts& comp) {
    const std::string& cn = comp.classname;
    oss << "/// Special builder: " << cn << " — fixed signal registration after scheduler add.\n";
    oss << "static void build_" << cn << "(BuildResult& result, const SolverDevice& dev, ParamReader& param_reader) {\n";
    oss << "    " << cn << "<JitProvider> comp;\n";
    oss << "    consume_params(comp, param_reader);\n";
    oss << "    setup_component_ports(result, dev, comp);\n";
    oss << "    param_reader.validate_all_consumed();\n";
    oss << "    result.devices[dev.name] = std::move(comp);\n";
    emit_scheduler_add(oss, comp);
    oss << "    {\n";
    oss << "        const std::string key = dev.name + \".v\";\n";
    oss << "        const core::InternedId iid = result.signal_key_interner.lookup(key);\n";
    oss << "        auto it_sig = result.port_to_signal.find(iid);\n";
    oss << "        if (it_sig != result.port_to_signal.end()) {\n";
    oss << "            result.fixed_signals.push_back(it_sig->second);\n";
    oss << "        }\n";
    oss << "    }\n";
    oss << "}\n\n";
}

/// Emit the dispatch table and main build function.
static void emit_dispatch_table_and_main(std::ostringstream& oss, const std::vector<ComponentPorts>& all_components) {
    oss << R"(/// Dispatch table — one entry per ComponentKind, indexed by enum value.
using BuildFn = void(*)(BuildResult&, const SolverDevice&, ParamReader&);

/// Sentinel for unsupported ComponentKind values (Unknown).
/// Should never be called — guarded by has_component_metadata() check in the main loop.
[[noreturn]] static void build_unsupported(BuildResult&, const SolverDevice& dev, ParamReader&) {
    throw std::runtime_error("No factory handler for component '" + dev.classname + "'");
}

static const BuildFn BUILD_TABLE[] = {
)";

    for (const auto& comp : all_components) {
        const std::string& cn = comp.classname;
        if (comp.solver_role_kind == SolverRoleKind::FixedVoltageNode) {
            oss << "    build_" << cn << ",  // " << cn << " (special: fixed signals)\n";
        } else if (needs_special_builder(comp)) {
            oss << "    build_" << cn << ",  // " << cn << " (special: table arena)\n";
        } else {
            oss << "    build_generic<" << cn << "<JitProvider>, SchedulerRoleKind::" << scheduler_role_for(comp) << ">,  // " << cn << "\n";
        }
    }

    // Sentinel for Unknown — the last real enum value before _COUNT.
    oss << "    build_unsupported,  // Unknown (sentinel — guarded by has_component_metadata)\n";
    oss << "};\n\n";

    // Emit a static_assert that table size matches ComponentKind count
    oss << "static_assert(sizeof(BUILD_TABLE) / sizeof(BUILD_TABLE[0]) == static_cast<size_t>(ComponentKind::_COUNT),\n";
    oss << "    \"BUILD_TABLE size must match ComponentKind count\");\n\n";

    oss << R"(void build_and_register_components(
    BuildResult& result,
    const std::vector<SolverDevice>& devices)
{
    result.devices.reserve(devices.size());  // Prevent rehash invalidating scheduler pointers

    std::vector<std::string> consumer_device_names;

    for (const auto& dev : devices) {
        if (!has_component_metadata(dev.kind)) {
            throw std::runtime_error("Missing generated port metadata for component class '" + dev.classname + "'");
        }

        if (dev.scheduler_role_kind == SchedulerRoleKind::Consumer) {
            consumer_device_names.push_back(dev.name);
        }

        ParamReader param_reader(dev.params, dev);

        BUILD_TABLE[static_cast<size_t>(dev.kind)](result, dev, param_reader);
    }

    // Post-registration pass: Deduplicate fixed signals
    std::sort(result.fixed_signals.begin(), result.fixed_signals.end());
    result.fixed_signals.erase(
        std::unique(result.fixed_signals.begin(), result.fixed_signals.end()),
        result.fixed_signals.end());

    // Sentinel is a fixed signal: always allocated at the end, never changes
    result.fixed_signals.push_back(result.signal_count - 1);

    validate_source_writer_conflicts(result, devices);
    validate_consumer_guardrails(result, consumer_device_names, devices);
    topological_sort_consumers(result, consumer_device_names, devices);
}

}  // namespace jit_solver_impl
)";
}

/// Generate the full build_factory.cpp content into oss.
/// Data-driven approach: per-component consume_params overloads + generic template + dispatch table.
/// Only LUT (arena allocation) and RefNode (fixed signal registration) need custom builders.
static void emit_build_factory_content(std::ostringstream& oss, const std::vector<ComponentPorts>& all_components) {
    oss << "// Auto-generated by codegen from library/*.blueprint\n";
    oss << "// DO NOT EDIT - changes will be overwritten\n\n";
    oss << "#include \"jit_solver_internal.h\"\n";
    oss << "#include \"build_components_common.h\"\n";
    oss << "#include \"components/all.h\"\n";
    oss << "\n";
    oss << "#include <algorithm>\n";
    oss << "\n";
    oss << "namespace jit_solver_impl {\n\n";

    // SchedulerRoleKind is defined in component_types.h — Consumer, Source, None.
    // No local enum needed for build_generic dispatch.

    // Per-component consume_params overloads
    oss << "// Per-component param consumers — the \"data\" in data-driven.\n";
    oss << "// Each overload is selected by the generic template via overload resolution.\n\n";
    for (const auto& comp : all_components) {
        emit_consume_params_overload(oss, comp);
    }

    // Generic template
    emit_build_generic_template(oss);

    // Special builders for non-vanilla components
    for (const auto& comp : all_components) {
        if (comp.solver_role_kind == SolverRoleKind::FixedVoltageNode) {
            emit_build_RefNode(oss, comp);
        } else if (needs_special_builder(comp)) {
            emit_build_LUT(oss, comp);
        }
    }

    // Dispatch table + main function
    emit_dispatch_table_and_main(oss, all_components);
}

// ==============================================================================
// Split emit functions for port_metadata.h (no all.h, no variant)
// ==============================================================================

void emit_port_metadata_prelude(std::ostringstream& oss, const std::vector<ComponentPorts>& all_components) {
    oss << "// Auto-generated by codegen from library/*.blueprint\n";
    oss << "// DO NOT EDIT - changes will be overwritten\n\n";
    oss << "#pragma once\n\n";
    oss << "#include <cstddef>\n";
    oss << "#include <cstdint>\n\n";
    oss << "#include \"core/solvers/common/port_names.h\"\n";
    oss << "#include \"core/model/component_types.h\"\n";
    oss << "#include \"blueprint_v2/interface/direction.h\"\n";
    oss << "#include \"core/model/component_kind.h\"\n\n";

    oss << "/// True for valid ComponentKind values (not Unknown, not _COUNT).\n";
    oss << "inline constexpr bool has_component_metadata(ComponentKind kind) {\n";
    oss << "    return kind != ComponentKind::Unknown && static_cast<size_t>(kind) < static_cast<size_t>(ComponentKind::_COUNT);\n";
    oss << "}\n\n";

    // Struct definitions — the new ABI replacing 355+ global arrays.
    oss << "/// Per-port metadata — name, direction, domain mask, source_writer flag.\n";
    oss << "struct PortMeta {\n";
    oss << "    const char* name;\n";
    oss << "    bp2::Direction direction;\n";
    oss << "    uint8_t domain;\n";
    oss << "    bool source_writer;\n";
    oss << "};\n\n";

    oss << "/// Per-component port info — indexed by ComponentKind.\n";
    oss << "/// Provides port range (offset + count) into PORT_META[] and component-level traits.\n";
    oss << "struct ComponentPortInfo {\n";
    oss << "    size_t port_offset;\n";
    oss << "    size_t port_count;\n";
    oss << "    SchedulerRoleKind scheduler_role_kind;\n";
    oss << "    bool requires_solver_role;\n";
    oss << "};\n\n";
}

void emit_port_metadata_arrays(std::ostringstream& oss, const std::vector<ComponentPorts>& all_components) {
    // Flat array — all ports from all components concatenated, grouped by ComponentKind.
    oss << "constexpr PortMeta PORT_META[] = {\n";
    for (const auto& comp : all_components) {
        oss << "    // " << comp.classname << "\n";
        for (const auto& port : comp.ports) {
            const char* dir_name = "Output";
            if (port.direction == bp2::Direction::Input) dir_name = "Input";
            else if (port.direction == bp2::Direction::InOut) dir_name = "InOut";
            oss << "    {\"" << port.name << "\", bp2::Direction::" << dir_name
                << ", " << static_cast<int>(static_cast<uint8_t>(port.domain))
                << ", " << (port.source_writer ? "true" : "false") << "},\n";
        }
    }
    oss << "};\n\n";

    // Per-component metadata, indexed by ComponentKind enum value.
    oss << "constexpr ComponentPortInfo COMPONENT_PORT_INFO[] = {\n";
    size_t offset = 0;
    for (const auto& comp : all_components) {
        oss << "    {" << offset << ", " << comp.ports.size()
            << ", SchedulerRoleKind::" << scheduler_role_kind_name(comp.scheduler_role_kind)
            << ", " << (comp.solver_role_kind.has_value() ? "true" : "false")
            << "},  // " << comp.classname << "\n";
        offset += comp.ports.size();
    }
    oss << "    {0, 0, SchedulerRoleKind::Consumer, false},  // Unknown (sentinel)\n";
    oss << "};\n\n";

    // Size validation
    oss << "static_assert(sizeof(COMPONENT_PORT_INFO) / sizeof(COMPONENT_PORT_INFO[0]) == static_cast<size_t>(ComponentKind::_COUNT),\n";
    oss << "    \"COMPONENT_PORT_INFO size must match ComponentKind count\");\n";
    oss << "static_assert(" << offset << " == sizeof(PORT_META) / sizeof(PORT_META[0]),\n";
    oss << "    \"PORT_META total entries must match sum of all component port counts\");\n\n";

    // Convenience accessor for port count (replaces per-component *_PORT_COUNT constants).
    oss << "/// Number of ports for a given ComponentKind. Returns 0 for Unknown.\n";
    oss << "inline constexpr size_t port_count(ComponentKind kind) {\n";
    oss << "    if (!has_component_metadata(kind)) return 0;\n";
    oss << "    return COMPONENT_PORT_INFO[static_cast<size_t>(kind)].port_count;\n";
    oss << "}\n\n";
}

// ==============================================================================
// port_traits.h — lookup functions, trait arrays, predicates (NO all.h)
// ==============================================================================

void emit_port_traits_prelude(std::ostringstream& oss) {
    oss << "// Auto-generated by codegen from library/*.blueprint\n";
    oss << "// DO NOT EDIT - changes will be overwritten\n";
    oss << "//\n";
    oss << "// Port traits: lookup functions, trait arrays, and predicate helpers.\n";
    oss << "// Zero component-header dependencies — only needs port_metadata.h + component_kind.h.\n\n";
    oss << "#pragma once\n\n";
    oss << "#include <cstdint>\n";
    oss << "#include <string>\n";
    oss << "#include <unordered_map>\n";
    oss << "#include <optional>\n";
    oss << "#include <vector>\n\n";
    oss << "#include \"core/solvers/common/port_metadata.h\"\n";
    oss << "#include \"core/model/component_kind.h\"\n\n";
}

void emit_port_traits_lookups(
    std::ostringstream& oss,
    const std::vector<ComponentPorts>& all_components,
    const std::set<std::string>& all_port_names
) {
    // Port name string → PortNames enum (used at setup time only)
    oss << "inline std::optional<PortNames> string_to_port_name(const std::string& name) {\n";
    oss << "    static const std::unordered_map<std::string, PortNames> map = {\n";
    for (const auto& port_name : all_port_names) {
        oss << "        {\"" << port_name << "\", PortNames::" << port_name << "},\n";
    }
    oss << "    };\n";
    oss << "    auto it = map.find(name);\n";
    oss << "    if (it != map.end()) return it->second;\n";
    oss << "    return std::nullopt;\n";
    oss << "}\n\n";

    // get_component_ports: data-driven loop over PORT_META + COMPONENT_PORT_INFO
    oss << "inline std::vector<std::string> get_component_ports(ComponentKind kind) {\n";
    oss << "    if (!has_component_metadata(kind)) return {};\n";
    oss << "    const auto& meta = COMPONENT_PORT_INFO[static_cast<size_t>(kind)];\n";
    oss << "    std::vector<std::string> result;\n";
    oss << "    result.reserve(meta.port_count);\n";
    oss << "    for (size_t i = meta.port_offset; i < meta.port_offset + meta.port_count; ++i)\n";
    oss << "        result.push_back(PORT_META[i].name);\n";
    oss << "    return result;\n";
    oss << "}\n\n";

    // get_output_ports: data-driven loop filtering by direction
    oss << "inline std::vector<std::string> get_output_ports(ComponentKind kind) {\n";
    oss << "    if (!has_component_metadata(kind)) return {};\n";
    oss << "    const auto& meta = COMPONENT_PORT_INFO[static_cast<size_t>(kind)];\n";
    oss << "    std::vector<std::string> result;\n";
    oss << "    for (size_t i = meta.port_offset; i < meta.port_offset + meta.port_count; ++i) {\n";
    oss << "        if (PORT_META[i].direction == bp2::Direction::Output ||\n";
    oss << "            PORT_META[i].direction == bp2::Direction::InOut)\n";
    oss << "            result.push_back(PORT_META[i].name);\n";
    oss << "    }\n";
    oss << "    return result;\n";
    oss << "}\n\n";

    // get_source_writer_ports: data-driven loop filtering by source_writer + domain mask
    oss << "inline std::vector<std::string> get_source_writer_ports(ComponentKind kind, uint8_t domain_mask) {\n";
    oss << "    if (!has_component_metadata(kind)) return {};\n";
    oss << "    const auto& meta = COMPONENT_PORT_INFO[static_cast<size_t>(kind)];\n";
    oss << "    std::vector<std::string> result;\n";
    oss << "    for (size_t i = meta.port_offset; i < meta.port_offset + meta.port_count; ++i) {\n";
    oss << "        if (PORT_META[i].source_writer && (PORT_META[i].domain & domain_mask) != 0)\n";
    oss << "            result.push_back(PORT_META[i].name);\n";
    oss << "    }\n";
    oss << "    return result;\n";
    oss << "}\n\n";
}

void emit_port_traits_arrays(std::ostringstream& oss, const std::vector<ComponentPorts>& /*all_components*/) {
    // Component-level traits are now in COMPONENT_PORT_INFO — just provide predicate helpers.
    oss << "inline SchedulerRoleKind component_scheduler_role(ComponentKind kind) {\n";
    oss << "    return has_component_metadata(kind) ? COMPONENT_PORT_INFO[static_cast<size_t>(kind)].scheduler_role_kind : SchedulerRoleKind::Consumer;\n";
    oss << "}\n\n";

    oss << "inline bool is_scheduler_source_component(ComponentKind kind) {\n";
    oss << "    return component_scheduler_role(kind) == SchedulerRoleKind::Source;\n";
    oss << "}\n\n";

    oss << "inline bool is_solver_owned_component(ComponentKind kind) {\n";
    oss << "    return component_scheduler_role(kind) == SchedulerRoleKind::None;\n";
    oss << "}\n\n";

    oss << "inline bool requires_solver_role_component(ComponentKind kind) {\n";
    oss << "    return has_component_metadata(kind) && COMPONENT_PORT_INFO[static_cast<size_t>(kind)].requires_solver_role;\n";
    oss << "}\n\n";
}

// ==============================================================================
// port_queries.h — ComponentVariant + static_asserts (needs all.h)
// ==============================================================================

void emit_port_queries_prelude(std::ostringstream& oss) {
    oss << "// Auto-generated by codegen from library/*.blueprint\n";
    oss << "// DO NOT EDIT - changes will be overwritten\n\n";
    oss << "#pragma once\n\n";
    oss << "#include <variant>\n\n";
    oss << "#include \"core/solvers/common/port_traits.h\"\n";
    oss << "#include \"core/solvers/common/provider.h\"\n";
    oss << "#include \"core/solvers/jit/components/all.h\"\n\n";
}

void emit_port_queries_variant(std::ostringstream& oss, const std::vector<ComponentPorts>& all_components) {
    oss << "using ComponentVariant = std::variant<\n";
    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "    " << all_components[i].classname << "<JitProvider>";
        if (i < all_components.size() - 1) {
            oss << ",\n";
        } else {
            oss << "\n";
        }
    }
    oss << ">;\n\n";

    oss << "static_assert(\n";
    oss << "    std::variant_size_v<ComponentVariant> == static_cast<size_t>(ComponentKind::Unknown),\n";
    oss << "    \"ComponentVariant size doesn't match real component count — re-run update_port_registry\"\n";
    oss << ");\n\n";

    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "static_assert(static_cast<size_t>(ComponentKind::" << all_components[i].classname
            << ") == " << i << "ull, \""
            << all_components[i].classname << " enum position mismatch — re-run update_port_registry\");\n";
    }
    oss << "\n";
}

} // namespace

void CodeGen::write_files(
    const std::string& out_dir,
    const std::string& source_file,
    const std::vector<ResolvedDevice>& devices,
    const std::unordered_map<std::string, uint32_t>& port_to_signal,
    uint32_t signal_count,
    const ElectricalPlanCodegen& electrical_plan_arg
) {
    ElectricalPlanCodegen electrical_plan = electrical_plan_arg;
    if (electrical_plan.islands.empty() && !devices.empty()) {
        electrical_plan = extract_electrical_plan(devices, port_to_signal);
    }

    warn_lua_script_devices(devices);

    std::string base_name = source_file;
    size_t pos = base_name.find_last_of("/\\");
    if (pos != std::string::npos) {
        base_name = base_name.substr(pos + 1);
    }
    pos = base_name.find_last_of('.');
    if (pos != std::string::npos) {
        base_name = base_name.substr(0, pos);
    }
    std::string const header_name = "generated_" + base_name + ".h";

    std::string const header_path = out_dir + "/" + header_name;
    std::string const source_name = "generated_" + base_name + ".cpp";
    std::string const source_path = out_dir + "/" + source_name;

    std::cerr << "[codegen] Writing optimized ECS-like header to: " << header_path << "\n";
    std::cerr << "[codegen] Writing optimized ECS-like source to: " << source_path << "\n";

    std::string const header = generate_header(source_file, devices, port_to_signal, signal_count, "Systems", electrical_plan);
    std::ofstream hfile(header_path);
    if (!hfile.is_open()) {
        std::cerr << "Failed to open: " << header_path << "\n";
        return;
    }
    hfile << header;
    hfile.close();

    std::string const source = generate_source(header_name, devices, port_to_signal, signal_count, "Systems", electrical_plan);
    std::ofstream sfile(source_path);
    if (!sfile.is_open()) {
        std::cerr << "Failed to open: " << source_path << "\n";
        return;
    }
    sfile << source;
    sfile.close();
}

void CodeGen::generate_component_kind(const ComponentRegistry& registry, const std::string& output_path) {
    auto all_components = build_component_metadata(registry);

    std::ostringstream oss;
    oss << "// Auto-generated by codegen from library/*.blueprint\n";
    oss << "// DO NOT EDIT - changes will be overwritten\n\n";
    oss << "#pragma once\n\n";
    oss << "#include <cstdint>\n";
    oss << "#include <optional>\n";
    oss << "#include <string_view>\n\n";

    // Enum — alphabetical order matches codegen iteration order.
    // Unknown: valid sentinel for "not resolved" (in-bounds, safe in switch).
    // _COUNT: array sizing only — never used as a value.
    oss << "/// ComponentKind — enumeration of every primitive component type.\n";
    oss << "/// Resolved once at load/elaboration time from the string classname.\n";
    oss << "/// All downstream dispatch uses this enum instead of string comparison.\n";
    oss << "///\n";
    oss << "/// Unknown — valid sentinel for \"not resolved\". In-bounds, safe in switch,\n";
    oss << "/// but has_component_metadata(Unknown) == false.\n";
    oss << "/// _COUNT — array sizing only. Never used as a value.\n";
    oss << "///\n";
    oss << "/// NOTE: This file is auto-generated. To add a new component, add a\n";
    oss << "/// .blueprint to the library and re-run update_port_registry.\n\n";
    oss << "enum class ComponentKind : uint8_t {\n";
    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "    " << all_components[i].classname << ",\n";
    }
    oss << "    Unknown,\n";
    oss << "    _COUNT\n";
    oss << "};\n\n";

    // parse_component_kind — if-chain (load-time, not hot path)
    oss << "/// Resolve a string classname to ComponentKind. Returns std::nullopt for unknown names.\n";
    oss << "inline std::optional<ComponentKind> parse_component_kind(std::string_view name) {\n";
    for (const auto& comp : all_components) {
        oss << "    if (name == \"" << comp.classname << "\") return ComponentKind::" << comp.classname << ";\n";
    }
    oss << "    return std::nullopt;\n";
    oss << "}\n\n";

    // component_kind_classname — inverse mapping (constexpr)
    oss << "/// Inverse mapping: ComponentKind → string_view classname (for diagnostics/serialization).\n";
    oss << "inline constexpr std::string_view component_kind_classname(ComponentKind kind) {\n";
    oss << "    switch (kind) {\n";
    for (const auto& comp : all_components) {
        oss << "        case ComponentKind::" << comp.classname << ": return \"" << comp.classname << "\";\n";
    }
    oss << "        case ComponentKind::Unknown: return \"Unknown\";\n";
    oss << "        case ComponentKind::_COUNT: return \"_COUNT\";\n";
    oss << "    }\n";
    oss << "    return \"Unknown\";\n";
    oss << "}\n\n";

    // Family predicates — data-driven from solver_role_kind metadata.
    // Each entry: {predicate_name, doc_string, filter}.  New families just add a row.
    struct FamilyDef {
        const char* predicate_name;
        const char* doc_string;
        SolverRoleKind role_kind;
    };
    const FamilyDef families[] = {
        {"is_knob_switch_kind", "KnobSwitch family", KNOB_SWITCH_BRANCHES_ROLE},
    };

    for (const auto& fam : families) {
        std::vector<std::string> members;
        for (const auto& comp : all_components) {
            if (comp.solver_role_kind == fam.role_kind) {
                members.push_back(comp.classname);
            }
        }
        if (members.empty()) continue;

        oss << "/// " << fam.doc_string << ": solver_role.kind == \"" << solver_role_kind_name(fam.role_kind) << "\".\n";
        oss << "inline constexpr bool " << fam.predicate_name << "(ComponentKind kind) {\n";
        if (members.size() == 1) {
            oss << "    return kind == ComponentKind::" << members[0] << ";\n";
        } else {
            oss << "    return ";
            for (size_t i = 0; i < members.size(); ++i) {
                oss << "kind == ComponentKind::" << members[i];
                if (i < members.size() - 1) {
                    oss << " ||\n           ";
                }
            }
            oss << ";\n";
        }
        oss << "}\n\n";
    }

    std::ofstream out(output_path);
    if (!out.is_open()) {
        std::cerr << "[codegen] Error: could not write to " << output_path << "\n";
        return;
    }
    out << oss.str();
    out.close();

    std::cerr << "[codegen] Generated component_kind: " << output_path << "\n";
}

void CodeGen::generate_port_registry(const ComponentRegistry& registry, const std::string& output_path) {
    auto all_components = build_component_metadata(registry);

    std::set<std::string> all_port_names;
    for (const auto& comp : all_components) {
        for (const auto& port : comp.ports) {
            all_port_names.insert(port.name);
        }
    }

    // Determine output directory from output_path
    std::string dir = output_path;
    auto slash = dir.find_last_of("/\\");
    if (slash != std::string::npos) {
        dir = dir.substr(0, slash + 1);
    } else {
        dir.clear();
    }

    // 1. Emit port_metadata.h (no all.h, no variant)
    {
        std::ostringstream oss;
        emit_port_metadata_prelude(oss, all_components);
        emit_port_metadata_arrays(oss, all_components);

        std::string const meta_path = dir + "port_metadata.h";
        std::ofstream out(meta_path);
        if (out.is_open()) {
            out << oss.str();
            out.close();
            std::cerr << "[codegen] Generated port_metadata.h: " << meta_path << "\n";
        }
    }

    // 2. Emit port_traits.h (lookup functions, trait arrays, predicates — NO all.h)
    {
        std::ostringstream oss;
        emit_port_traits_prelude(oss);
        emit_port_traits_lookups(oss, all_components, all_port_names);
        emit_port_traits_arrays(oss, all_components);

        std::string const traits_path = dir + "port_traits.h";
        std::ofstream out(traits_path);
        if (out.is_open()) {
            out << oss.str();
            out.close();
            std::cerr << "[codegen] Generated port_traits.h: " << traits_path << "\n";
        }
    }

    // 3. Emit port_queries.h (ComponentVariant + static_asserts — needs all.h)
    {
        std::ostringstream oss;
        emit_port_queries_prelude(oss);
        emit_port_queries_variant(oss, all_components);

        std::string const queries_path = dir + "port_queries.h";
        std::ofstream out(queries_path);
        if (out.is_open()) {
            out << oss.str();
            out.close();
            std::cerr << "[codegen] Generated port_queries.h: " << queries_path << "\n";
        }
    }

    // 4. Emit port_registry.h (convenience umbrella include)
    {
        std::ostringstream oss;
        oss << "// Auto-generated by codegen from library/*.blueprint\n";
        oss << "// DO NOT EDIT - changes will be overwritten\n";
        oss << "// This file includes all port-related headers for convenience.\n";
        oss << "// For minimal includes, use port_names.h, port_metadata.h, or port_traits.h directly.\n\n";
        oss << "#pragma once\n\n";
        oss << "#include \"port_metadata.h\"\n";
        oss << "#include \"port_traits.h\"\n";
        oss << "#include \"port_queries.h\"\n";

        std::ofstream out(output_path);
        if (out.is_open()) {
            out << oss.str();
            out.close();
            std::cerr << "[codegen] Generated port_registry.h: " << output_path << "\n";
        }
    }

    generate_port_names_header(output_path, all_port_names);
}

void CodeGen::generate_build_factory(const ComponentRegistry& registry, const std::string& output_path) {
    auto all_components = build_component_metadata(registry);

    std::ostringstream oss;
    emit_build_factory_content(oss, all_components);

    std::ofstream out(output_path);
    if (!out.is_open()) {
        std::cerr << "[codegen] Error: could not write to " << output_path << "\n";
        return;
    }
    out << oss.str();
    out.close();

    std::cerr << "[codegen] Generated build factory: " << output_path << "\n";
}
