#include "codegen_internal.h"

#include <fstream>
#include <iostream>
#include <set>
#include <unordered_set>
#include <variant>

namespace {

struct PortMeta {
    std::string name;
    PortDirection direction = PortDirection::Out;
    Domain domain = Domain::Electrical;
    bool source_writer = false;
};

struct ComponentPorts {
    std::string classname;
    std::vector<PortMeta> ports;
    bool scheduler_source = false;
};

std::vector<ComponentPorts> build_component_metadata(const TypeRegistry& registry) {
    std::vector<ComponentPorts> all_components;

    for (const auto& [name, def] : registry.types) {
        (void)name;
        if (!def.cpp_class) {
            continue;
        }

        ComponentPorts comp;
        comp.classname = def.classname;
        comp.scheduler_source = def.scheduler_source;
        for (const auto& [port_name, port] : def.ports) {
            PortMeta meta;
            meta.name = port_name;
            meta.direction = port.direction;
            meta.domain = port.domain;
            meta.source_writer = port.source_writer;
            comp.ports.push_back(std::move(meta));
        }
        std::sort(comp.ports.begin(), comp.ports.end(),
            [](const PortMeta& a, const PortMeta& b) { return a.name < b.name; });
        all_components.push_back(std::move(comp));
    }

    std::sort(all_components.begin(), all_components.end(),
        [](const ComponentPorts& a, const ComponentPorts& b) { return a.classname < b.classname; });

    return all_components;
}

void emit_port_registry_prelude(std::ostringstream& oss, const std::vector<ComponentPorts>& all_components) {
    oss << "// Auto-generated by codegen from library/*.blueprint\n";
    oss << "// DO NOT EDIT - changes will be overwritten\n\n";
    oss << "#pragma once\n\n";
    oss << "#include <cstdint>\n";
    oss << "#include <string>\n";
    oss << "#include <unordered_map>\n";
    oss << "#include <unordered_set>\n";
    oss << "#include <optional>\n";
    oss << "#include <vector>\n";
    oss << "#include <variant>\n\n";
    oss << "#include \"provider.h\"\n";
    oss << "#include \"all.h\"\n";
    oss << "#include \"port_names.h\"\n\n";

    oss << "enum class ComponentType {\n";
    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "    " << all_components[i].classname << ",\n";
    }
    oss << "    _COUNT\n";
    oss << "};\n\n";

    for (const auto& comp : all_components) {
        oss << "constexpr size_t " << comp.classname << "_PORT_COUNT = " << comp.ports.size() << ";\n";
    }
    oss << "\n";
}

void emit_port_registry_metadata(std::ostringstream& oss, const std::vector<ComponentPorts>& all_components) {
    for (const auto& comp : all_components) {
        oss << "constexpr const char* " << comp.classname << "_PORTS[] = {\n";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "    \"" << comp.ports[i].name << "\"";
            if (i < comp.ports.size() - 1) {
                oss << ",\n";
            } else {
                oss << "\n";
            }
        }
        oss << "};\n";
    }
    oss << "\n";

    oss << "enum class RegistryPortDirection : uint8_t { In = 0, Out = 1, InOut = 2 };\n\n";
    for (const auto& comp : all_components) {
        oss << "constexpr RegistryPortDirection " << comp.classname << "_PORT_DIRECTIONS[] = {\n";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            const char* dir_name = "Out";
            if (comp.ports[i].direction == PortDirection::In) {
                dir_name = "In";
            } else if (comp.ports[i].direction == PortDirection::InOut) {
                dir_name = "InOut";
            }
            oss << "    RegistryPortDirection::" << dir_name;
            if (i < comp.ports.size() - 1) {
                oss << ",\n";
            } else {
                oss << "\n";
            }
        }
        oss << "};\n";

        oss << "constexpr uint8_t " << comp.classname << "_PORT_DOMAINS[] = {\n";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "    " << static_cast<int>(static_cast<uint8_t>(comp.ports[i].domain));
            if (i < comp.ports.size() - 1) {
                oss << ",\n";
            } else {
                oss << "\n";
            }
        }
        oss << "};\n";

        oss << "constexpr bool " << comp.classname << "_PORT_SOURCE_WRITER[] = {\n";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "    " << (comp.ports[i].source_writer ? "true" : "false");
            if (i < comp.ports.size() - 1) {
                oss << ",\n";
            } else {
                oss << "\n";
            }
        }
        oss << "};\n";

        oss << "constexpr bool " << comp.classname << "_SCHEDULER_SOURCE = "
            << (comp.scheduler_source ? "true" : "false") << ";\n\n";
    }
}

void emit_port_registry_lookups(
    std::ostringstream& oss,
    const std::vector<ComponentPorts>& all_components,
    const std::set<std::string>& all_port_names
) {
    oss << "inline std::optional<PortNames> string_to_port_name(const std::string& name) {\n";
    oss << "    static const std::unordered_map<std::string, PortNames> map = {\n";
    for (const auto& port_name : all_port_names) {
        oss << "        {\"" << port_name << "\", PortNames::" << port_name << "},\n";
    }
    oss << "    };\n";
    oss << "    auto it = map.find(name);\n";
    oss << "    if (it != map.end()) return it->second;\n";
    oss << "    return std::nullopt;\n";
    oss << "}\n\n";

    oss << "inline std::vector<std::string> get_component_ports(const std::string& classname) {\n";
    oss << "    static const std::unordered_map<std::string, std::vector<std::string>> registry = {\n";
    for (const auto& comp : all_components) {
        oss << "        {\"" << comp.classname << "\", {";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "\"" << comp.ports[i].name << "\"";
            if (i < comp.ports.size() - 1) {
                oss << ", ";
            }
        }
        oss << "}},\n";
    }
    oss << "    };\n";
    oss << "    auto it = registry.find(classname);\n";
    oss << "    if (it != registry.end()) return it->second;\n";
    oss << "    return {};\n";
    oss << "}\n\n";

    oss << "inline bool has_component_metadata(const std::string& classname) {\n";
    oss << "    static const std::unordered_set<std::string> known = {\n";
    for (const auto& comp : all_components) {
        oss << "        \"" << comp.classname << "\",\n";
    }
    oss << "    };\n";
    oss << "    return known.count(classname) > 0;\n";
    oss << "}\n\n";

    oss << "inline bool is_scheduler_source_component(const std::string& classname) {\n";
    oss << "    static const std::unordered_map<std::string, bool> registry = {\n";
    for (const auto& comp : all_components) {
        oss << "        {\"" << comp.classname << "\", " << (comp.scheduler_source ? "true" : "false") << "},\n";
    }
    oss << "    };\n";
    oss << "    auto it = registry.find(classname);\n";
    oss << "    if (it == registry.end()) return false;\n";
    oss << "    return it->second;\n";
    oss << "}\n\n";

    oss << "inline std::vector<std::string> get_output_ports(const std::string& classname) {\n";
    oss << "    std::vector<std::string> result;\n";
    for (const auto& comp : all_components) {
        oss << "    if (classname == \"" << comp.classname << "\") {\n";
        oss << "        for (size_t i = 0; i < " << comp.classname << "_PORT_COUNT; ++i) {\n";
        oss << "            if (" << comp.classname << "_PORT_DIRECTIONS[i] == RegistryPortDirection::Out || "
            << comp.classname << "_PORT_DIRECTIONS[i] == RegistryPortDirection::InOut) result.push_back(" << comp.classname << "_PORTS[i]);\n";
        oss << "        }\n";
        oss << "        return result;\n";
        oss << "    }\n";
    }
    oss << "    return result;\n";
    oss << "}\n\n";

    oss << "inline std::vector<std::string> get_source_writer_ports(const std::string& classname, uint8_t domain_mask) {\n";
    oss << "    std::vector<std::string> result;\n";
    for (const auto& comp : all_components) {
        oss << "    if (classname == \"" << comp.classname << "\") {\n";
        oss << "        for (size_t i = 0; i < " << comp.classname << "_PORT_COUNT; ++i) {\n";
        oss << "            if (" << comp.classname << "_PORT_SOURCE_WRITER[i] && ((" << comp.classname << "_PORT_DOMAINS[i] & domain_mask) != 0)) result.push_back(" << comp.classname << "_PORTS[i]);\n";
        oss << "        }\n";
        oss << "        return result;\n";
        oss << "    }\n";
    }
    oss << "    return result;\n";
    oss << "}\n\n";
}

void emit_port_registry_variant(std::ostringstream& oss, const std::vector<ComponentPorts>& all_components) {
    oss << "using ComponentVariant = std::variant<\n";
    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "    " << all_components[i].classname << "<JitProvider>";
        if (i < all_components.size() - 1) {
            oss << ",\n";
        } else {
            oss << "\n";
        }
    }
    oss << ">;\n\n";

    oss << "static_assert(\n";
    oss << "    std::variant_size_v<ComponentVariant> == static_cast<size_t>(ComponentType::_COUNT),\n";
    oss << "    \"ComponentType enum and ComponentVariant are out of sync — regenerate port_registry.h\"\n";
    oss << ");\n\n";
}

void generate_port_names_header(const std::string& output_path, const std::set<std::string>& all_port_names) {
    std::string dir = output_path;
    auto slash = dir.find_last_of("/\\");
    if (slash != std::string::npos) {
        dir = dir.substr(0, slash + 1);
    } else {
        dir.clear();
    }
    std::string port_names_path = dir + "port_names.h";

    std::ostringstream pn;
    pn << "// Auto-generated by codegen from library/*.blueprint\n";
    pn << "// DO NOT EDIT - changes will be overwritten\n\n";
    pn << "#pragma once\n\n";
    pn << "#include <cstdint>\n\n";
    pn << "enum class PortNames : uint32_t {\n";
    for (const auto& port_name : all_port_names) {
        pn << "    " << port_name << ",\n";
    }
    pn << "    _COUNT\n";
    pn << "};\n";

    std::ofstream pn_out(port_names_path);
    if (pn_out.is_open()) {
        pn_out << pn.str();
        pn_out.close();
    }
}

} // namespace

void CodeGen::write_files(
    const std::string& out_dir,
    const std::string& source_file,
    const std::vector<DeviceInstance>& devices,
    const std::vector<Connection>& connections,
    const std::unordered_map<std::string, uint32_t>& port_to_signal,
    uint32_t signal_count,
    const ElectricalPlanCodegen& electrical_plan_arg
) {
    ElectricalPlanCodegen electrical_plan = electrical_plan_arg;
    if (electrical_plan.islands.empty() && !devices.empty()) {
        electrical_plan = extract_electrical_plan(devices, port_to_signal);
    }

    std::string base_name = source_file;
    size_t pos = base_name.find_last_of("/\\");
    if (pos != std::string::npos) {
        base_name = base_name.substr(pos + 1);
    }
    pos = base_name.find_last_of('.');
    if (pos != std::string::npos) {
        base_name = base_name.substr(0, pos);
    }
    std::string header_name = "generated_" + base_name + ".h";

    std::string header_path = out_dir + "/" + header_name;
    std::string source_name = "generated_" + base_name + ".cpp";
    std::string source_path = out_dir + "/" + source_name;

    std::cerr << "[codegen] Writing optimized ECS-like header to: " << header_path << "\n";
    std::cerr << "[codegen] Writing optimized ECS-like source to: " << source_path << "\n";

    std::string header = generate_header(source_file, devices, connections, port_to_signal, signal_count, "Systems", electrical_plan);
    std::ofstream hfile(header_path);
    if (!hfile.is_open()) {
        std::cerr << "Failed to open: " << header_path << "\n";
        return;
    }
    hfile << header;
    hfile.close();

    std::string source = generate_source(header_name, devices, connections, port_to_signal, signal_count, "Systems", electrical_plan);
    std::ofstream sfile(source_path);
    if (!sfile.is_open()) {
        std::cerr << "Failed to open: " << source_path << "\n";
        return;
    }
    sfile << source;
    sfile.close();
}

void CodeGen::generate_port_registry(const TypeRegistry& registry, const std::string& output_path) {
    auto all_components = build_component_metadata(registry);

    std::set<std::string> all_port_names;
    for (const auto& comp : all_components) {
        for (const auto& port : comp.ports) {
            all_port_names.insert(port.name);
        }
    }

    std::ostringstream oss;
    emit_port_registry_prelude(oss, all_components);
    emit_port_registry_metadata(oss, all_components);
    emit_port_registry_lookups(oss, all_components, all_port_names);
    emit_port_registry_variant(oss, all_components);

    std::ofstream out(output_path);
    if (!out.is_open()) {
        std::cerr << "[codegen] Error: could not write to " << output_path << "\n";
        return;
    }
    out << oss.str();
    out.close();

    generate_port_names_header(output_path, all_port_names);
}
