#include "codegen_internal.h"

#include <fstream>
#include <iostream>
#include <set>
#include <unordered_set>
#include <variant>

namespace {

struct PortMeta {
    std::string name;
    bp2::Direction direction = bp2::Direction::Output;
    Domain domain = Domain::Electrical;
    bool source_writer = false;
};

/// Codegen representation of a param entry from param_schema.
struct CodegenParam {
    std::string name;             ///< JSON param key (e.g. "v_nominal")
    std::string field;            ///< C++ field name override (empty = same as name)
    ParamSchemaType type;         ///< float/int/bool/string/table
    std::string default_value;    ///< From param_defaults (string form)
    std::string arena_field_offset; ///< For table type: component field receiving arena offset
    std::string arena_field_size;   ///< For table type: component field receiving entry count
};

struct ComponentPorts {
    std::string classname;
    std::vector<PortMeta> ports;
    std::vector<CodegenParam> params;
    std::string solver_role_kind;  ///< Empty if no solver_role, else e.g. "FixedVoltageNode"
    bool scheduler_source = false;
    bool solver_owned_electrical = false;
};

std::vector<ComponentPorts> build_component_metadata(const ComponentRegistry& registry) {
    std::vector<ComponentPorts> all_components;

    for (const auto& [name, spec] : registry.types) {
        (void)name;
        const auto* def = as_primitive(spec);
        if (!def) {
            continue;
        }

        ComponentPorts comp;
        comp.classname = def->classname;
        comp.solver_role_kind = def->solver.solver_role.has_value()
            ? def->solver.solver_role->kind : "";
        comp.scheduler_source = def->solver.scheduler_source;
        comp.solver_owned_electrical = def->solver.solver_owned_electrical;

        // Collect non-visual-only params sorted by name for deterministic codegen
        for (const auto& [param_name, param_spec] : def->params) {
            if (param_spec.visual_only) continue;
            CodegenParam cp;
            cp.name = param_name;
            cp.field = param_spec.field.empty() ? param_name : param_spec.field;
            cp.type = param_spec.type;
            cp.default_value = param_spec.default_value;
            cp.arena_field_offset = param_spec.arena_field_offset;
            cp.arena_field_size = param_spec.arena_field_size;
            comp.params.push_back(std::move(cp));
        }
        std::sort(comp.params.begin(), comp.params.end(),
            [](const CodegenParam& a, const CodegenParam& b) { return a.name < b.name; });

        for (const auto& [port_name, port] : def->ports) {
            PortMeta meta;
            meta.name = port_name;
            meta.direction = port.direction;
            meta.domain = port.domain;
            meta.source_writer = port.source_writer;
            comp.ports.push_back(std::move(meta));
        }
        std::sort(comp.ports.begin(), comp.ports.end(),
            [](const PortMeta& a, const PortMeta& b) { return a.name < b.name; });
        all_components.push_back(std::move(comp));
    }

    std::sort(all_components.begin(), all_components.end(),
        [](const ComponentPorts& a, const ComponentPorts& b) { return a.classname < b.classname; });

    return all_components;
}

void emit_port_registry_prelude(std::ostringstream& oss, const std::vector<ComponentPorts>& all_components) {
    oss << "// Auto-generated by codegen from library/*.blueprint\n";
    oss << "// DO NOT EDIT - changes will be overwritten\n\n";
    oss << "#pragma once\n\n";
    oss << "#include <cstdint>\n";
    oss << "#include <string>\n";
    oss << "#include <unordered_map>\n";
    oss << "#include <optional>\n";
    oss << "#include <stdexcept>\n";
    oss << "#include <vector>\n";
    oss << "#include <variant>\n\n";
    oss << "#include \"provider.h\"\n";
    oss << "#include \"all.h\"\n";
    oss << "#include \"port_names.h\"\n";
    oss << "#include \"core/model/component_kind.h\"\n\n";

    for (const auto& comp : all_components) {
        oss << "constexpr size_t " << comp.classname << "_PORT_COUNT = " << comp.ports.size() << ";\n";
    }
    oss << "\n";
}

void emit_port_registry_metadata(std::ostringstream& oss, const std::vector<ComponentPorts>& all_components) {
    for (const auto& comp : all_components) {
        oss << "constexpr const char* " << comp.classname << "_PORTS[] = {\n";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "    \"" << comp.ports[i].name << "\"";
            if (i < comp.ports.size() - 1) {
                oss << ",\n";
            } else {
                oss << "\n";
            }
        }
        oss << "};\n";
    }
    oss << "\n";

    oss << "#include \"../../../../blueprint_v2/interface/direction.h\"\n\n";
    for (const auto& comp : all_components) {
        oss << "constexpr bp2::Direction " << comp.classname << "_PORT_DIRECTIONS[] = {\n";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            const char* dir_name = "Output";
            if (comp.ports[i].direction == bp2::Direction::Input) {
                dir_name = "Input";
            } else if (comp.ports[i].direction == bp2::Direction::InOut) {
                dir_name = "InOut";
            }
            oss << "    bp2::Direction::" << dir_name;
            if (i < comp.ports.size() - 1) {
                oss << ",\n";
            } else {
                oss << "\n";
            }
        }
        oss << "};\n";

        oss << "constexpr uint8_t " << comp.classname << "_PORT_DOMAINS[] = {\n";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "    " << static_cast<int>(static_cast<uint8_t>(comp.ports[i].domain));
            if (i < comp.ports.size() - 1) {
                oss << ",\n";
            } else {
                oss << "\n";
            }
        }
        oss << "};\n";

        oss << "constexpr bool " << comp.classname << "_PORT_SOURCE_WRITER[] = {\n";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "    " << (comp.ports[i].source_writer ? "true" : "false");
            if (i < comp.ports.size() - 1) {
                oss << ",\n";
            } else {
                oss << "\n";
            }
        }
        oss << "};\n";
    }
}

void emit_port_registry_lookups(
    std::ostringstream& oss,
    const std::vector<ComponentPorts>& all_components,
    const std::set<std::string>& all_port_names
) {
    // Port name string → PortNames enum (used at setup time only)
    oss << "inline std::optional<PortNames> string_to_port_name(const std::string& name) {\n";
    oss << "    static const std::unordered_map<std::string, PortNames> map = {\n";
    for (const auto& port_name : all_port_names) {
        oss << "        {\"" << port_name << "\", PortNames::" << port_name << "},\n";
    }
    oss << "    };\n";
    oss << "    auto it = map.find(name);\n";
    oss << "    if (it != map.end()) return it->second;\n";
    oss << "    return std::nullopt;\n";
    oss << "}\n\n";

    // ComponentKind → port list (switch dispatch, no hash map)
    oss << "inline std::vector<std::string> get_component_ports(ComponentKind kind) {\n";
    oss << "    switch (kind) {\n";
    for (const auto& comp : all_components) {
        oss << "        case ComponentKind::" << comp.classname << ": return {";
        for (size_t i = 0; i < comp.ports.size(); ++i) {
            oss << "\"" << comp.ports[i].name << "\"";
            if (i < comp.ports.size() - 1) {
                oss << ", ";
            }
        }
        oss << "};\n";
    }
    oss << "        default: return {};\n";
    oss << "    }\n";
    oss << "}\n\n";

    // has_component_metadata: bounds-checked enum validity
    oss << "inline bool has_component_metadata(ComponentKind kind) {\n";
    oss << "    const auto idx = static_cast<size_t>(kind);\n";
    oss << "    return idx < static_cast<size_t>(ComponentKind::_COUNT);\n";
    oss << "}\n\n";

    // get_output_ports: switch on ComponentKind (O(1) jump table)
    oss << "inline std::vector<std::string> get_output_ports(ComponentKind kind) {\n";
    oss << "    std::vector<std::string> result;\n";
    oss << "    switch (kind) {\n";
    for (const auto& comp : all_components) {
        oss << "        case ComponentKind::" << comp.classname << ":\n";
        oss << "            for (size_t i = 0; i < " << comp.classname << "_PORT_COUNT; ++i) {\n";
        oss << "                if (" << comp.classname << "_PORT_DIRECTIONS[i] == bp2::Direction::Output || "
            << comp.classname << "_PORT_DIRECTIONS[i] == bp2::Direction::InOut)\n";
        oss << "                    result.push_back(" << comp.classname << "_PORTS[i]);\n";
        oss << "            }\n";
        oss << "            return result;\n";
    }
    oss << "        default: return result;\n";
    oss << "    }\n";
    oss << "}\n\n";

    // get_source_writer_ports: switch on ComponentKind (O(1) jump table)
    oss << "inline std::vector<std::string> get_source_writer_ports(ComponentKind kind, uint8_t domain_mask) {\n";
    oss << "    std::vector<std::string> result;\n";
    oss << "    switch (kind) {\n";
    for (const auto& comp : all_components) {
        oss << "        case ComponentKind::" << comp.classname << ":\n";
        oss << "            for (size_t i = 0; i < " << comp.classname << "_PORT_COUNT; ++i) {\n";
        oss << "                if (" << comp.classname << "_PORT_SOURCE_WRITER[i] && ((" << comp.classname << "_PORT_DOMAINS[i] & domain_mask) != 0))\n";
        oss << "                    result.push_back(" << comp.classname << "_PORTS[i]);\n";
        oss << "            }\n";
        oss << "            return result;\n";
    }
    oss << "        default: return result;\n";
    oss << "    }\n";
    oss << "}\n\n";
}

void emit_port_registry_component_traits(
    std::ostringstream& oss,
    const std::vector<ComponentPorts>& all_components
) {
    // Per-component constexpr booleans (already emitted as part of metadata).
    // Now emit indexed lookup arrays for fast enum → trait queries.

    // scheduler_source: indexed by ComponentKind
    oss << "constexpr bool COMPONENT_SCHEDULER_SOURCE[] = {\n";
    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "    " << (all_components[i].scheduler_source ? "true" : "false")
            << (i < all_components.size() - 1 ? ",\n" : "\n");
    }
    oss << "};\n\n";

    // solver_owned_electrical: indexed by ComponentKind
    oss << "constexpr bool COMPONENT_SOLVER_OWNED_ELECTRICAL[] = {\n";
    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "    " << (all_components[i].solver_owned_electrical ? "true" : "false")
            << (i < all_components.size() - 1 ? ",\n" : "\n");
    }
    oss << "};\n\n";

    // requires_solver_role: component has solver_role defined
    oss << "constexpr bool COMPONENT_REQUIRES_SOLVER_ROLE[] = {\n";
    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "    " << (!all_components[i].solver_role_kind.empty() ? "true" : "false")
            << (i < all_components.size() - 1 ? ",\n" : "\n");
    }
    oss << "};\n\n";

    // Lookup functions — O(1) array index, zero string comparison
    oss << "inline bool is_scheduler_source_component(ComponentKind kind) {\n";
    oss << "    const auto idx = static_cast<size_t>(kind);\n";
    oss << "    return idx < static_cast<size_t>(ComponentKind::_COUNT) && COMPONENT_SCHEDULER_SOURCE[idx];\n";
    oss << "}\n\n";

    oss << "inline bool is_solver_owned_electrical_component(ComponentKind kind) {\n";
    oss << "    const auto idx = static_cast<size_t>(kind);\n";
    oss << "    return idx < static_cast<size_t>(ComponentKind::_COUNT) && COMPONENT_SOLVER_OWNED_ELECTRICAL[idx];\n";
    oss << "}\n\n";

    oss << "inline bool requires_solver_role_component(ComponentKind kind) {\n";
    oss << "    const auto idx = static_cast<size_t>(kind);\n";
    oss << "    return idx < static_cast<size_t>(ComponentKind::_COUNT) && COMPONENT_REQUIRES_SOLVER_ROLE[idx];\n";
    oss << "}\n\n";
}

void emit_port_registry_variant(std::ostringstream& oss, const std::vector<ComponentPorts>& all_components) {
    oss << "using ComponentVariant = std::variant<\n";
    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "    " << all_components[i].classname << "<JitProvider>";
        if (i < all_components.size() - 1) {
            oss << ",\n";
        } else {
            oss << "\n";
        }
    }
    oss << ">;\n\n";

    oss << "static_assert(\n";
    oss << "    std::variant_size_v<ComponentVariant> == static_cast<size_t>(ComponentKind::_COUNT),\n";
    oss << "    \"ComponentKind enum and ComponentVariant are out of sync — regenerate port_registry.h\"\n";
    oss << ");\n\n";

    // Round-trip validation: ensures the hand-written ComponentKind enum ordering
    // matches the codegen-sorted component list. Catches silent misindexing if
    // a new component is inserted in the wrong position.
    oss << "// Compile-time ordering check: enum ↔ classname round-trip\n";
    for (size_t i = 0; i < all_components.size(); ++i) {
        oss << "static_assert(static_cast<size_t>(ComponentKind::" << all_components[i].classname
            << ") == " << i << "ull, \""
            << all_components[i].classname << " enum position mismatch — regenerate port_registry.h or update component_kind.h\");\n";
    }
    oss << "\n";
}

void generate_port_names_header(const std::string& output_path, const std::set<std::string>& all_port_names) {
    std::string dir = output_path;
    auto slash = dir.find_last_of("/\\");
    if (slash != std::string::npos) {
        dir = dir.substr(0, slash + 1);
    } else {
        dir.clear();
    }
    std::string port_names_path = dir + "port_names.h";

    std::ostringstream pn;
    pn << "// Auto-generated by codegen from library/*.blueprint\n";
    pn << "// DO NOT EDIT - changes will be overwritten\n\n";
    pn << "#pragma once\n\n";
    pn << "#include <cstdint>\n\n";
    pn << "enum class PortNames : uint32_t {\n";
    for (const auto& port_name : all_port_names) {
        pn << "    " << port_name << ",\n";
    }
    pn << "    _COUNT\n";
    pn << "};\n";

    std::ofstream pn_out(port_names_path);
    if (pn_out.is_open()) {
        pn_out << pn.str();
        pn_out.close();
    }
}

// ======================================================================
// Build factory codegen — all helpers in anonymous namespace
// ======================================================================

/// Build a param signature key — used to detect components sharing the same
/// param set (e.g. KnobSwitch/RotarySwitch1ToN/RotarySwitchNTo1).
/// Includes field name so components with identical JSON params but different
/// C++ field mappings are NOT grouped together.
static std::string param_signature(const ComponentPorts& comp) {
    std::string sig;
    for (const auto& p : comp.params) {
        sig += p.name + ":" + std::to_string(static_cast<int>(p.type)) + ":" + p.field + ",";
    }
    return sig;
}

/// Emit a single param assignment line with given indentation.
/// Returns true if code was emitted (false for table params, handled separately).
static bool emit_param_assignment(std::ostringstream& oss, const CodegenParam& p, const char* indent = "            ") {
    const std::string& def = p.default_value;

    /// Convert a default value string (e.g. "0.005", "2", "1e-6") to a valid C++ float literal.
    auto float_literal = [](const std::string& v) -> std::string {
        if (v.empty()) return "0.0f";
        // If value contains '.' or 'e'/'E', it's already float-like — append 'f'
        if (v.find('.') != std::string::npos || v.find('e') != std::string::npos || v.find('E') != std::string::npos) {
            return v + "f";
        }
        // Pure integer — add ".0f" to make it a valid float literal
        return v + ".0f";
    };

    switch (p.type) {
    case ParamSchemaType::Float:
        oss << indent << "comp." << p.field << " = param_reader.consume_float_optional(\""
            << p.name << "\", " << float_literal(def) << ");\n";
        return true;
    case ParamSchemaType::Int:
        oss << indent << "comp." << p.field << " = static_cast<int>(param_reader.consume_float_optional(\""
            << p.name << "\", " << float_literal(def) << "));\n";
        return true;
    case ParamSchemaType::Bool:
        oss << indent << "comp." << p.field << " = param_reader.consume_bool_optional(\""
            << p.name << "\", " << (def == "true" || def == "1" ? "true" : "false") << ");\n";
        return true;
    case ParamSchemaType::String:
        oss << indent << "comp." << p.field << " = param_reader.consume_string_optional(\""
            << p.name << "\", \"" << p.default_value << "\");\n";
        return true;
    case ParamSchemaType::Table:
        return false;
    }
    return false;
}

/// Emit LUT-style table arena allocation block (indented for switch-case body).
static void emit_table_arena_block(std::ostringstream& oss, const ComponentPorts& comp) {
    for (const auto& p : comp.params) {
        if (p.type != ParamSchemaType::Table) continue;
        oss << "            if (auto it = dev.params.find(\"" << p.name << "\"); it != dev.params.end()) {\n";
        oss << "                const std::string " << p.name << "_str = param_reader.consume_string_optional(\""
            << p.name << "\", \"\");\n";
        oss << "                std::vector<float> keys, vals;\n";
        oss << "                if (" << comp.classname << "<JitProvider>::parse_table(" << p.name << "_str, keys, vals)) {\n";
        oss << "                    comp." << p.arena_field_offset
            << " = static_cast<uint32_t>(result.lut_keys.size());\n";
        oss << "                    comp." << p.arena_field_size
            << " = static_cast<uint16_t>(keys.size());\n";
        oss << "                    result.lut_keys.insert(result.lut_keys.end(), keys.begin(), keys.end());\n";
        oss << "                    result.lut_values.insert(result.lut_values.end(), vals.begin(), vals.end());\n";
        oss << "                }\n";
        oss << "            }\n";
    }
}

/// Emit FixedVoltageNode post-registration logic (indented for switch-case body).
static void emit_fixed_voltage_node_block(std::ostringstream& oss, const ComponentPorts& comp) {
    if (comp.solver_role_kind != "FixedVoltageNode") return;
    oss << "            {\n";
    oss << "                const std::string key = dev.name + \".v\";\n";
    oss << "                const ui::InternedId iid = result.signal_key_interner.lookup(key);\n";
    oss << "                auto it_sig = result.port_to_signal.find(iid);\n";
    oss << "                if (it_sig != result.port_to_signal.end()) {\n";
    oss << "                    result.fixed_signals.push_back(it_sig->second);\n";
    oss << "                }\n";
    oss << "            }\n";
}

/// Emit a single switch case for a component.
static void emit_build_case(std::ostringstream& oss, const ComponentPorts& comp, bool use_helper) {
    const std::string& cn = comp.classname;

    if (use_helper) {
        oss << "        case ComponentKind::" << cn << ": {\n";
        oss << "            build_knob_switch_impl<" << cn << "<JitProvider>>(result, dev, param_reader);\n";
        // Registration: same logic as non-helper path
        if (comp.solver_owned_electrical) {
            // no scheduler registration — managed by electrical subsolver
        } else if (comp.scheduler_source) {
            oss << "            result.scheduler.add_source(&std::get<"
                << cn << "<JitProvider>>(result.devices[dev.name]));\n";
        } else {
            oss << "            result.scheduler.add_consumer(&std::get<"
                << cn << "<JitProvider>>(result.devices[dev.name]));\n";
        }
        emit_fixed_voltage_node_block(oss, comp);
        oss << "            break;\n";
        oss << "        }\n";
        return;
    }

    oss << "        case ComponentKind::" << cn << ": {\n";
    oss << "            " << cn << "<JitProvider> comp;\n";

    // Emit param assignments (non-table first, then table arena block)
    for (const auto& p : comp.params) {
        if (p.type != ParamSchemaType::Table) {
            emit_param_assignment(oss, p);
        }
    }
    emit_table_arena_block(oss, comp);

    oss << "            comp.pre_load();\n";
    oss << "            setup_component_ports(result, dev, comp);\n";
    oss << "            param_reader.validate_all_consumed();\n";
    oss << "            result.devices[dev.name] = std::move(comp);\n";

    // Registration: solver_owned_electrical takes priority (handled by electrical solver)
    if (comp.solver_owned_electrical) {
        // no scheduler registration — managed by electrical subsolver
    } else if (comp.scheduler_source) {
        oss << "            result.scheduler.add_source(&std::get<"
            << cn << "<JitProvider>>(result.devices[dev.name]));\n";
    } else {
        oss << "            result.scheduler.add_consumer(&std::get<"
            << cn << "<JitProvider>>(result.devices[dev.name]));\n";
    }

    // Post-registration special blocks
    emit_fixed_voltage_node_block(oss, comp);

    oss << "            break;\n";
    oss << "        }\n";
}

/// Detect knob-switch families — components sharing identical param schema
/// and solver_role.kind == "KnobSwitchBranches".
static std::map<std::string, std::vector<const ComponentPorts*>>
group_knob_switch_families(const std::vector<ComponentPorts>& all_components) {
    std::map<std::string, std::vector<const ComponentPorts*>> families;
    for (const auto& comp : all_components) {
        if (comp.solver_role_kind == "KnobSwitchBranches") {
            families[param_signature(comp)].push_back(&comp);
        }
    }
    return families;
}

/// Generate the full build_factory.cpp content into oss.
static void emit_build_factory_content(std::ostringstream& oss, const std::vector<ComponentPorts>& all_components) {
    // Detect KnobSwitch families for helper function generation
    auto families = group_knob_switch_families(all_components);
    std::set<std::string> helper_classnames;
    for (const auto& [sig, members] : families) {
        if (members.size() > 1) {
            for (const auto* m : members) {
                helper_classnames.insert(m->classname);
            }
        }
    }

    oss << "// Auto-generated by codegen from library/*.blueprint\n";
    oss << "// DO NOT EDIT - changes will be overwritten\n\n";
    oss << "#include \"jit_solver_internal.h\"\n";
    oss << "#include \"build_components_common.h\"\n";
    oss << "#include \"components/all.h\"\n";
    oss << "\n";
    oss << "#include <algorithm>\n";
    oss << "#include <spdlog/spdlog.h>\n";
    oss << "\n";
    oss << "namespace jit_solver_impl {\n\n";

    // Emit KnobSwitch template helper (only if needed)
    if (!helper_classnames.empty()) {
        oss << "/// Template helper for KnobSwitch-family components.\n";
        oss << "/// Generated because multiple ComponentKinds share identical params.\n";
        oss << "template <typename CompType>\n";
        oss << "static void build_knob_switch_impl(\n";
        oss << "    BuildResult& result, const ResolvedDevice& dev, ParamReader& param_reader)\n";
        oss << "{\n";
        oss << "    CompType comp;\n";

        // Use first family member's params — they're all identical
        const auto& first_family = families.begin()->second;
        const auto& ref = *first_family[0];
        for (const auto& p : ref.params) {
            emit_param_assignment(oss, p, "    ");
        }
        oss << "    comp.pre_load();\n";
        oss << "    setup_component_ports(result, dev, comp);\n";
        oss << "    param_reader.validate_all_consumed();\n";
        oss << "    result.devices[dev.name] = std::move(comp);\n";
        oss << "}\n\n";
    }

    oss << "void build_and_register_components(\n";
    oss << "    BuildResult& result,\n";
    oss << "    const std::vector<ResolvedDevice>& devices)\n";
    oss << "{\n";
    oss << "    std::vector<std::string> consumer_device_names;\n\n";
    oss << "    for (const auto& dev : devices) {\n";
    oss << "        if (!has_component_metadata(dev.kind)) {\n";
    oss << "            throw std::runtime_error(\"Missing generated port metadata for component class '\" + dev.classname + \"'\");\n";
    oss << "        }\n\n";
    oss << "        const bool is_source = dev.scheduler_source;\n";
    oss << "        const bool is_solver_owned = dev.solver_owned_electrical;\n\n";
    oss << "        if (!is_source && !is_solver_owned) {\n";
    oss << "            consumer_device_names.push_back(dev.name);\n";
    oss << "        }\n\n";
    oss << "        ParamReader param_reader(dev.params, dev);\n\n";
    oss << "        switch (dev.kind) {\n";

    for (const auto& comp : all_components) {
        bool use_helper = helper_classnames.count(comp.classname) > 0;
        emit_build_case(oss, comp, use_helper);
    }

    oss << "        default:\n";
    oss << "            throw std::runtime_error(\"Unknown component class '\" + std::string(dev.classname)\n";
    oss << "                + \"' for device '\" + dev.name + \"'. No factory handler registered.\");\n";
    oss << "        }\n";
    oss << "    }\n\n";

    // Post-pass: deduplicate fixed signals + validation
    oss << "    // Post-registration pass: Deduplicate fixed signals\n";
    oss << "    std::sort(result.fixed_signals.begin(), result.fixed_signals.end());\n";
    oss << "    result.fixed_signals.erase(\n";
    oss << "        std::unique(result.fixed_signals.begin(), result.fixed_signals.end()),\n";
    oss << "        result.fixed_signals.end());\n\n";
    oss << "    // Sentinel is a fixed signal: always allocated at the end, never changes\n";
    oss << "    result.fixed_signals.push_back(result.signal_count - 1);\n\n";
    oss << "    validate_source_writer_conflicts(result, devices);\n";
    oss << "    validate_consumer_guardrails(result, consumer_device_names, devices);\n";
    oss << "    topological_sort_consumers(result, consumer_device_names, devices);\n";
    oss << "}\n\n";
    oss << "}  // namespace jit_solver_impl\n";
}

} // namespace

void CodeGen::write_files(
    const std::string& out_dir,
    const std::string& source_file,
    const std::vector<ResolvedDevice>& devices,
    const std::vector<Connection>& connections,
    const std::unordered_map<std::string, uint32_t>& port_to_signal,
    uint32_t signal_count,
    const ElectricalPlanCodegen& electrical_plan_arg
) {
    ElectricalPlanCodegen electrical_plan = electrical_plan_arg;
    if (electrical_plan.islands.empty() && !devices.empty()) {
        electrical_plan = extract_electrical_plan(devices, port_to_signal);
    }

    std::string base_name = source_file;
    size_t pos = base_name.find_last_of("/\\");
    if (pos != std::string::npos) {
        base_name = base_name.substr(pos + 1);
    }
    pos = base_name.find_last_of('.');
    if (pos != std::string::npos) {
        base_name = base_name.substr(0, pos);
    }
    std::string header_name = "generated_" + base_name + ".h";

    std::string header_path = out_dir + "/" + header_name;
    std::string source_name = "generated_" + base_name + ".cpp";
    std::string source_path = out_dir + "/" + source_name;

    std::cerr << "[codegen] Writing optimized ECS-like header to: " << header_path << "\n";
    std::cerr << "[codegen] Writing optimized ECS-like source to: " << source_path << "\n";

    std::string header = generate_header(source_file, devices, connections, port_to_signal, signal_count, "Systems", electrical_plan);
    std::ofstream hfile(header_path);
    if (!hfile.is_open()) {
        std::cerr << "Failed to open: " << header_path << "\n";
        return;
    }
    hfile << header;
    hfile.close();

    std::string source = generate_source(header_name, devices, connections, port_to_signal, signal_count, "Systems", electrical_plan);
    std::ofstream sfile(source_path);
    if (!sfile.is_open()) {
        std::cerr << "Failed to open: " << source_path << "\n";
        return;
    }
    sfile << source;
    sfile.close();
}

void CodeGen::generate_port_registry(const ComponentRegistry& registry, const std::string& output_path) {
    auto all_components = build_component_metadata(registry);

    std::set<std::string> all_port_names;
    for (const auto& comp : all_components) {
        for (const auto& port : comp.ports) {
            all_port_names.insert(port.name);
        }
    }

    std::ostringstream oss;
    emit_port_registry_prelude(oss, all_components);
    emit_port_registry_metadata(oss, all_components);
    emit_port_registry_lookups(oss, all_components, all_port_names);
    emit_port_registry_component_traits(oss, all_components);
    emit_port_registry_variant(oss, all_components);

    std::ofstream out(output_path);
    if (!out.is_open()) {
        std::cerr << "[codegen] Error: could not write to " << output_path << "\n";
        return;
    }
    out << oss.str();
    out.close();

    generate_port_names_header(output_path, all_port_names);
}

void CodeGen::generate_build_factory(const ComponentRegistry& registry, const std::string& output_path) {
    auto all_components = build_component_metadata(registry);

    std::ostringstream oss;
    emit_build_factory_content(oss, all_components);

    std::ofstream out(output_path);
    if (!out.is_open()) {
        std::cerr << "[codegen] Error: could not write to " << output_path << "\n";
        return;
    }
    out << oss.str();
    out.close();

    std::cerr << "[codegen] Generated build factory: " << output_path << "\n";
}
