if(EXISTS "/Users/vladimir/an24_cpp/examples/tests/editor_persist_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/examples/tests/editor_persist_tests[1]_tests.cmake")
else()
  add_test(editor_persist_tests_NOT_BUILT editor_persist_tests_NOT_BUILT)
endif()
