if(EXISTS "/Users/vladimir/an24_cpp/examples/tests/editor_router_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/examples/tests/editor_router_tests[1]_tests.cmake")
else()
  add_test(editor_router_tests_NOT_BUILT editor_router_tests_NOT_BUILT)
endif()
