if(EXISTS "/Users/vladimir/an24_cpp/examples/tests/editor_interaction_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/examples/tests/editor_interaction_tests[1]_tests.cmake")
else()
  add_test(editor_interaction_tests_NOT_BUILT editor_interaction_tests_NOT_BUILT)
endif()
