if(EXISTS "/Users/vladimir/an24_cpp/examples/tests/editor_render_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/examples/tests/editor_render_tests[1]_tests.cmake")
else()
  add_test(editor_render_tests_NOT_BUILT editor_render_tests_NOT_BUILT)
endif()
