if(EXISTS "/Users/vladimir/an24_cpp/examples/tests/jit_solver_tests[1]_tests.cmake")
  include("/Users/vladimir/an24_cpp/examples/tests/jit_solver_tests[1]_tests.cmake")
else()
  add_test(jit_solver_tests_NOT_BUILT jit_solver_tests_NOT_BUILT)
endif()
